<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Español                                                  //
//     - File     : admin_pref.inc                                           //
// 2006-02-24 Jaime E. Gomez H.   jgomez@skinatech.com                       //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// labels
$l_user_pref = "Preferencias de Usuarios";
$l_user_pref_reset = "Colocar valores por omisión en las preferencias de todos los usuarios";
$l_user_pref_update_one = "Cambie el valor por omisión de la opción seleccionada" ;

// Actions
$l_execute = "Ejecute Acción";
$l_help = "Ayuda";

// Messages (+ javascript)
$l_update_ok = "Preferencias actualizadas exitosamente";
$l_update_error = "Actualización de preferencias ha fallado !";
$l_reset_ok = "Preferencias actualizadas a los valores por omisión";
