#!/bin/sh

# Rename sql dirs into module/doc/examples
find -type d -name  sql | while read dir ; do
	doc="$(dirname $dir)/doc" ;
	if [ ! -d $doc ]
		then mkdir -p $doc
	fi
	mv $dir "$doc/examples"
done

# Move all sql files into module/doc/examples
find -type f -name *\sql -not -path '*examples*' | while read file ; do
	dir=$(basename $(dirname $file))
	mod=$(echo $file | awk -F '/' '{ print $2 }')
	if [ "$dir" != "examples" ] ; then
		ex="${mod}/doc/examples"
		if [ ! -d $ex ]
			then mkdir -p $ex
		fi
		mv $file $ex
	fi
done

# Remove all CVS files
find -type d -name CVS -o -type f -name .cvsignore |
	while read cvs ; do
		rm -rf ${cvs}
	done

find -path '*doc*' -type f -exec chmod 644 {} \;
