<img src='image/LinePlot-1.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-2.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-3.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-4.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-5.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-6.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-7.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-8.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-9.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-10.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-11.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-12.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-13.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-14.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-15.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-16.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-17.test.php' border=2 bordercolor=black/>
<img src='image/LinePlot-18.test.php' border=2 bordercolor=black/>