<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Romanian                                                   //
//     - File     : document.inc                                             //
// 2003-08-21 Rande Mehdi                                                    //
///////////////////////////////////////////////////////////////////////////////
// $Id: document.inc 2972 2008-07-02 09:42:54Z mehdi $
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-18T15:38:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:47:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:47:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:55:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:03:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:35:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:41:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:44:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:57:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:18:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:27:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:29:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:41:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:59:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:59:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:06:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:08:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:11:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:12:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:13:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:14:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:15:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:15:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:17:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:19:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:19:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:21:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:25:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:26:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:27:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:28:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:29:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:29:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:30:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:39:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:39:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:40:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:41:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:54:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:56:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:58:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:59:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:59:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:03:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:04:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:05:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:06:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:14:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:19:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:20:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:21:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:22:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:22:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:23:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:23:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:25:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:26:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:26:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:27:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:27:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:29:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:30:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:35:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:35:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:37:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:37:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:38:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:40:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:40:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:42:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:42:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:43:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:43:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:44:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:48:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:50:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:50:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:57:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:57:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:02:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:02:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:09:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:16:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:22:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:23:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:25:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:26:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:30:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:32:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:31:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:32:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:35:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:22:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:29:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:29:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:31:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:34:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:34:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:41:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:44:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:44:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:46:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:46:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:46:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:46:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:48:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:48:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:48:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:48:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:49:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:51:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T16:58:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:10:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:18:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:19:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:19:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:19:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:20:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:27:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:27:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:30:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T17:30:40+02:00 using OBMtranslation (0.4.1)

$l_author = "Autor";
$l_createtime = "Data de creare";
$l_extension = "Extensiune";
$l_mime_label = "Etichetă";
$l_mime_manage = "Gestiunea tipurilor MIME";
$l_mime_exist = "Tipuri MIME existente";
$l_mime_new = "Tip MIME Nou "; 
$l_mimetype = "Tip MIME";
$l_mime_delete = "Ștergeți";
$l_path = "Repertoriu";
$l_title = "Titlu";
$l_updatetime = "Ultima modificare";
$l_document_display = "Opțiuni de vizualizare a listelor de documente";
$l_size = "Mărime";
$l_bytes = "bytes";
$l_header_new_dir = "Directoriu nou";
$l_dir = "Directoriu";
$l_add_dir = "Creați directoriul";
$l_update_dir = "Actualizați";
$l_header_tree = "Arborescență";
$l_auto = "Predefinit";
$l_consult = "Consultați documentul";
$l_url = "Adresă";
$l_add = "Adăugați documentele";
$l_mime_link_document = "Tipul MIME este asociat acestor ducumente";
$l_mime_link_document_no = "Tipul MIME nu este inclus în niciun document";
$l_mime_can_delete = "Tipul MIME poate fi șters";
$l_mime_cant_delete = "Tipul MIME nu poate fi șters";
$l_found = "document(e) găsit(e)";
$l_mime_checkdelete = "Verificați sau ștergeți tipul MIME";
$l_mime_update = "Actualizați tipul MIME";
$l_mime_insert = "Introduceți un tip MIME";
$l_mime_delete_ok = "Ștergerea tipului MIME a fost corect efectuată.";
$l_mime_delete_error = "Ștergerea tipului MIME a eșuat!";
$l_mime_insert_ok = "Introducerea tipului MIME a fost efectuată corect.";
$l_mime_insert_error = "Introducerea tipului MIME a eșuat!";
$l_mime_update_ok = "Modificarea tipului MIME a fost corect efectuată";
$l_mime_update_error = "Modificarea tipului MIME a eșuat!";
$l_no_found = "Niciun document nu corespunde acestor criterii!";
$l_no_display = "Completați spațiile și apăsați butonul  <Caută > pentru a obține lista documentelor corespunzătoare.";
$l_new_file = "Fișier nou";
$l_link = "Link HTTP";
$l_links = "Link HTTPS";
$l_kind = "Tip de document";
$l_invalid_link_file = "Imposibil de a creea un alias pentru un link";
$l_invalid_url = "Adresă invalidă";
$l_noupdate_file = "Nu schimbați fișierul";
$l_update_file = "Schimbați fișierul";
$l_create_file_error = "Eroare înregistrată în timpul creări unui fișier";
$l_delete_file_error = "Ștergerea fișierului acestui document a eșuat!";
$l_can_delete = "Documentul poate fi șters.";
$l_cant_delete = "Documentul nu poate fi șters!";
$l_err_system_path = "Directoarele Root și Default nu pot fi șterse!";
$l_err_dir_no_empty = "Directoriul nu este gol!";
$l_dir_can_delete = "Directoriul poate fi șters.";
$l_dir_cant_delete = "Directoriul nu poate fi șters!";
$l_browse = "Parcurgeți";
$l_have_link = "Acest document este asociat mai multor aplicații OBM";
$l_have_no_link = "Acest document nu este asociat niciunui element";
$l_no_document = "Niciun document";
$l_checkdelete = "Verificați sau ștergeți documentul";
$l_delete = "Ștergeți documentul";
$l_insert = "Introduceți documentul";
$l_update = "Modificați documentul";
$l_dir_delete = "Ștergeți directoriul";
$l_fill_title = "Trebuie să introduceți un Titlu înainte de a valida.";
$l_fill_author = "Introduceți Autorul înainte de a valida.";
$l_fill_path = "Trebuie să indicați repertoriul înainte de a valida.";
$l_j_mime_create = "Completați toate câmpurile de tip MIME";
$l_j_mime_update = "Completați toate câmpurile de tip MIME";
$l_j_mime_delete = "Selectați un tip MIME";
$l_fill_dir_name = "Trebuie să dați un nume directoriului dumneavoastră";
$l_invalid_dir_path = "Repertoriul specificat nu este valid";
$l_invalid_file = "Fișier incorect";
$l_invalid_existing_file = "Repertoriul specificat nu indică niciun fișier valabil";
$l_error_dir = "Directoriul nu este gol. Verificați repertoriul si numele";

