<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Romanian                                                   //
//     - File     : incident.inc                                             //
// 2009-09-23 : Cristina Grigore                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id: incident.inc 2972 2008-07-02 09:42:54Z mehdi $ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-18T17:29:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:41:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:59:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:59:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:19:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:19:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:21:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:25:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:26:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:27:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:28:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:29:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:29:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:30:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:39:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:39:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:40:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:41:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:54:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:56:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:58:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:59:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:59:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:03:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:04:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:05:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:06:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:14:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:19:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:20:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:21:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:22:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:22:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:23:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:23:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:25:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:26:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:26:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:27:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:27:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:29:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:30:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:35:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:35:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:37:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:37:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:38:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:40:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:40:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:42:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:42:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:43:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:43:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:44:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:48:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:50:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:50:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:57:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:57:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:02:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:02:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:09:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:16:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:22:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:23:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:25:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:26:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:30:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:32:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:31:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:32:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:35:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:48+02:00 using OBMtranslation (0.4.1)

$l_date = "Dată";
$l_logger = "Receptor"; 
$l_owner = "Responsabil Tecnic";
$l_duration = "Durata totală de rezolvare";
$l_solution = "Problemă și rezolvare";
$l_client_manager = "Responsabil Client";
$l_date_before = "Dată Înainte de";
$l_date_after = "Dată După";
$l_archive_new = "Salvare";
$l_res_duration = "Durata de rezolvare";
$l_reference = "Referință";
$l_resolutiontype = "Tip de rezolvare";
$l_redhot = "Foarte Urgent";
$l_hot = "Urgent";
$l_normal = "Normal";
$l_low = "Mică";
$l_open = "Deschis";
$l_waitcall = "Apel în așteptare"; 
$l_standby = "În pauză";
$l_closed = "Închis";
$l_lastupdate = "Ultima modificare";
$l_select_contract = "Selectați un contract";
$l_insert = "Introduceți incidentul";
$l_update = "Modificați incidentul";
$l_delete = "Ștergeți incidentul"; 
$l_mail_incident_new_subject = "OBM : N. Incident";
$l_mail_incident_affected_subject = "OBM : Atribuire";
$l_mail_incident_closed_subject = "OBM : Încheiere";
$l_mail_incident_affected_content = "Ați fost asociat acestui incident";
$l_mail_incident_closed_content = "a fost închis";
$l_no_display = "Completați spațiile și apăsați butonul  <Caută > pentru a obține lista incidentelor corespunzătoare.";
$l_found = "incident(e) găsit(e).";
$l_no_found = "Niciun incident nu corespunde acestori criterii!";
$l_can_delete = "Incidentul poate fi șters";
$l_cant_delete = "Incidentul nu poate fi șters!";
$l_incident_display = "Opțiuni de vizualizare a incidentelor"; 
$l_length_label = "Câmpul Etichetă este prea lung";
$l_length_reference = "Câmpul Referință este prea lung"; 
$l_fill_contract = "Selectați un contract înainte de a valida.";
$l_j_select_contract = "Selectați un Contract!";
$l_delete_confirm = "Confirmați ștergerea incidentului?";
$l_date_after_js = "Dată După";
$l_incidentstatus_new = "Nou";
$l_incidentstatus_open = "Deschis";
$l_incidentstatus_affected = "Asociat";
$l_incidentstatus_standby = "În așteptare";
$l_incidentstatus_solved = "Rezolvat";
$l_incidentstatus_closed = "Închis";

