<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Romanian                                                   //
//     - File     : user.inc                                                 //
// 2005-03-13 Florent Goalabre                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id: resource.inc 4218 2009-05-20 09:05:40Z mehdi $ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-22T16:41:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T16:55:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T17:15:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T17:16:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T17:19:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T17:29:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T18:01:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T18:01:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T18:01:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:32:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:31:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:32:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:35:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:48+02:00 using OBMtranslation (0.4.1)

$l_desc = "Descriere";
$l_qty = "Capacitate/Cantitate";
$l_check_resourcecreate = "voci create de către acest utilizator";
$l_check_resourceupdate = "voci modificate de către acest utilizator.";
$l_no_resource = "Niciun câmp resursă în acest tabel";
$l_fill_name = "Introduceți numele înainte de a valida.";
$l_rtype = "Tip de resursă";
$l_rtype_manage = "Gestionarea tipurilor de resurse";
$l_rtype_property = "Proprietate";
$l_rtype_kind = "Tip";
$l_rtype_insert = "Creați tipul de resursă";
$l_rtype_update = "Modificați tipul de resursă";
$l_rtype_checkdelete = "Verificați sau ștergeți acest tip de resursă";
$l_ritem = "Obiecte";
$l_ritem_add = "Adăugați aceste obiecte";
$l_ritem_manage = "Gestionarea obiectelor";
$l_ritem_insert = "Creați obiectul";
$l_ritem_update = "Modificați obiectul";
$l_no_item_available = "Niciun obiect nu este disponibil pentru această resursă";
$l_confirm_delete_item = "Sunteți sigur(ă) că doriți să ștergeți acest obiect?";
$l_resource = "Resursă";
$l_resources = "Resurse";
$l_users = "Utilizatori";
$l_insert = "Introduceți această resursă";
$l_update = "Modificați resursa";
$l_checkdelete = "Verificați sau Ștergeți resursa";
$l_reset = "Preferințe preimpostate";
$l_delete = "Ștergeți resursa";
$l_add = "Adăugați aceste resurse";
$l_no_display = "Completați spațiile și apăsați butonul  <Caută > pentru a obține lista resurselor corespunzătoare.";
$l_found = "resursă(e) găsită(e).";
$l_no_found = "Nicio resursă nu corespunde criteriilor!";
$l_cant_delete = "Resursa nu poate fi ștearsă!";
$l_can_delete = "Resursa poate fi ștearsă";
$l_name_error = "Introduceți numele!";
$l_check_samename = "Aceste resurse sunt asemănătoare celei introduse ulterior!"; 
$l_exist_error = "Acest nume este deja folosit!";
$l_resource_display = "Opțiuni de vizualizare a listelor de resurse";
$l_add_resources = "Adăugați resurse";
$l_j_check_number = "Cantitatea introdusă nu este corectă.";
$l_j_create_type_first = "Creați un  tip de resursă înainte de a crea un obiect!";
$l_toggle_public_access = "Această opțiune va permite tuturor să ceară rezervarea acestei resurse. Doriți să continuați?";
$l_toggle_public_read = "Această acțiune va permite tuturor să vizualizeze această resursă. Doriți să continuați?";
$l_toggle_public_write = "Această opțiune va permite tuturor să modifice cererile de rezervare și să accepte rezervarea acesti resurse. Doriți să continuați?";
$l_toggle_public_admin = "Această acțiune va permite tuturor să modifice drepturile acestei resurse. Doriți să continuați?";

