<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Romanian                                                   //
//     - File     : time.inc                                                 //
// 1999-01-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id: time.inc 2972 2008-07-02 09:42:54Z mehdi $ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-22T10:49:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T10:57:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T11:05:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T11:13:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T11:21:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T11:23:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T11:29:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T11:44:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-22T11:50:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:02:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:09:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:16:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:22:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:23:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:25:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:26:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:30:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:32:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:31:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:32:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:35:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:51:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:51:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:51:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:51:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:51:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:53:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:55:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:55:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:55:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:56:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:56:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:56:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:57:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:57:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:57:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:58:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T09:58:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-24T10:01:31+02:00 using OBMtranslation (0.4.1)

$l_date_task = "Dată";
$l_task_del = "Ștergeți"; 
$l_delete = "Ștergeți sarcinile";
$l_length = "Durată";
$l_total = "Total";
$l_total_period = "Durata perioadei";
$l_total_spent = "Timpul folosit";
$l_total_before = "Total precedent";
$l_total_after = "Total actual";
$l_task_del="Suppr.";
$l_from = "de la ";
$l_to = "la";
$l_user = "Utilizator";
$l_see = "Consultați";
$l_valid = "Validați";
$l_unvalid = "Anulați";
$l_add = "Adăugați";
$l_update = "Modificați";
$l_fill = "completați";
$l_intern = "Intern";
$l_task = "Sarcină";
$l_label = "Etichetă";
$l_duration = "Durată";
$l_searchtime_display = "Opțiuni de vizualizare a listelor de sarcini";
$total_menu = "Meniu";
$total_tasks = "Totalul sarcinilor";
$total_companies = "Totalul firmelor";
$total_projects = "Total per proiect/afacere";
$l_pdf_settings = "Setările fișierului PDF";
$l_daysofweekshort = 
array (	'Dum',
				'Lun',
				'Mar',
				'Mie',
				'Joi',
				'Vin',
				'Sâm');
$l_projects_manager = "Confirmarea validării sarcinilor de către adminstrator:";
$l_found_task = "Vizualizați sarcinile realizate și indicate pentru săptămâna în curs:";
$l_found = "Sarcini găsite.";
$l_no_found = "Nicio sarcină pentru acest utilizator!";
$l_fill_addtask = "Indicați sarcinile realizate pentru săptămâna în curs.";
$l_task_list = "Lista sarcinilor săptămânii";
$l_admin_valid = "Secțiune de validare a administratorului";
$l_admin_empty = "Nu există informații pentru această lună";
$l_proj_stats = "Participare la proiectele în curs";
$l_no_proj_stats = "Acestă(Aceste) persoană(e) nu participă la niciun proiect";
$l_tt_stats = "Repatizarea timpului de lucru pe tipuri de sarcini";
$l_no_tt_stats = "Această(Aceste) persoană(e) nu folosește(folosesc) gestionarea timpului";
$l_j_select_day = "Selectați o zi.";
$l_j_select_tasktype = "Selectați o categorie";
$l_j_select_project = "Selectați un proiect pentru o sarcină facturată!";
$l_j_select_projecttask = "Selectați o sarcină de proiect pentru o sarcină facturată";
$l_delete_confirm = "Confirmați ștergerea acestor sarcini?";
$l_pdf_no_project_selected = "Selectați cel puțin un proiect";
$l_pdf_bad_date = "Dată incorectă sau format invalid.";
$l_pdf_com_date_format = "d/m/Y";
$l_pdf_title = "Numele activității";
$l_pdf_date = "Document creat pe :";
$l_pdf_date_format = "d/m/Y H:i";
$l_pdf_user = "Colaborator : ";
$l_pdf_visa_user = "Colaborator Visa ";
$l_pdf_visa_client = "Client Visa ";
$l_pdf_visa_company = "Responsabil Visa";
$l_pdf_comments = "Comentarii :";
$l_pdf_projects = "Proiecte :";

