<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Romanian                                                   //
//     - File     : tools.inc                                                //
// 2002-09-26 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id: tools.inc 4521 2009-07-01 13:03:44Z mehdi $
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-18T11:38:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T11:42:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:02:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:03:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:11:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:14:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:18:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:20:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:20:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:22:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:31:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T12:34:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:12:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:16:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:19:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:26:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:26:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:30:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:33:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:41:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:44:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:50:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T14:51:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:13:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:23:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:26:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:38:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:47:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:47:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T15:55:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:03:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:35:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:41:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:44:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T16:57:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:18:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:27:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:29:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:41:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:59:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-18T17:59:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:42:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:42:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:43:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:44:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:45:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:48:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:48:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:50:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:51:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:51:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:54:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:54:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:55:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:57:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:58:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:58:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:59:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T09:59:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:00:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:02:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:04:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:05:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:06:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:08:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:11:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:12:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:13:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:14:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:15:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:15:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:17:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:18:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:19:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:19:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:21:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:24:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:25:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:26:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:27:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:28:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:29:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:29:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:30:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:32:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:39:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:39:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:40:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:41:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:54:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:56:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:58:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:59:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T10:59:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:03:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:04:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:05:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:06:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:14:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:19:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:20:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:21:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:22:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:22:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:23:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:23:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:25:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:26:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:26:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:27:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:27:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:29:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:30:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:35:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:35:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:37:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:37:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:38:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:40:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:40:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:42:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:42:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:43:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:43:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:44:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:48:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:50:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:50:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:57:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T11:57:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:02:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:02:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:05:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:09:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:16:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:18:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:19:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:22:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:23:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:25:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:26:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:30:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T12:32:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:31:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:32:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:35:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-23T13:37:48+02:00 using OBMtranslation (0.4.1)

$l_tools = "Instrumente de administrare";
$l_upd = "Actualizarea configurării sistemului";
$l_upd_user = "Actualizări";
$l_upd_domain = "Actualizările domeniului"; 
$l_upd_delegation = "Actualizările delegației mele";
$l_upd_running = "Sistemul este în curs de configurare...";
$l_upd_already_running = "Imposibil, sistemul este deja în curs de configurare...";
$l_upd_not_needed = "Configurarea sistemului este <b>actualizată</b>";
$l_upd_need_domain_update = "Domeniul a fost modificat! Este necesar să validați configurarea domenului"; 
$l_upd_needed = "Configurarea sistemului a fost modificată";
$l_upd_run = "Înregistrarea noii configurări a sistemului";
$l_upd_cancel = "Anulați modificările efectuate";
$l_upd_ok = "Configurarea sistemului a fost înregistrată";
$l_upd_error = "Configurarea sistemului a eșuat!";
$l_upd_cancel_ok = "Anularea actualizării sistemului a fost înregistrată";
$l_upd_cancel_error = "Anularea actualizării sistemului a eșuat!";
$l_progress = "Progres de execuție";
$l_created = "Create";
$l_updated = "Modificate";
$l_deleted = "Șters";
$l_links = "Asocieri";
$l_unspecified = "nespecificat";
$l_js_ask_confirm = "Sunteți sigur?";
$l_halt = "Oprirea sistemului";
$l_halt_aliamin = "Oprire sistem";
$l_show_details = "Vezi detaliile";
$l_js_created_user_confirm = "Acestă opțiune va șterge utilizatorul din baza de date, toate informațiile vor fi pierdute definitiv, doriți să continuați?    ";
$l_js_created_host_confirm = "Această acțiune va șterge Host-ul din baza de date, toate informațiile vor fi pierdute definitiv, doriți să continuați?"; 
$l_js_created_group_confirm = "Această acțiune va șterge grupul di baza de date, toate informațiile vor fi pierdute definitiv, doriți să continuați?"; 
$l_js_created_mailshare_confirm = "Această opțiune va șterge mailshare-ul din baza de date, toate informațiile vor fi pierdute definitiv, doriți să continuați?"; 
$l_js_updated_user_confirm = "Această opțiune va șterge definitiv toate modificările efectuate asupra utilizatorului după ultima actualizare a sistemului, doriți să continuați?";
$l_js_updated_host_confirm = "Această opțiune va șterge definitiv toate modificările Host-ului, efectuate după ultima actualizare a sistemului, doriți să continuați?";
$l_js_updated_group_confirm = "Această opțiune va șterge definitiv toate modificările efectuate asupra grupului după ultima actualizare a sistemului, doriți să continuați?";
$l_js_updated_mailshare_confirm = "Această opțiune va anula definitiv toate modificările efectuate asupra mailshare-ului după ultima actualizare a sistemului, doriți să continuați?";
$l_js_deleted_user_confirm = "Această opțiune va recrea utilizatorul utilizând informațiile ultimei actualizări a sistemului, toate informațiile care nu aparțin sistemului nu vor putea fi recuperate, doriți să continuați? "; 
$l_js_deleted_host_confirm = "Această acțiune va recrea utilizatorul utilizând informațiile ultimei actualizări a sistemului, toate informațiile care nu aparțin sistemului nu vor putea fi recuperate, doriți să continuați?"; 
$l_js_deleted_group_confirm = "Acestă opțiune va recrea utilizatorul  folosind datele ultimei actualizări a sistemului, toate informațiile care nu aparțin sistemului nu vor putea fi recuperate, doriți să continuați? ";
$l_js_deleted_mailshare_confirm = "Această acțiune va recrea utilizatorul utilizând informațiile ultimei actualizări a sistemului, toate informațiile care nu aparțin sistemului nu vor putea fi recuperate, doriți să continuați?"; 
$l_cant_undo_created_user = "Eroare înregistrată in timpul anulării creării utilizatorului";
$l_cant_undo_created_mailshare = "Eroare  înregistrată în timpul anulării creării mailshare-ului";
$l_cant_undo_created_host = "Eroare înregistrată în timpul anulării creări Hostului"; 
$l_cant_undo_created_group = "Eroare înregistrată în timpul creării grupului";
$l_cant_undo_updated_user = "Eroare înregistrată în timpul actualizării utilizatorului";
$l_cant_undo_updated_mailshare = "Eroare înregistrată în timpul anulării actualizării mailshare-ului";
$l_cant_undo_updated_host = "Eroare înregistrată in timpul anulării actualizării Host-ului";
$l_cant_undo_updated_group = "Eroare înregistrată in timpul anulării actualizării grupului";
$l_cant_undo_deleted_user = "Eroare înregistrată în timpul ștergerii utilizatorului";
$l_cant_undo_deleted_mailshare = "Eroare înregistrată în timpul anulării ștergerii mailshare-ului"; 
$l_cant_undo_deleted_host = "Eroare înregistrată in timpul anulării ștergerii Host-ului";
$l_cant_undo_deleted_group = "Eroare înregistrată în timpul anulării ștergerii grupului";
$l_undo_success = "Anularea operațiunii a avut succes";

