=head1 NOM

OBM::Parameters::common - Déclaration de différentes valeurs utiles par
l'ensemble de l'automate.

=head1 DEPENDANCES

 require Exporter;
 use Config::IniFiles;
 use FindBin qw($Bin);

=head1 DESCRIPTION

    use OBM::Parameters::common

Ce paquet déclare un ensemble de valeurs (constantes ou variables) utilisées par
l'ensemble des scripts de l'automate.

=cut
