<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - File : admin_ref.inc                                                //
//     - Desc : English language for Admin Referential                       //
// 2003-12-05 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T11:11:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:27:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:28:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:30:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:35:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:55:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:56:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:57:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:01:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:05:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:07:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:07:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:07:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:08:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:10:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:19:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:21:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:25:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T12:31:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:09:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:13:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:13:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:16:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:16:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:17:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:25:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:32:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:32:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:45:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:49:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:49:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:54:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:57:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:59:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:02:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:03:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:03:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:04:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:06:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:08:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:11:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:19:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:22:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:23:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:23:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:24:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:25:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:26:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:26:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:29:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:30:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:31:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:32:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:33:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:34:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:37:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:38:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:42:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:43:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:43:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:45:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:45:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:47:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:53:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:00:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:01:06+02:00 using OBMtranslation (0.4.1)

$l_dsrc_manage = "Data Sources management";
$l_dsrc_exist = "Existing Data Sources";
$l_dsrc_new = "New Data Source";
$l_dsrc_no = "No Data source defined";
$l_dsrc_update = "Update Data Source";
$l_dsrc_checkdelete = "Check or Delete Data Source";
$l_dsrc_delete = "Delete Data Source";
$l_dsrc_insert = "Insert Data Source";
$l_dsrc_delete_ok = "The Data Source has been deleted successfully.";
$l_dsrc_delete_error = "The deletion of the Data Source has failed !";
$l_dsrc_insert_ok = "The Data Source has been inserted successfully.";
$l_dsrc_insert_error = "The insertion of the Data Source has failed !";
$l_dsrc_update_ok = "The Data Source has been updated successfully";
$l_dsrc_update_error = "The update of the Data Source has failed !";
$l_dsrc_link_company = "These companies reference this Data Source";
$l_dsrc_link_company_no = "No companies referenced by this Data Source";
$l_dsrc_link_contact = "These contacts reference this Data Source";
$l_dsrc_link_contact_no = "No contacts referenced by this Data Source";
$l_dsrc_cant_delete = "The Data Source cannot be deleted !"; 
$l_dsrc_can_delete = "The Data Source can be deleted.";
$l_j_dsrc_delete = "You have to select a data source to check or delete!";
$l_j_dsrc_update = "You have to select a data source and enter a new name to update it !";
$l_j_dsrc_create = "You have to enter a new data source name to create it !";
$l_ctry_manage = "Countries management";
$l_ctry_exist = "Existing Countries";
$l_ctry_new = "New Country";
$l_ctry_no = "No Country defined";
$l_ctry_update = "Update Country";
$l_ctry_checkdelete = "Check or Delete Country";
$l_ctry_delete = "Delete Country";
$l_ctry_insert = "Insert Country";
$l_ctry_delete_ok = "The Country has been deleted successfully.";
$l_ctry_delete_error = "The deletion of the Country has failed !";
$l_ctry_insert_ok = "The Country has been inserted successfully.";
$l_ctry_insert_error = "The insertion of the Country has failed !";
$l_ctry_update_ok = "The Country has been updated successfully";
$l_ctry_update_error = "The update of the Country has failed !";
$l_ctry_link_company = "These companies reference this Country";
$l_ctry_link_company_no = "No companies referenced by this Country";
$l_ctry_link_contact = "These contacts reference this Country";
$l_ctry_link_contact_no = "No contacts referenced by this Country";
$l_ctry_cant_delete = "The Country cannot be deleted !";
$l_ctry_can_delete = "The Country can be deleted.";
$l_j_ctry_delete = "You have to select a country to check or delete!";
$l_j_ctry_update = "You have to select a country and enter a new name to update it !";
$l_j_ctry_create = "You have to enter a new country name to create it !";
$l_iso_3166 = "Iso Code 3166";
$l_tt_manage = "Task Type management";
$l_tt_exist = "Existing Task Types";
$l_tt_new = "New";
$l_tt_no = "No Task Type defined";
$l_tt_update = "Update Task Type";
$l_tt_checkdelete = "Check or Delete Task Type";
$l_tt_delete = "Delete Task Type";
$l_tt_insert = "Insert Task Type";
$l_tt_delete_ok = "The Task Type has been deleted successfully.";
$l_tt_delete_error = "The deletion of the Task Type has failed !";
$l_tt_insert_ok = "The Task Type has been inserted successfully.";
$l_tt_insert_error = "The insertion of the Task Type has failed !";
$l_tt_update_ok = "The Task Type has been updated successfully";
$l_tt_update_error = "The update of the Task Type has failed !";
$l_tt_link_deal = "These deals reference this Task Type";
$l_tt_link_deal_no = "No deal referenced by this Task Type";
$l_tt_link_project = "These projects reference this Task Type";
$l_tt_link_project_no = "No project referenced by this Task Type";
$l_tt_link_time = "The Task Type is used in time management";
$l_tt_link_time_no = "The Task Type is not used in time management";
$l_tt_cant_delete = "The Task Type cannot be deleted !"; 
$l_tt_can_delete = "The Task Type can be deleted.";
$l_j_tt_delete = "You have to select a task type to check or delete!";
$l_j_tt_update = "You have to select a task type and enter a new name to update it !";
$l_j_tt_create = "You have to enter a new task type name to create it !";

