<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : admin.inc                                                //
// 2001-12-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id //
///////////////////////////////////////////////////////////////////////////////

// labels
$l_check = "Checking";
$l_version = "OBM version";
$l_database_server = "Database Engine";
$l_database = "Database";
$l_session_stats = "Sessions Statistics";
$l_date = "Date";
$l_user_session = " Entries in ActiveUserObm";
$l_active_user = "Active users";
$l_login_date = "Login date";
$l_last_acces = "Last Acces";
$l_nb_connec = "Hits number";
$l_last_page = "Last page";
$l_user_ip = "IP";
$l_user_pref = "Users preferences";
$l_global_pref = "Global preferences";
$l_lifetime = "User session lifetime (seconds)";
$l_session_lifetime = "User session lifetime (max idle time before a user is deconnected) in seconds";
$l_session_cookie = "Do session cookie (cookie expires when the client close the browser). This should avoid problem with date differences between client and server. Recommended.";

// Titles
$l_admin = "Admin";
$l_admin_lang = "Admin Lang";

// Actions
$l_execute = "Execute action";
$l_help = "Help";

// Messages (+ javascript)
$l_fill_lifetime = "You have to fill the lifetime before submitting.";
$l_j_check_lifetime = "The lifetime is not valid.";
$l_update_ok = "Preferences updated successfully";
$l_update_error = "Preferences update failed !";
