<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                   //
//     - File     : backup.inc                                               //
// 2005-08-22 Aliacom - Pierre Baudracco                                     //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

$l_bytes = "bytes";
$l_no_display = "Fill in the search fields and press < Find > to retrieve the backup";
$l_backup_found = "backup found";
$l_no_found = "No backup matching the query has been found!"; 
$l_restore_ok = "The backup has been restored successfully.";
$l_restore_error = "The backup restoration has failed !";
$l_err_backup_no_mail = "You can't backup this entity, because it doesn't have mail enabled.";
$l_err_host = "You can't backup this entity, because it doesn't have mail host defined.";
$l_create_backup_error = "The backup file creation has failed !";
$l_delete_file_error = "The backup file deletion has failed !";
$l_err_backup_name = "The backup file name is not valid !";
$l_err_backup_file = "The backup file cannot be read !"; 
$l_err_backup_dir_not_exist = "The backup directory does not exist !";
$l_err_backup_dir_not_writable = "The backup directory is not writable !";
$l_can_delete = "The backup can be deleted.";
$l_cant_delete = "The backup cannot be deleted !"; 
$l_can_create = "The backup can be created.";
$l_cant_create = "The backup cannot be created !"; 
$l_err_unknown_db = "Unknown database Type !";
$l_delete = "Delete backup";
$l_insert = "Create backup";
$l_restore = "Restore";

$l_restore_mailbox = "Mailbox";
$l_restore_calendar = "Calendar";
$l_restore_contact = "Contacts";
$l_restore_all = "Everything";
$l_backup_complete = "Backup completed successfully.";
$l_restore_complete = "Restoration completed successfully.";
$l_no_backup_available = "No backup available !";
$l_err_cant_backup = "An error happend and the backup didn't proceed !";
$l_err_cant_restore = "An error occured and the restoration failed !";
$l_err_cant_get_availablebackup = "Unable to get the list of available backups !";
$l_cant_backup_pending_modifications = "Unable to do backup. The entity have pending modifications, please use system configuration tools to validate it";
$l_err_obm_satellite_usersystem = "Connexion to obm-satellite fail : Can't get the system user to use.";

$l_push_backup_ftp_failed = "The backup hasn't been added on the FTP server";
$l_retrieve_from_ftp = "Retrieve backups";
$l_retrieve_from_ftp_success = "All available backups on the FTP server has been retrieved";
$l_no_backup_ftp_specified = "No FTP server specified for the domain.";
$l_retrieve_from_backup_ftp = "Click on the button bellow to retrieve all available backups for '%s', available on the domain FTP server.";
$l_unable_to_retrieve_backup = "Unable to retrieve archived backups from the FTP server";

