<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : backup.inc                                               //
// 2005-08-22 Aliacom - Pierre Baudracco                                     //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

// Labels et textes
$l_bytes = "bytes";

// Message
$l_no_display = "Fill the search fields and press < Find > to retrieve the backup";
$l_found = "backup found";
$l_no_found = "No backup found matching the query !";

$l_restore_ok = "The backup has been restored successfully.";
$l_restore_error = "The backup restoration has failed !";

$l_create_backup_error = "The backup file creation has failed !";
$l_delete_file_error = "The backup file deletion has failed !";
$l_err_backup_name = "The backup file name is not valid !";
$l_err_backup_file = "The backup file can not be read !";
$l_err_backup_dir_not_exist = "The backup directory does not exist !";
$l_err_backup_dir_not_writable = "The backup directory is not writable !";
$l_can_delete = "The backup can be deleted.";
$l_cant_delete = "The backup can't be deleted !";
$l_can_create = "The backup can be created.";
$l_cant_create = "The backup can't be created !";
$l_err_unknown_db = "Unknown database Type !";

// Actions
$l_delete = "Delete the backup";
$l_insert = "Create the backup";
$l_restore = "Restore";
