<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : company.inc                                              //
// 1999-01-25 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-09T15:20:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:02:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:20:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:49:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:50:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:58:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:01:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:04:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:12:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:14:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:23:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:34:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:43:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:44:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T16:32:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:53:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:00:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:01:06+02:00 using OBMtranslation (0.4.1)

$l_number = "Number";
$l_company_name = "Company Name";
$l_type = "Type";
$l_activity = "Activity";
$l_nafcode = "NAF Code";
$l_market = "Marketing manager";
$l_web = "Web";
$l_email = "E-Mail";
$l_coord = "Details";
$l_vat = "EU VAT";
$l_siret = "SIRET";
$l_contact_new = "New Contact";
$l_deal_new = "New Deal";
$l_project_new = "New Projet";
$l_contract_new = "New Contract";
$l_internal = "Internal";
$l_naf_manage = "NAF Code Management";
$l_naf_exist = "Existing NAF codes";
$l_naf_new = "New NAF Code";
$l_naf_label = "Label";
$l_naf_code = "Code";
$l_naf_istitle = "It is a title"; 
$l_add = "Add";
$l_insert = "Insert Company";
$l_update = "Update Company";
$l_checkdelete = "Check or Delete Company";
$l_delete = "Delete Company";
$l_naf_update = "Update NAF Code";
$l_naf_checkdelete = "Check or Delete NAF Code";
$l_naf_delete = "Delete NAF Code";
$l_naf_insert = "Insert NAF Code";
$l_select_company = "Select Company";
$l_err_act_empty = "You must fill in the company activity !";
$l_cat_no = "No categories defined";
$l_no_display = "Fill in the search fields and press < Find > to retrieve the companies";
$l_found = "companies found.";
$l_no_found = "No company matching the query has been found!";
$l_check_samecompany = "These companies seem similar to this new entry !";
$l_link_contact = "The company has contacts";
$l_link_contact_no = "The company has no contacts";
$l_link_deal = "The company is involved in some deals";
$l_link_deal_no = "The company is not involved in any deal"; 
$l_link_contract = "The company is involved in some contracts";
$l_link_contract_no = "The company is not involved in any contract"; 
$l_link_project = "The company is involved in some projects";
$l_link_project_no = "The company is not involved in any projects"; 
$l_link_invoice = "The company is involved in some invoices";
$l_link_invoice_no = "The company is not involved in any invoices"; 
$l_cant_delete = "The company cannot be deleted !";
$l_can_delete = "The company can be deleted.";
$l_naf_no = "No NAF Code defined";
$l_naf_link_company = "These companies are referenced by the NAF code";
$l_naf_link_company_no = "No company linked to NAF code";
$l_naf_cant_delete = "The NAF code cannot be deleted !";
$l_naf_can_delete = "NAF Code can be deleted.";
$l_delete_confirm = "Confirm company deletion  ?"; 
$l_fill_name = "You have to enter the Name before submitting.";
$l_j_check_zip = "The zip code is not valid.";
$l_j_check_phone = "The phone number is not valid.";
$l_j_check_fax = "The fax number is not valid.";
$l_j_check_email = "The email address is not valid. Verify domain";
$l_j_check_web = "The web address is not valid.";
$l_j_select_company = "You have to select a company !";
$l_j_naf_create = "You have to enter a NAF code to create it !";
$l_company_display = "Display options for companies lists";
$l_phone_labels = array ('WORK_VOICE' => 'Phone', 'CELL_VOICE' => 'Mobile phone', 'WORK_FAX' => 'Fax', 'OTHER' => 'Other phone');
$l_email_labels = array ('INTERNET' => 'email', 'OTHER' => 'Other');
$l_address_labels = array ('HQ' => 'Headquarters', 'OTHER' => 'Other');
$l_website_labels = array ('URL' => 'Website', 'OTHER' => 'Other');
$l_j_naf_update = "You have to select a NAF code and to update before validating.";
$l_j_cat_deep = "The categories cannot have more than three depth levels";
$l_j_naf_delete = "Select a NAF code to validate or to delete !";
$l_comment = "Comment";

