<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : contact.inc                                              //
// 1999-01-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_lastname = "Lastname";
$l_firstname = "Firstname";
$l_kind = "Kind";
$l_market = "Person in charge";
$l_function = "Function";
$l_title = "Job Title";
$l_minihphone = "(Home)";
$l_minimphone = "(Mobile)";
$l_email = "E-Mail";
$l_email_other = "Other E-Mail";
$l_mailing_ok = "Mailing enabled";
$l_mailing_ok_only = "Mailing enabled only";
$l_newsletter = "Newsletter";
$l_news = "News";
$l_code = "Code";
$l_letter = "Letter Head";
$l_comment1 = "Comment";
$l_comment2 = "Comment 2";
$l_comment3 = "Comment 3";
$l_date_after = "Inscription date after";
$l_date_before = "Inscription date before";
$l_mailing_ok_first = "Mail.";

// Labels and texts
$l_contact_name = "Contact Name";
$l_from_company = "From Company";
$l_telother = "Other tel";
$l_contact_select_company = "Select the company for the contact.";
$l_kind_manage = "Contact Kind Management";
$l_kind_exist = "Existing Kinds";
$l_kind_no = "No kind defined";
$l_kind_new = "New Kind";
$l_header = "Header";
$l_subscription = "Subscriptions";
$l_subscription_list = "Subscriptions";
$l_subscription_new= "New subscription";

// Actions
$l_insert = "Insert the Contact";
$l_update = "Update the Contact";
$l_checkdelete = "Check or Delete the Contact";
$l_delete = "Delete the Contact";
$l_kind_update = "Update Kind";
$l_kind_checkdelete = "Check or Delete Kind";
$l_kind_delete = "Delete Kind";
$l_kind_insert = "Insert Kind";
$l_add_comment1 = "Add a comment";
$l_upd_comment1 = "Update comment";
$l_add_comment2 = "Add a comment 2";
$l_upd_comment2 = "Update comment 2";
$l_add_comment3 = "Add a comment 3";
$l_upd_comment3 = "Update comment 3";

// Messages
$l_check_samecontact = "These contacts seem similar to this new entry !";
$l_link_deal = "The contact is involved in some deals";
$l_link_deal_no = "The contact isn't involved in any deal";
$l_link_contract = "The contact is involved in some contracts";
$l_link_contract_no = "The contact isn't involved in any contract";
$l_link_list = "The contact is registered in some lists";
$l_link_list_no = "The contact isn't registered in any list";
$l_link_publication = "The contact has some subscriptions";
$l_link_publication_no = "The contact hasn't any subscription";
$l_cant_delete = "The contact can't be deleted !";
$l_can_delete = "The contact can be deleted.";
$l_no_display = "Fill the search fields and press < Find > to retrieve the contacts";
$l_found = "contacts found.";
$l_no_found = "No contact found matching the query !";
// Kind Messages
$l_kind_link_company = "These companies are referenced as";
$l_kind_link_company_no = "No company referenced as";
$l_kind_cant_delete = "The Kind can't be deleted !";
$l_kind_can_delete = "The Kind can be deleted.";

// JavaScript Messages (specials charcaters must be escaped whith \ -> \\)
$l_fill_lastname = "You have to fill the Lastname before submitting.";
$l_fill_company = "You have to select a company before submitting.";
$l_fill_phone = "You have to fill the Phone before submitting.";
$l_delete_confirm = "Really delete the contact ?";
$l_j_select_company =  "You must select a company !";
$l_j_check_phone = "The phone number is not valid.";
$l_j_check_hphone = "The personal phone number is not valid.";
$l_j_check_mphone = "The mobile phone number is not valid.";
$l_j_check_fax = "The fax number is not valid.";
$l_j_check_email = "The email adress is not valid.";
// JavaScript messages - Kind
$l_j_kind_delete = "You have to select a kind to check or delete it !";
$l_j_kind_update = "You have to select a kind and enter a new name to update it !";
$l_j_kind_create = "You have to fill all kind informations kind to create it !";
// For the display parameters modification screen
$l_contact_display = "Display options for contacts list"; 
//External Field
$l_timecreate = "Creation";
$l_timeupdate = "Last update";
$l_publication_title = "Title";
$l_renewal = "Automatic renewal";
$l_recept = "Reception mode";
$l_quantity = "Quantity";
$l_no_found_subscription = "No subscription found for this contact !";
