<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : contact.inc                                              //
// 1999-01-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_lastname = "Lastname";
$l_firstname = "Firstname";
$l_kind = "Kind";
$l_market = "Person in charge";
$l_function = "Function";
$l_title = "Job Title";
$l_service = "Service";
$l_minihphone = "(Home)";
$l_minimphone = "(Mobile)";
$l_email = "E-Mail";
$l_email_other = "Other E-Mail";
$l_mailing_ok = "Mailing enabled";
$l_coord = "Details";
$l_code = "Code";
$l_letter = "Letter Head";
$l_comment2 = "Comment 2";
$l_comment3 = "Comment 3";
$l_category3 = "category 3";
$l_category4 = "category 4";
$l_category5 = "category 5";

// Labels and texts
$l_contact_name = "Contact Name";
$l_from_company = "From Company";
$l_telother = "Other tel";
$l_contact_select_company = "Select the company for the contact.";
$l_func_manage = "Contact Function Management";
$l_func_exist = "Existing Functions";
$l_func_no = "No functions defined";
$l_func_new = "New Function";
$l_kind_manage = "Contact Kind Management";
$l_kind_exist = "Existing Kinds";
$l_kind_no = "No kind defined";
$l_kind_new = "New Kind";
$l_header = "Header";
$l_subscription = "Subscriptions";
$l_subscription_list = "Subscriptions";
$l_subscription_new= "New subscription";

// Actions
$l_insert = "Insert the Contact";
$l_update = "Update the Contact";
$l_checkdelete = "Check or Delete the Contact";
$l_delete = "Delete the Contact";
$l_func_update = "Update Function";
$l_func_checkdelete = "Check or Delete Function";
$l_func_delete = "Delete Function";
$l_func_insert = "Insert Function";
$l_kind_update = "Update Kind";
$l_kind_checkdelete = "Check or Delete Kind";
$l_kind_delete = "Delete Kind";
$l_kind_insert = "Insert Kind";
$l_add_cats1 = "Add these categories 1";
$l_add_cats2 = "Add these categories 2";
$l_add_comment2 = "Add a comment 2";
$l_upd_comment2 = "Update comment 2";
$l_add_comment3 = "Add a comment 3";
$l_upd_comment3 = "Update comment 3";

// Messages
$l_check_samecontact = "These contacts seem similar to this new entry !";
$l_link_deal = "The contact is involved in some deals";
$l_link_deal_no = "The contact isn't involved in any deal";
$l_link_contract = "The contact is involved in some contracts";
$l_link_contract_no = "The contact isn't involved in any contract";
$l_link_list = "The contact is registered in some lists";
$l_link_list_no = "The contact isn't registered in any list";
$l_link_publication = "The contact has some subscriptions";
$l_link_publication_no = "The contact hasn't any subscription";
$l_cant_delete = "The contact can't be deleted !";
$l_can_delete = "The contact can be deleted.";
$l_no_display = "Fill the search fields and press < Find > to retrieve the contacts";
$l_found = "contacts found.";
$l_no_found = "No contact found matching the query !";
$l_delete_ok = "The contact has been deleted successfully.";
$l_delete_error = "The deletion of the contact has failed !";
$l_insert_ok = "The contact has been inserted successfully.";
$l_insert_error = "The insertion of the contact has failed !";
$l_update_ok = "The contact has been updated successfully.";
$l_update_error = "The update of the contact has failed !";
// Function Messages
$l_func_insert_ok = "The function has been inserted successfully.";
$l_func_insert_error = "The insertion of the function has failed !";
$l_func_delete_ok = "The function has been deleted successfully.";
$l_func_delete_error = "The deletion of the function has failed !";
$l_func_update_ok = "The function has been updated successfully.";
$l_func_update_error = "The update of the function has failed !";
$l_func_link_contact = "These contacts are referenced as";
$l_func_link_contact_no = "No contact referenced as";
$l_func_cant_delete = "The Function can't be deleted !";
$l_func_can_delete = "The Function can be deleted.";
// Kind Messages
$l_kind_insert_ok = "The kind has been inserted successfully.";
$l_kind_insert_error = "The insertion of the kind has failed !";
$l_kind_delete_ok = "The kind has been deleted successfully.";
$l_kind_delete_error = "The deletion of the kind has failed !";
$l_kind_update_ok = "The kind has been updated successfully.";
$l_kind_update_error = "The update of the kind has failed !";
$l_kind_link_company = "These companies are referenced as";
$l_kind_link_company_no = "No company referenced as";
$l_kind_cant_delete = "The Kind can't be deleted !";
$l_kind_can_delete = "The Kind can be deleted.";

// JavaScript Messages (specials charcaters must be escaped whith \ -> \\)
$l_fill_lastname = "You have to fill the Lastname before submitting.";
$l_fill_company = "You have to select a company before submitting.";
$l_fill_phone = "You have to fill the Phone before submitting.";
$l_delete_confirm = "Really delete the contact ?";
$l_j_select_company =  "You must select a company !";
$l_j_check_phone = "The phone number is not valid.";
$l_j_check_hphone = "The personal phone number is not valid.";
$l_j_check_mphone = "The mobile phone number is not valid.";
$l_j_check_fax = "The fax number is not valid.";
$l_j_check_email = "The email adress is not valid.";
// JavaScript messages - Function
$l_j_func_delete = "You have to select a function to check or delete it !";
$l_j_func_update = "You have to select a function and enter a new name to update it !";
$l_j_func_create = "You have to enter a new function label to create it !";
// JavaScript messages - Kind
$l_j_kind_delete = "You have to select a kind to check or delete it !";
$l_j_kind_update = "You have to select a kind and enter a new name to update it !";
$l_j_kind_create = "You have to fill all kind informations kind to create it !";
// For the display parameters modification screen
$l_contact_display = "Display options for contacts list"; 
//External Field
$l_timecreate = "Creation";
$l_timeupdate = "Last update";
$l_publication_title = "Title";
$l_year = "Year";
$l_renewal = "Automatic renewal";
$l_recept = "Reception mode";
$l_quantity = "Quantity";
$l_no_found_subscription = "No subscription found for this contact !";
