<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : control.inc                                              //
// 2009-06-16 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id:$
///////////////////////////////////////////////////////////////////////////////

$l_system = "System";
$l_network = "Network";
$l_mail_domain = "Mail domain";
$l_mail_alias = "Mail Domain Alias";
$l_mail_mode = "Mail Mode";
$l_relay = "Relay";
$l_server = "Server";
$l_global_stats = "Global stats";
$l_nb_user = "# users";
$l_nb_group = "# groups";
$l_nb_mailshare = "# mail shares";
$l_disk_space = "Disk space usage";
$l_mail_stats = "Mail Stats";
$l_mail_sent = "Mails sent";
$l_mail_recv = "Mails received";
$l_mail_kb_sent = "Mail sent size (kb)";
$l_mail_kb_recv = "Mail received size (kb)";
$l_maintenance = "Updates";
$l_sys_update = "Data update waiting";
