<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English for global                                       //
//     - File     : global.inc                                               //
// 2001-12-27 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id //
///////////////////////////////////////////////////////////////////////////////

// Common actions
$l_find = "Find";
$l_back = "Back";
$l_cancel = "Cancel";
$l_close = "Close the window";
$l_validate = "Validate";

// Common messages
$l_all = "All";
$l_all_f = "All";
$l_none = "---";
$l_archive = "Archive";
$l_invalid_data = "Invalid Data";

// Mysql Date format
$l_datetime_format = "%m-%d-%Y %H:%i:%s"; // Complete Date + Time
$l_date_format = "%m-%d-%Y"; // Date only 
$l_date_text_format = "%a %d %M"; // Date only (text mode eg : Mon 10 Jul)
$l_time_format = "%H:%i:%s"; // Time only

// OBM_DISPLAY
$l_field = "Field";
$l_displayed = "Displayed";
$l_order = "Display order";
$l_move = "Move";
$l_mandatory = "Display of this field is mandatory";
$l_display_no = "Stop displaying this field";
$l_display_yes = "Display this field";
$l_down = "Move the field down one row";
$l_up = "Move the field up one row";

// OBM_DISPLAY help screen
$l_help = "Help";
$l_help_display_yes = "The field is displayed. Click on this button if you want the field not to be displayed";
$l_help_display_no = "The field is not displayed. Click on this button if you want the field to be displayed";
$l_help_mandatory = "This field is mandatory";
$l_help_down  = "Move the field down";
$l_help_up = "Move the field up";


//used by many modules
// days and months
$l_january="January";
$l_february="February";
$l_march="March";
$l_april="April";
$l_may="May";
$l_june="June";
$l_july="July";
$l_august="August";
$l_september="September";
$l_october="October";
$l_november="November";
$l_december="December";

$l_short_january="Jan";
$l_short_february="Feb";
$l_short_march="Mar";
$l_short_april="Apr";
$l_short_may="May";
$l_short_june="Jun";
$l_short_july="Jul";
$l_short_august="Aou";
$l_short_september="Sep";
$l_short_october="Oct";
$l_short_november="Nov";
$l_short_december="Dec";
$l_invalid_perm = "Invalid permissions.";

////////////////////////////////////////////////////////
////// Theme headers lang files ////////////////////////
////////////////////////////////////////////////////////
$l_header_com    = "COMMERCIAL";
$l_header_prod   = "PRODUCTION";
$l_header_compta = "ACCOUTANCY";
$l_header_users  = "USERS";
$l_header_admins = "ADMINISTRATION";

$l_header_settings = "Settings";
$l_header_company = "Companies";
$l_header_contact = "Contacts";
$l_header_contract = "Contracts";
$l_header_incident = "Incidents";
$l_header_deal = "Deals";
$l_header_list = "Lists";
$l_header_user = "Users";
$l_header_admin = "Administration";
$l_header_admin_lang = "Lang";
$l_header_admin_data = "Data";
$l_header_admin_pref = "Prefs";
$l_header_admin_code = "Code";
$l_header_computer = "Computers";
$l_header_account = "Accounts";
$l_header_invoice = "Invoices";
$l_header_payment = "Payments";
$l_header_agenda = "Calendar";

//TIME
$l_header_time = "Time management" ;
$l_header_stats = "Statistics";
$l_header_month = "Monthly view";


$l_header_title_computer = "COMPUTER" ;
$l_header_title_settings = "SETTINGS";
$l_header_title_company = "COMPANY";
$l_header_title_contact = "CONTACT";
$l_header_title_contract = "CONTRACT";
$l_header_title_incident = "INCIDENT";
$l_header_title_deal = "DEAL";
$l_header_title_list = "LIST" ; 
$l_header_title_user = "USER";
$l_header_title_admin = "ADMINISTRATION";
$l_header_title_account = "ACCOUNT";
$l_header_title_invoice = "INVOICE";
$l_header_title_payment = "PAYMENT";
$l_header_title_agenda = "CALENDAR";

$l_header_new_f = "New";
$l_header_new = "New";
$l_header_find = "Find";
$l_header_display = "Display";
$l_header_export = "Export";
$l_header_modify = "Modify";
$l_header_delete = "Delete";

$l_header_new_parent = "New ParentDeal";
$l_header_find_parent = "Find ParentDeal";

$l_header_add_contact = "Add contact";

$l_header_reconcile = "Reconcile";
$l_header_compute_balance = "Compute balance";
$l_header_dupplicate = "Dupplicate";

$l_header_reset = "Défault Préferences";

$l_header_amp	= "Show amp";
$l_header_clear_sess = "Clear sessions";
$l_header_pref_update  = "Reset users preferences";

$l_header_help = "Aide";

$l_header_day = "Day";
$l_header_week = "Week";
$l_header_month = "Month";
$l_header_new_event = "New appointment";
$l_header_index     = "Main";


