<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English for global                                       //
//     - File     : global.inc                                               //
// 2001-12-27 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Common actions
$l_find = "Find";
$l_back = "Back";
$l_cancel = "Cancel";
$l_close = "Close the window";
$l_validate = "Validate";
$l_execute = "Execute action";
$l_confirm = "Confirm";
$l_home = "Home";

// Common messages
$l_yes = "Yes";
$l_no = "No";
$l_all = "All";
$l_all_f = "All";
$l_none = "---";
$l_comment = "Comment";
$l_add_comment = "Add a comment";
$l_upd_comment = "Update comment";
$l_mail_comment = "Send Mail";
$l_members = "Members";
$l_lang = "Lang";
$l_default = "Default";
$l_status = "Status";
$l_archive = "Archive";
$l_archive_first = "Arc";
$l_date = "Date";
$l_datebegin = "Begin date";
$l_dateend = "End date";
$l_name = "Name";
$l_label = "Label";
$l_number = "Number";
$l_invalid_data = "Invalid Data";
$l_error_permission = "You are not allowed to execute this action";
$l_error_visibility = "You can't access this information, it is private.";
$l_err_fill = "The field must be filled";
$l_query_error = "Error while executing the query";
$l_color = "Color";
$l_phone = "Phone";
$l_hphone = "Home phone";
$l_mphone = "Mobile phone";
$l_fax = "Fax";
$l_address = "Address";
$l_postcode = "Zip Code";
$l_town = "Town";
$l_expresspostal = "Express postal";
$l_country = "Country";
$l_desc = "Description";
$l_priority = "Priority";
$l_datasource = "Data source";
$l_after = "After";
$l_before = "Before";
$l_fuzzy = "Advanced";
$l_cat = "Category";
$l_visibility = "Access";
$l_private = "Private";
$l_public = "Public";
$l_local = "Local";
$l_ext_id = "Ext Id";
$l_manager = "Manager";
$l_client = "Customer";
$l_supplier = "Supplier";
$l_total = "Total";
$l_active = "Active";
$l_new = "New";
$l_last = "Last";
$l_login = "Login";
$l_logout = "Logout";
$l_profile = "Profile";
$l_connection_end = "Connection end";
$l_reconnect = "Click here to reconnect";

// Entities
$l_company = "Company";
$l_contact = "Contact";
$l_deal = "Deal";
$l_list = "List";
$l_publication = "Publication";
$l_todo = "To Do";
$l_time = "Time management";
$l_project = "Project";
$l_contract = "Contract";
$l_incident = "Incident";
$l_document = "Document";
$l_account = "Account";
$l_invoice = "Invoice";
$l_payment = "Payment";
$l_user = "User";
$l_group = "Group";
$l_settings = "Settings";

// Global display
$l_last_visit = "Bookmarks";

// OBM_DISPLAY
$l_entries = "Entries";
$l_page_res = "Result pages";
$l_export = "Export";
$l_export_all = "Export All";
$l_field = "Field";
$l_displayed = "Displayed";
$l_order = "Order";
$l_move = "Move";
$l_mandatory = "Display of this field is mandatory";
$l_display_no = "Stop displaying this field";
$l_display_yes = "Display this field";
$l_down = "Move the field down one row";
$l_up = "Move the field up one row";

// OBM_DISPLAY help screen
$l_help = "Help";
$l_help_display_yes = "The field is displayed. Click on this button if you want the field not to be displayed";
$l_help_display_no = "The field is not displayed. Click on this button if you want the field to be displayed";
$l_help_mandatory = "This field is mandatory";
$l_help_down  = "Move the field down";
$l_help_up = "Move the field up";
$l_document_added = " added documents";
$l_no_document_added = "No documents added";

// Javascript common messages
$l_fill_label = "You have to fill the label";
$l_fill_date = "The date must be filled";
$l_invalid_date = "Invalid date format (MM/JJ/AAAA ou AAAA-MM-JJ)";

// Tasktype groups
$l_task_fac = "Factured Tasks";
$l_task_int = "Internal Projects";
$l_task_div = "Not Factured Tasks";

// Days and months
$l_monthsofyear = array('January','February', 'March','April','May','June','July','August','September','October','November','December');
$l_monthsofyearshort = array('jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec');
$l_daysofweek = array('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
$l_daysofweekshort = array('Sun','Mon','Tue','Wed','Thu','Fri','Sat');
$l_daysofweekfirst = array ('S','M','T','W','T','F','S');

//---------------------------------------------------------------------------//
// Theme headers lang files
//---------------------------------------------------------------------------//

$l_section_com    = "COMMERCIAL";
$l_section_prod   = "PRODUCTION";
$l_section_compta = "ACCOUTANCY";
$l_section_user   = "USERS";
$l_section_admin  = "ADMINISTRATION";
$l_section_aliamin = "ALIAMIN";
$l_section_settings = "PREFERENCES";

$l_module_company = "Companies";
$l_module_contact = "Contacts";
$l_module_deal = "Deals";
$l_module_list = "Lists";
$l_module_agenda = "Calendar";
$l_module_todo    = "Todo";
$l_module_publication = "Publications";
$l_module_statistic = "Statistics";

$l_module_time = "Time management";
$l_module_project = "Projects";
$l_module_contract = "Contracts";
$l_module_incident = "Incidents";
$l_module_document = "Documents";

$l_module_account = "Accounts";
$l_module_invoice = "Invoices";
$l_module_payment = "Payments";

$l_module_settings = "Settings";
$l_module_user = "Users";
$l_module_group = "Groups";

$l_module_admin = "Administration";
$l_module_admin_lang = "Lang";
$l_module_admin_data = "Data";
$l_module_admin_pref = "Prefs";
$l_module_admin_code = "Code";
$l_module_admin_ref = "Referential";
$l_module_import = "Import";

$l_header_admin = "Administration";
$l_header_new_f = "New";
$l_header_new = "New";
$l_header_find = "Find";
$l_header_display = "Display";
$l_header_global_export = "Export";
$l_header_export = "Export";
$l_header_vcard = "Vcard";
$l_header_consult = "Consult";
$l_header_quickupdate = "Quick Update";
$l_header_update = "Update";
$l_header_delete = "Delete";
$l_header_add_contact = "Add contact";
$l_header_add_user = "Add user";
$l_header_add_group = "Add group";
$l_header_upd_group = "Update groups";
$l_header_add_deal = "Add deal";
$l_header_todo_list = "List";

$l_header_new_child = "New linked Deal";
$l_header_new_parent = "New ParentDeal";

$l_header_reconcile = "Reconcile";
$l_header_compute_balance = "Compute balance";
$l_header_duplicate = "Dupplicate";

$l_header_add_contact = "Add contact";

// Project headers
$l_header_man_task = "Tasks";
$l_header_man_member = "Members";
$l_header_advance = "Advance";
$l_header_man_affect = "Allocation";
$l_header_add_member = "Add member";
$l_header_dashboard = "Dashboard";

// Admin headers
$l_header_index = "Main";
$l_header_help = "Help";
$l_header_amp = "Show amp";
$l_header_func_unused = "Functions";
$l_header_clear_sess = "Clear sessions";
$l_header_pref_update = "Reset users preferences";
$l_header_reset = "Default Preferences";
$l_header_country = "Country";
$l_header_datasource = "Data Source";
$l_header_tasktype = "Task Type";

$l_header_year = "Year";
$l_header_day = "Day";
$l_header_week = "Week";
$l_header_month = "Month";
$l_header_new_event = "New appointment";

//time headers
$l_header_stats = "Statistics";
$l_header_statsmonth = "Monthly stats";
$l_header_statsuser = "User stats";
$l_header_weeklyview = "Week";
$l_header_monthlyview = "Month";
$l_header_globalview = "Validation";

//document headers
$l_document_new = "New document";
$l_document_add = "Link some documents";

//---------------------------------------------------------------------------//
// Home page portlets
//---------------------------------------------------------------------------//
$l_waiting_events = "Waiting event(s)";
$l_unfilled = "Day(s) unfilled";
$l_your_agenda = "Your calendar";
$l_your_time = "Your time management";

$l_my_deal_current = "My current deals";
$l_my_deal = "My deals";
$l_deal_total = "Total amount";
$l_deal_balanced = "Balanced amount";
