<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : header.inc                                               //
// 1999-01-27 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////
////// Theme headers lang files ////////////////////////
////////////////////////////////////////////////////////
$l_header_com    = "COMMERCIAL";
$l_header_prod   = "PRODUCTION";
$l_header_compta = "ACCOUTANCY";
$l_header_users  = "USERS";
$l_header_admins = "ADMINISTRATION";

$l_header_settings = "Settings";
$l_header_company = "Companies";
$l_header_contact = "Contacts";
$l_header_contract = "Contracts";
$l_header_incident = "Incidents";
$l_header_deal = "Deals";
$l_header_list = "Lists";
$l_header_user = "Users";
$l_header_admin = "Administration";
$l_header_admin_lang = "Lang";
$l_header_admin_data = "Data";
$l_header_admin_pref = "Prefs";
$l_header_admin_code = "Code";
$l_header_computer = "Computers";
$l_header_account = "Accounts";
$l_header_invoice = "Invoices";
$l_header_payment = "Payments";
$l_header_time = "Time management" ;
$l_header_agenda = "Calendar";

$l_header_title_computer = "COMPUTER" ;
$l_header_title_settings = "SETTINGS";
$l_header_title_company = "COMPANY";
$l_header_title_contact = "CONTACT";
$l_header_title_contract = "CONTRACT";
$l_header_title_incident = "INCIDENT";
$l_header_title_deal = "DEAL";
$l_header_title_list = "LIST" ; 
$l_header_title_user = "USER";
$l_header_title_admin = "ADMINISTRATION";
$l_header_title_account = "ACCOUNT";
$l_header_title_invoice = "INVOICE";
$l_header_title_payment = "PAYMENT";
$l_header_title_agenda = "CALENDAR";

$l_header_new_f = "New";
$l_header_new = "New";
$l_header_find = "Find";
$l_header_display = "Display";
$l_header_export = "Export";
$l_header_modify = "Modify";
$l_header_delete = "Delete";

$l_header_add_contact = "Add contact";

$l_header_reconcile = "Reconcile";
$l_header_compute_balance = "Compute balance";
$l_header_dupplicate = "Dupplicate";

$l_header_reset = "Défault Préferences";

$l_header_new_parent = "New ParentDeal";
$l_header_find_parent = "Find ParentDeal";

$l_header_day = "Day";
$l_header_week = "Week";
$l_header_month = "Month";
$l_header_new_event = "New appointment";

