<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : host.inc                                                 //
// 2004-09-09 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id: host.inc 2072 2007-09-13 23:49:27Z pierre $
///////////////////////////////////////////////////////////////////////////////

$l_smb = "Windows";
$l_smb_only = "Windows Only.";
$l_host_select_user = "Select the computer user";
$l_user = "User";
$l_web = "Web access";
$l_web_mode = "Web access allowed";
$l_web_list = "Access list";
$l_web_all = "All but list";
$l_web_list_only = "Only list";
$l_ftp = "FTP access";
$l_firewall = "advanced perms";
$l_perms = "Permissions";
$l_web_access = "Internet acces";
$l_restrict = "restrictions";
$l_not_assigned = "Not assigned";
$l_ip = "IP";
$l_host_display = "Display options for host lists"; 
$l_consult_web_list = "Refer to the URLs list";
$l_clear = "Break link";
$l_no_display = "Fill in the search fields and press < Find > to retrieve the hosts"; 
$l_found = "hosts found.";
$l_no_found = "No host matching the query has been found!"; 
$l_insert_ok = "Host insertion successful.";
$l_insert_error = "Host insertion fail !";
$l_update_ok = "Host update successful.";
$l_update_error = "Host update fail !";
$l_delete_ok = "Host delete successful.";
$l_delete_error = "Host delete fail !";
$l_can_delete = "Host can be delete";
$l_err_host_name_empty = "Host name must be filled in"; 
$l_err_host_name_exist = "Host name already used";
$l_err_host_name = "Invalid host name";
$l_err_host_windows_not_global = "A Windows host can notbe in the Global domain !"; 
$l_check_samehost = "This host seems similar to the new one"; 
$l_err_host_ip_exist = "Host IP address already used";
$l_err_host_delegation_exist = "Host Delegation already used.";
$l_err_host_ip = "Invalid host IP address";
$l_err_host_ip_not_in_lan = "Host IP address is not in the local network"; 
$l_err_firewall_perms = "Invalid advanced perms syntax";
$l_help_system = "System host is needed for the system.";
$l_cant_delete = "This host is linked to one or more domains thus it cannot be deleted"; 
$l_imap = 'IMAP';
$l_imap_archive = 'IMAP Archive';
$l_smtp_in = 'SMTP in';
$l_smtp_out = 'SMTP out';
$l_obm_sync = 'OBM Sync';
$l_imap_frontend = 'IMAP Frontend';
$l_solr = 'Solr';
$l_opush = 'OPush';
$l_opush_frontend = 'OPush Frontend';
$l_ldap = 'LDAP';
$l_provisioning = 'Provisioning';
$l_fqdn = 'Fully qualified name';
$l_err_host_fqdn = 'The fully qualified name is not well formed (computername.domaine.name)';

$l_backup_ftp = 'Backup FTP';
$l_backup_ftp_login = 'Backup FTP: Login';
$l_backup_ftp_password = 'Backup FTP: Password';
$l_backup_ftp_root = 'Backup FTP: Root path';
$l_err_host_backup_ftp_login_empty = 'The login used to connect to the FTP service must be filled in';
$l_err_host_backup_ftp_password_empty = 'The password used to connect to the FTP service must be filled in';
$l_err_host_backup_ftp_root_empty = 'The root path used to connect to the FTP service must be filled in';

