<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : import.inc                                               //
// 2004-01-17 AliaSource - Pierre Baudracco                                  //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T13:45:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:49:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:49:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:54:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:57:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:59:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:02:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:03:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:03:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:04:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:06:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:08:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:11:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:19:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:22:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:23:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:23:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:24:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:25:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:26:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:26:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:29:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:30:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:31:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:32:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:33:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:34:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:37:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:38:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:42:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:43:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:43:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:45:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:45:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:47:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:53:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:00:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:01:06+02:00 using OBMtranslation (0.4.1)

$l_import = "Import";
$l_format = "Format";
$l_csv_sep = "CSV Separator";
$l_enclosed = "Fields enclosed by";
$l_mapping = "Fields mapping";
$l_field_num = "# field";
$l_field = "field";
$l_default = "Default value";
$l_result = "Result";
$l_info = "Information";
$l_sample_file = "Sample file to check";
$l_conflict = "Conflict";
$l_nb_insert = "inserts";
$l_nb_update = "updates";
$l_mailing_ok_msg = "'X', '1', 'Y' to enable mailing";
$l_insert = "Insert import"; 
$l_update = "Update  import"; 
$l_delete = "Delete the import";
$l_check_file = "Check file"; 
$l_test_file = "Test file"; 
$l_comp_nothing = "Keep the actual company";
$l_comp_insert = "Insert company"; 
$l_comp_update = "Update existing company"; 
$l_con_nothing = "Keep the existing contact";
$l_con_insert = "Insert this contact";
$l_con_update = "Update the existing contact";
$l_name_import_nomatch = "Import name is not valid";
$l_import_exists = "Sorry but this import already exists";
$l_check_sameimport = "These imports seem similar to this new entry !";
$l_warn_delete = "Really delete this Import ?";
$l_import_end = "Import terminated";
$l_lines_processed = "lines processed";
$l_conflict_detected = "Conflict detected";
$l_invalid_row = "Invalid row !";
$l_invalid_rows = "Invalid rows";
$l_conflict_rows = "Conflict rows"; 
$l_no_display = "Fill in the search fields and press < Find > to retrieve the imports defined"; 
$l_found = "imports found.";
$l_no_found = "No imports matching the query have been found!"; 
$l_fill_name = "The Import Name must be filled in !"; 
$l_similar_company = "Similar company";
$l_used_company = "Used Company";
$l_similar_contact = "Similar contact";
$l_company_defaultname = "Company with no Name";
$l_contact_defaultname = "Contact with no Last name"; 
$l_same_company = "The imported company seems to be exactly the same as this one"; 
$l_auto_resolv = "Automatic company conflict management.";
$l_always_ask = "Always ask.";
$l_always_do_nothing = "Do nothing if a company is identical.";
$l_always_update_same = "Always update if the company is identical."; 
$l_always_update_similar = "Alway update if the company is identical or there is only one company which seems similar.";
$l_always_insert = "Always create a company if there is no strictly identical company."; 
$l_csvd_sc = ";";
$l_csvd_tab = "tab";

