<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : list.inc                                                 //
// 2001-02-16 AliaSource                                                     //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-09T15:20:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:08:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:09:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:11:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:16:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:22:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:31:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:35:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:41:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:48:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:50:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T09:55:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:05:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:25:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:26:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:32:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:33:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:33:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:34:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:35:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:36:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:40:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:42:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:52:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:56:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:56:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:57:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:59:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T10:59:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:07:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:11:16+02:00 using OBMtranslation (0.4.1)

$l_subject = "Subject";
$l_query = "Query";
$l_static = "Static";
$l_mode = "Mode";
$l_list_contact = "Having as contact";
$l_list_display = "Display options for Lists list";
$l_contact_display = "Display options for Contact lists"; 
$l_list_set = "List Set";
$l_criterion = "Search criteria";
$l_timeafter = "Updated after";
$l_timebefore = "Updated before";
$l_market = "Responsible";
$l_expert = "Expert";
$l_normal = "Normal";
$l_renew = "Automatic renewal";
$l_recept = "Reception mode";
$l_mailing = "Mailing enabled only";
$l_contact_archive = "Archived contacts";
$l_info_pub = "Publications information";
$l_function = "Function";
$l_service = "Service";
$l_letter = "Letterhead"; 
$l_quantity = "Quantity";
$l_insert = "Insert";
$l_update = "Update";
$l_delete = "Delete";
$l_add = "Add these lists";
$l_add_criterion = "Add a criterion";
$l_or = "OR";
$l_not = "NOT";
$l_and = "AND";
$l_empty = "&nbsp;";
$l_exclude = "Exclude";
$l_name_list_nomatch = "List name is not valid";
$l_list_exists = "Sorry but this list already exists";
$l_check_samelist = "These lists seem similar to this new entry !";
$l_j_check_email = "The email address is not valid.";
$l_has_contact = "registered contacts in this list";
$l_cant_delete = "The list cannot be deleted !"; 
$l_can_delete = "The list can be deleted.";
$l_list_wizard = "Global search";
$l_no_display = "Fill in the search fields and press < Find > to retrieve the lists"; 
$l_found = "lists found.";
$l_no_found = "No lists  matching the query have been found !"; 
$l_static_con_found = "static registered contacts";
$l_no_static_contact = "No static contact registered";
$l_dyn_con_found = "Contacts found";
$l_no_dyn_contact = "No contacts found";
$l_add_contact = "Add contacts to the list" ;
$l_del_contact_sel = "Remove these contacts";
$l_contact_added = "added Contact(s)";
$l_contact_removed = "removed Contact(s)";
$l_fill_name = "The list Name must be filled in !"; 
$l_fill_subject = "The subject must be filled in !"; 
$l_invalid_query = "Invalid query !"; 
$l_banned_word = "Banned word";
$l_incoherent_criteria = "Criteria are not coherent !";
$l_err_list_coh_pub = "$l_info_pub selected while same publication criteria combined with AND !";
$l_hungry_query = "The query needs too many resources !"; 
$l_warning_exp_to_nor = "Warning, You will lose your current query. Continue ?";
$l_warning_nor_to_exp = "Warning, the generated query will be editable directly in SQL. If you turn to normal mode, you will lose the changes you have manually made. Continue ?"; 
$l_status = "Status"; 
$l_j_select_list = "You have to select a list !"; 
$l_publication = "Publication"; 

