<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                   //
//     - File     : mailbox.inc                                              //
// 2009-05-15 Mehdi Rande                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id: resource.inc 3412 2008-12-10 10:35:39Z mehdi $ //
///////////////////////////////////////////////////////////////////////////////

$l_toggle_public_access = "";
$l_toggle_public_read = "This will make this mailbox readable for everybody. Do you want to continue ?";
$l_toggle_public_write = "This will make this mailbox writable for everybody. Do you want to continue ?";
$l_toggle_public_admin = "This will allow everybody to update the mailbox's right. Do you want to continue ?";

