<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                   //
//     - File     : organizationalchart.inc                                  //
// 2007-02-26 David PHAN                                                     //
///////////////////////////////////////////////////////////////////////////////
// $Id: organizationalchart.inc,v 1.17 2007/02/14 15:18:54 flo Exp $ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-10T16:32:41+02:00 using OBMtranslation (0.4.1)

$l_detail = "Detail";
$l_title = "Title";
$l_add_child_tooltip = "Add a child";
$l_zoom = "Zoom";
$l_zoom_big = "Big";
$l_zoom_small = "Small";
$l_outline = "Outline";
$l_insert = "Insert organizational chart";
$l_update = "update organizational chart";
$l_ldif_export = "LDIF Export";
$l_svg_export = "SVG Export";
$l_pdf_export = "PDF Export";
$l_no_display = "Fill in the search fields and press < Find > to retrieve the organizational chart"; 
$l_found = "organizational charts found";
$l_no_found = "No organizational chart matching the query has been found !"; 
$l_can_delete = "The organizational chart can be deleted";
$l_cant_delete = "The organizational chart cannot be deleted"; 
$l_fill_name = "You have to fill in the organizational chart name before submitting."; 
$l_fill_ogroup_name = "You have to fill in all node name before submitting."; 
$l_js_delete_node = "Do you really want to delete this node ?"; 
$l_js_delete_chart = "Do you really want to delete this organizational chart ?";
$l_organizationalchart_display = "Display options for organizational chart lists"; 

