<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                   //
//     - File     : profile.inc                                              //
// 2008-09-12 Vincent Bernard                                                //
///////////////////////////////////////////////////////////////////////////////
// $Id: profile.inc 2917 2008-05-31 15:08:08Z pierre $ //
///////////////////////////////////////////////////////////////////////////////

// Messages
$l_profile_name_error = "Profile name is invalid, please enter from 1 to 64 alphanumerical characters or _ !";
$l_profile_name_empty = "You must enter a profile name : from 1 to 64 alphanumerical characters or _ !";

// Noms de propriétés
$l_level = "Level";
$l_level_managepeers = "Manage peers level";
$l_access_restriction = "Access restriction";
$l_access_exeptions = "Access restriction exceptions";

// Messages d'erreurs
$l_level_empty = "The field Level is empty. Please enter 0, 1, 2, or 3 !";
$l_level_managepeers_empty = "The field Manage peers level is empty. Please enter 0 or 1 !";
$l_access_restriction_empty = "The field Access restriction exceptions is empty. Please fill it !";