<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                   //
//     - File     : profile.inc                                              //
// 2008-09-12 Vincent Bernard                                                //
///////////////////////////////////////////////////////////////////////////////
// $Id: profile.inc 2917 2008-05-31 15:08:08Z pierre $ //
///////////////////////////////////////////////////////////////////////////////

// Messages
$l_profile_name_error = "Profile name is invalid, please enter from 1 to 64 alphanumerical characters or _ !";
$l_profile_name_empty = "You must enter a profile name : from 1 to 64 alphanumerical characters or _ !";
