<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : report.inc                                               //
///////////////////////////////////////////////////////////////////////////////

// Titles
$l_report = "Reporting";
$l_valid_report = "Run report";

//Report
$l_user_report = "List of users";
$l_group_report = "List of groups";
$l_mailshare_report = "List of MailShare ";
$l_userarchive_report = "Archived users";
$l_alias_report = "List of user with alias";
$l_expiration_report = "List of user with date of expiration";
$l_mailquota_report = "Utilisation de la boite mail";
$l_mailredirection_report = "Affichage de la redirection de la boite mail";
$l_vacation_report = "Affichage de l'etat d'abscence des utilisateurs";
$l_used_percent = "Used Percent";
$l_all_services = "All service";
$l_choose_report = "Choice a report";

//User
$l_id = "Id";
$l_login = "Login";
$l_password = "Password";
$l_password_update = "Update Password";
$l_lastaccess = "Last access";
$l_phone2 = "$l_phone 2";
$l_fax2 = "$l_fax 2";
$l_email = "Email address";
$l_datebegin = "Entry date";
$l_dateexp = "Expiration date";
$l_exp = "Day before expery";
$l_noexperie = "Never expire";
$l_account_dateexp = "Expery Date";
$l_perms_user = "User";
$l_perms_editor = "Editor";
$l_perms_admin = "Administrator";
$l_infos = "Information";
$l_group = "Group";
$l_delegation_target = "Delegation target";
$l_photo = "Photo";

$l_hidden = 'Hidden mailbox';
$l_mail_server = "Mail Server";
$l_email_nomade = "Nomad email address";
$l_nomade = "Mail forwarding";
$l_access_nomade = "Mail forwarding";
$l_perms = "Allowed";
$l_local_copy = "Local copy";
$l_vacation = "Vacation message";
$l_vacation_message = "Message";
$l_vacation_datebegin = "From";
$l_vacation_dateend = "To";
$l_access = "Internet access";
$l_web = "Web access";
$l_smb = "Windows network";
$l_smb_perms = "Windows user";
$l_smb_home = "Home directory";
$l_smb_home_drive = "Home drive";
$l_smb_logon = "Logon script";
$l_group_member = "Member of groups";
$l_password_type = "Password Crypt";
$l_mailserver_auto = "Automatic";

//Group
$l_name = "Name";
$l_desc = "Description";
$l_description = "Description";

// Labels et textes
$l_nb_user = "# Users";
$l_group_user = "Containing user";
$l_group_display = "Display options for Groups lists";
$l_user_display = "Display options for Users lists";

//Warning
$l_warn_download = "No report choose";
$l_warn_exp = "Warning the account is nearly expired";
$l_warn_quota = "Warning the quota is nearly expired";
$l_warn = "Alert";

// Actions
$l_help = "Help";
