<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : user.inc                                                 //
// 2005-03-13 Florent Goalabre                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_desc  = "Description";
$l_qty  = "Quantity";
$l_check_resourcecreate = " entries owned by this user.";
$l_check_resourceupdate = " entries last updated by this user.";
$l_no_resource = "No resource fields in this table";
$l_fill_name = "You have to fill the name before submitting.";

// Titres
$l_resource = "Resource";
$l_resources = "Resources";
$l_users = "Users";

// Actions
$l_insert = "Insert the resource";
$l_update = "Update the resource";
$l_checkdelete = "Check or Delete the resource";
$l_reset = "Reset resource's preferences";
$l_delete = "Delete the resource";
$l_add = "Add these resources";

// Messages
$l_no_display = "Fill the search fields and press < Find > to retrieve the resources";
$l_found = "resource(s) found.";
$l_no_found = "No resource found matching the query !";
$l_cant_delete = "The resource can't be deleted !";
$l_can_delete = "The resource can be deleted.";
$l_check_sameuser = "These resources seem similar to this new entry !";
$l_exist_error = "already exists";

$l_add_resources = "Add resources";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_j_check_number = "The quantity is not valid.";

$l_resource_display = "Display options for resources lists";
