<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : samba.inc                                                //
// 2009-06-16 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id:$
///////////////////////////////////////////////////////////////////////////////

$l_samba = "Samba";
$l_smb_domain = "Domain";
$l_smb_sid = "SID";
$l_smb_pdc_name = "PDC name";
$l_smb_profile = "Profiles directory";
$l_default = "Default values";
$l_smb_home_def = "Home directory";
$l_smb_home_drive_def = "Home drive";

// Messages
$l_err_home = "The default home directory is incorrect !";
$l_err_drive = "The default home drive is incorrect !";

</script>
