<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : tools.inc                                                //
// 2002-09-26 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id: tools.inc 2171 2007-10-18 15:00:45Z anthony $
///////////////////////////////////////////////////////////////////////////////

$l_tools = "Administration tools";

$l_upd = "Update system configuration";
$l_upd_user = "My updates";
$l_upd_domain = "Domain updates";
$l_upd_delegation = "My delegation updates";
$l_upd_running = "System is configuring...";
$l_upd_already_running = "Impossible, system is already configuring...";
$l_upd_not_needed = "System configuration is <b>update</b>";
$l_upd_need_domain_update = "Domain modified ! Domain update needed";
$l_upd_needed = "System configuration is updated";
$l_upd_run = "Apply new system configuration";
$l_upd_cancel = "Cancel updates";
$l_upd_ok = "System configuration is applied";
$l_upd_error = "System configuration failed !";
$l_upd_cancel_ok = "Cancelling updates";
$l_upd_cancel_error = "Cancelling system updates failed !";

$l_created = "Creates";
$l_updated = "Updates";
$l_deleted = "Deletes";
$l_links = "Links";

$l_unspecified = "unspecified";
$l_js_ask_confirm = "Are you sure ?";

$l_halt = "System stop";
$l_halt_aliamin = "Stopping system";
$l_show_details = 'Show details';
