<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                   //
//     - File     : mailshare.inc                                            //
///////////////////////////////////////////////////////////////////////////////

// Labels et textes
$l_mailshare_display = "Display options for mailshares lists";
$l_mail_server = "Mail server";

// Messages
$l_no_display = "Fill the search fields and press < Find > to retrieve the mailshares";
$l_found = "mailshares found.";
$l_no_found = "No mailshare found matching the query !";

$l_can_delete = "Mailshare can be delete";
$l_cant_delete = "Host can't be delete";
$l_name_error = "Mailshare name isn't valid ! It cannot contains spaces character nor special char";
$l_name_in_use = "Mailshare name already used !";

$l_err_mailshare_name_empty = "Mailshare name must be fill";
$l_err_mailshare_name_exist = "Mailshare name already used";
$l_err_mailshare_quota = "Invalid mailshare quota !";
$l_err_mailshare_email = "Invalid mailshare E-mail !";
$l_err_mailshare_email_empty = "Mailshare E-mail must be fill !";
$l_err_mailshare_email_exist = "Mailshare E-mail already used !";
$l_err_mailshare_uemail_exist = "Same E-mail address used several times !";

$l_check_samemailshare = "This mailshare seems similar to the new mailshare";

$l_toggle_public_access = "";
$l_toggle_public_read = "This will make this mailsharereadable for everybody. Do you want to continue ?";
$l_toggle_public_write = "This will make this mailshare writable for everybody. Do you want to continue ?";
$l_toggle_public_admin = "This will allow everybody to update this mailshare's right. Do you want to continue ?";

