<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng Việt                                                   //
//     - File     : backup.inc                                               //
// 2005-08-22 Aliacom - Pierre Baudracco                                     //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

$l_bytes = "bytes";
$l_no_display = "Điền vào trường tìm kiếm và nhấn <Tìm> để lấy các bản sao lưu";
$l_backup_found = "Các bản sao lưu đã tìm thấy";
$l_no_found = "Không có bản sao lưu phù hợp với truy vấn của bạn!"; 
$l_restore_ok = "Bản sao lưu đã được phục hồi thành công.";
$l_restore_error = "Sao lưu thất bại !";
$l_err_backup_no_mail = "Bạn không thể sao lưu thực thể này, bởi vì hòm thư của nó chưa được kích hoạt.";
$l_err_host = "Bạn không thể sao lưu thực thể này, bởi vì hòm thư cử nó chưa từng được tạo.";
$l_create_backup_error = "Sao lưu tập tin thất bại!";
$l_delete_file_error = "Xóa tập tin sao lưu đã thất bại !";
$l_err_backup_name = "Tên tập tin sao lưu không hợp lệ !";
$l_err_backup_file = "Tập tin sao lưu không thể đọc !"; 
$l_err_backup_dir_not_exist = "Thư mục sao lưu không tồn tại !";
$l_err_backup_dir_not_writable = "Thư mục sao lưu không thể ghi !";
$l_can_delete = "Sao lưu có thể xóa.";
$l_cant_delete = "Sao lưu không thể xóa !"; 
$l_can_create = "Có thể tạo sao lưu này.";
$l_cant_create = "Không thể tạo sao lưu này !"; 
$l_err_unknown_db = "Không phát hiện được kiểu cơ sở dữ liệu!";
$l_delete = "Xóa bản sao lưu";
$l_insert = "Tạo bản sao lưu";
$l_restore = "Phục hồi";

$l_restore_mailbox = "Hòm thư";
$l_restore_calendar = "Lịch";
$l_restore_contact = "Danh sách liên lạc";
$l_restore_all = "Tất cả";
$l_backup_complete = "Sao lưu thành công.";
$l_restore_complete = "Phục hồi thành công.";
$l_no_backup_available = "Không có sao lưu!";
$l_err_cant_backup = "Có lỗi xảy ra, sao lưu thất bại !";
$l_err_cant_restore = "Một lỗi xảy ra, phục hồi thất bại !";
$l_err_cant_get_availablebackup = "Không thể lấy danh sách các bản sao lưu có sẵn !";
$l_cant_backup_pending_modifications = "Không thể sao lưu. Thực thể đang có một vài chỉnh sửa, xin vui lòng sử dụng công cụ cấu hình hệ thống để xác nhận nó";
$l_err_obm_satellite_usersystem = "Kết nối đến OBM vệ tinh thất bại : không thể lấy được người sử dụng hệ thống.";

$l_push_backup_ftp_failed = "Sao lưu đã không được thêm vào máy chủ FTP";
$l_retrieve_from_ftp = "Lấy bản sao lưu";
$l_retrieve_from_ftp_success = "Tất cả các bản sao lưu trên máy chủ FTP đã được lấy ra";
$l_no_backup_ftp_specified = "Không có máy chủ FTP xác định cho miền này.";
$l_retrieve_from_backup_ftp = "Bấm vào nút dưới đây để lấy tất cả các bản sao lưu cho '% s' trên máy chủ FTP miền.";
$l_unable_to_retrieve_backup = "Không thể lấy bản sao lưu được lưu trữ từ máy chủ FTP";

