<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng Việt                                               //
//     - File     : calendar.inc                                             //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_second = 'giây';
$l_minute = 'phút';
$l_hour = 'giờ';
$l_day = 'ngày';
$l_week = 'tuần';

$l_attendees = "Người tham dự";
$l_others_attendees = "Người tham dự khác";
$l_add_shared_calendar = "Thêm lịch chia sẻ";
$l_add_displayed_users = "Thêm người dùng hiển thị";
$l_add_displayed_resources = "Thêm tài nguyên hiển thị";
$l_show_user_calendar = "Hiển thị lịch người tham dự sau khi tạo sự kiện";
$l_show_resource_calendar = "Hiển thị lịch tài nguyên sau khi tạo sự kiện";
$l_users = "Người dùng";
$l_calendar = "Lịch";
$l_owner = "Người tổ chức/Chủ sự kiện";
$l_resources = "Tài nguyên";
$l_groups = "Nhóm";
$l_title = "Tiêu đề";
$l_location = "Địa điểm";
$l_private_description = "Đây là một sự kiện riêng tư, bạn không thể xem chi tiết";
$l_back_mono = "Trở lại chế độ xem của riêng bạn";
$l_back_to_calendar = "« Trở lại lịch";
$l_free_resources = "Tài nguyên miễn phí";
$l_go = "Đến";
$l_high = "Cao";
$l_low = "Thấp";
$l_medium = "Trung bình";
$l_details = "Chi tiết";
$l_occupied_day = "Cả ngày";
$l_user_right = "Quản lý quyền cho";
$l_exception = "Ngoại lệ";
$l_alerts = "Nhắc nhở";
$l_alerts_time = "Nhắc nhở (phút)";
$l_format = "(AAAA-MM-JJ)";
$l_repeat = "Lặp lại";
$l_periodicity = "Tần xuất";
$l_repeatkind = "Loại tần suất";
$l_repeatdays = "Ngày lặp lại (loại hàng tuần)";
$l_date_repeatend = "Lặp lại cuối";
$l_too_much_user = "Không nhiều hơn sáu người dùng";
$l_too_much_resource = "Không nhiều hơn sáu tài nguyên";
$l_waiting_events = "Các sự kiện đang đợi";
$l_calendar_visible = "Chọn lịch";
$l_calendar_displayed = "Lịch được hiển thị";
$l_resource_visible = "Chọn Tài nguyên";
$l_resource_displayed = "Tài nguyên được hiển thị";
$l_resource_allocated = "Tài nguyên được phân phối";
$l_repeatdays2 = "Ngày lặp lại";
$l_repeatfrequency = "Tần suất";
$l_everybody = "Tất cả mọi người";
$l_everyresources = "Tất cả tài nguyên";
$l_all_day = "Cả ngày";
$l_begin = "Bắt đầu";
$l_end = "Kết thúc";
$l_link_events = "Các sự kiện liên quan đến loại này ";
$l_accepted = "Chấp nhận";
$l_needs_action = "Hành động cần thiết";
$l_declined = "Từ chối";
$l_wait = "Đợi";
$l_free = "Miễn phí nhưng hạn chế";
$l_opacity = "Trạng thái";
$l_opacity_free = "Rảnh";
$l_opacity_busy = "Bận";
$l_possible = "Rảnh";
$l_occupied = "Không tồn tại";
$l_daily = "Hàng ngày";
$l_daily_unit = "%s ngày một lần";
$l_weekly = "Hàng tuần";
$l_weekly_unit = "%s tuần một lần";
$l_monthlybydate = "Hàng tháng (ngày)";
$l_monthlybyday_unit = "%s tháng một lần";
$l_monthlybyday = "Hàng tháng (thứ)";
$l_monthlybydate_unit = " %s tháng một lần";
$l_yearly = "Hàng năm";
$l_yearly_unit = "%s năm một lần";
$l_repeatkind = "Kiểu lặp";
$l_from = "từ";
$l_to = "đến";
$l_event_duration = "Thời gian họp";
$l_conflicts = "Xung đột được tìm thấy";
$l_date = "Ngày";
$l_user = "Người dùng";
$l_meeting_legend = "Chú thích";
$l_selection = "Lựa chọn";
$l_task = "Công việc";
$l_category_filter = "Lọc theo loại";
$l_cat_none = "Không";
$l_events = "Sự kiện";
$l_days = 'Thứ';
$l_more = 'chi tiết';
$l_know_more = 'Biết chi tiết';
$l_display_details = "Hiển thị chi tiết";
$l_one_day_per_page = "Một ngày cho một trang";
$l_display_days = "Hiển thi thứ";
$l_collapse_all = "Thu gọn tất cả";
$l_expand_all = "Mở rộng hết";
$l_edit = "Chỉnh sửa";
$l_view = "Xem";
$l_view_default = "Xem mặc định";
$l_views = "Các cửa sổ xem";
$l_select_view = "Chọn cửa sổ xem";
$l_insert_default_view = "Lưu diện mặc định";
$l_delete_default_view = "Xóa mặc định";
$l_view_label = "Xem nhãn";
$l_view_save = "Lưu khung xem";
$l_view_delete = "Xóa khung xem";
$l_view_invalid = "Khung này là không hợp lệ, nó không thể được hiển thị";

$l_first_hour = "Giờ bắt đầu";
$l_last_hour = "Giờ kết thúc";
$l_save_as_template = "Lưu làm bản mẫu";
$l_save_template = "Lưu bản mẫu";
$l_create_from_template = "Tạo ra từ mẫu";
$l_duplicate_template = "Bản sao mẫu";
$l_edit_template = "Chỉnh sửa mẫu";
$l_template = "Sự kiện mẫu";
$l_template_name = "Tên mẫu";
$l_header_templates = "Mẫu";
$l_no_template = "Không tìm thấy mẫu.";
$l_export_templates = "Xuất tất cả các mẫu";
$l_import_template = "Nhập mẫu";
$l_copy_of = "Copy của";
$l_template_entities_access_warning = "Bạn không được phép truy cập vào một số thành phần mẫu hoặc chúng có thể đã bị xóa";
$l_delete_template = "Xóa mẫu ?";

$l_hour = 'giờ';
$l_hours = 'nhiều giờ';
$l_day = 'thứ';
$l_days = 'nhiều thứ';
$l_week = 'tuần';

$l_insert = "Thêm sự kiện";
$l_update = "Cập nhật sự kiện";
$l_accept = "Chấp nhận";
$l_reject = "Từ chối";
$l_select = "Chọn";
$l_repeat_update = "Cập nhật tất cả các lần xuất hiện của cuộc hẹn này";
$l_go_to = "Đến";
$l_refuse = "Từ chối";
$l_state = "Trạng thái";
$l_change_state = "Sự kiện bạn Tham gia";
$l_force_insert = "Buộc thêm vào";
$l_refuse_insert = "Từ chối sự kiện";
$l_cancel_insert = "Chờ...";
$l_calendar_select_group = "Chọn nhóm.";
$l_force = "Buộc thêm sự kiện";
$l_force_disabled = "(không thể vì xung đột tài nguyên)";
$l_overbooking_not_allowed = "Không được phép đặt hàng vượt quá nguồn tài nguyên";
$l_carac = "Đặc điểm";
$l_meeting_perform = "Tìm kiếm các khoảng thời gian rảnh";
$l_owner_notification = "Thông báo cho chủ sự kiện";
$l_notification =  "Thông báo";
$l_attach_documents = "Đính kèm";
$l_add_documents = "Tài liệu đính kèm";
$l_event_color_tt = "Màu sự kiện được định nghĩa khi tạo sự kiện đó.";
$l_confirm_delete = "Thao tác này sẽ xoá sự xuất hiện của sự kiện này đối với tất cả người dùng, bạn có chắc bạn muốn tiếp tục?";
$l_confirm = "Xác nhận";
$l_cancel = "Hủy";
$l_update_warning = "Cảnh báo: bắt được một vài xung đột";
$l_insert_warning = "Cảnh báo: bắt được một vài xung đột";
$l_calendar_share_subject = "Chia sẻ lịch";
$l_resource_share_subject = " Chia sẻ lịch tài nguyên";
$l_update_error = "Các cuộc xung đột đã Được phát hiện, cập nhật bị hủy bỏ";
$l_insert_error = "Các cuộc xung đột đã Được phát hiện, thêm bị hủy bỏ";
$l_view_type = "Kiểu khung nhìn";
$l_sendamail = "Thông báo những người tham dự";
$l_select_contacts = "Bạn phải lựa chọn người dùng hoặc nhóm.";
$l_select_repeat_day = "Bạn phải chọn những ngày lặp lại.";
$l_select_pdf_day = "Bạn phải chọn một ngày";
$l_conflict_events = "Các thời gian lựa chọn đang bận cho ";
$l_fill_title = "Bạn phải điền vào trường [ $l_title ]";
$l_fill_dateend = "Bạn phải điền vào trường[ $l_dateend ]";
$l_fill_datebegin = "Bạn phải điền vào trường [ $l_datebegin ]";
$l_warn_date_past = "Ngày sự kiện bắt đầu là trong quá khứ";
$l_warn_file_upload = "Một số file không thể tải lên";
$l_warn_already_attached = "Một số tài liệu đã được đính kèm";
$l_err_file_access_forbidden = "Bạn không được phép truy cập tài liệu này";
$l_over_quota_error = "Thêm tài liệu này sẽ vượt quá dung lượng của bạn! Để thêm tài liệu này phải xóa một số tài liệu riêng.";
$l_dtstart_after_repeat_end_error = "Ngày đầu tiên của sự kiện hàng tuần này xảy ra sau ngày lặp lại của sự kiện";
$l_err_no_calendar_selected = "Không có lịch nào được chọn";
$l_err_begin_end = "Ngày kết thúc phải sau ngày bắt đầu!";
$l_err_end_repeat = "Ngày lặp lại phải sau ngày kết thúc";
$l_err_end_repeat2 = "Thời gian lặp lại tối đa là một năm";
$l_err_end_repeat3 = "Thời gian lặp lại tối đa là mười năm khi sự lặp lại là hàng năm";
$l_err_days_repeat = "Bạn phải chọn một hoặc nhiều ngày lặp lại.";
$l_err_days_repeat_not_weekly = "Bạn có thể chỉ chọn ngày lặp lại hàng tuần.";
$l_err_weekly_repeat = "Cho lặp lại hàng tuần, ngày kết thúc lặp phải có ít nhất bảy ngày sau khi kết thúc sự kiện này.";
$l_err_monthly_dateend_repeat = "Lặp lại hàng tháng, ngày kết thúc phải có ít nhất một tháng sau ngày kết thúc sự kiện. ";
$l_err_yearly_dateend_repeat = "Lặp lại hàng năm, ngày kết thúc phải có ít nhất một năm sau ngày kết thúc sự kiện.";
$l_err_repeatfrequency = "Tần số không hợp lệ";
$l_err_transparent_empty_resources = "Không tài nguyên nào có thể đặt trước khi các sự kiện có sẵn là miễn phí.";
$l_err_template_xml_import = "Các tập tin XML có định dạng kém!";
$l_event_cant_delete = "Bạn chỉ có thể xoá các sự kiện của riêng bạn!";
$l_fill_view_label = "Bạn phải điền vào trường [$ l_view_label]";
$l_confirm_delete_view = "Bạn có thực sự muốn xóa khung nhìn này?";
$l_confirm_default_view = "Bạn có thực sự muốn xóa giao diện mặc định?";
$l_no_sel_view = "Không thể xóa: không có khung nhìn nào được lựa chọn";
$l_no_sel_default_view = "Khung nhìn mặc định: không có khung nhìn nào được lựa chọn";
$l_conflict_view_label = "$l_view_label: Có xung đột";
$l_unknown = "Không rõ ";
$l_header_planning = "Đang lập kế hoạch";
$l_header_meeting = "Cuộc họp mới";
$l_header_admin = "Quản trị";
$l_header_waiting_events = "Các sự kiện đang chờ";
$l_header_export = "Xuất lịch";
$l_authorize_list = "Người dùng đã được cấp phép";
$l_denie_list = "Người dùng không được cấp phép";
$l_read_permission = "Quản lý truy cập đọc";
$l_write_permission = "Quản lý truy cập viết";
$l_everyone = "Tất cả mọi người đã được cấp phép";
$l_noone = "Không ai được cấp phép";
$l_authorize = "Cấp pháp";
$l_deny = "&gt;&gt;&gt;&gt;";
$l_periodic = "Định kỳ";
$l_add_event_mail_head = "Sự kiện mới trên OBM:";
$l_update_event_mail_head = "Sự kiện được cập nhật trên OBM:";
$l_delete_event_mail_head = "Sự kiện bị xóa trên OBM:";
$l_today_date = "Hôm nay";
$l_update_event_mail_body = "Thay cho: ";
$l_delete_event_mail_body = "Ngày: ";
$l_confirm_mail = "Thông báo Xác nhận + Buộc ";
$l_add_event_mail_subject = "Sự kiện mới trên OBM";
$l_update_event_mail_subject = "Sự kiện được cập nhật trên OBM";
$l_delete_event_mail_subject = "Sự kiện bị xóa trên OBM";
$l_attachments_mail_body = "Đính kèm:";
$l_interval_null = "Thời gian không thể null";
$mj_fill_title_event = "Bạn phải nhập tiêu đề cho sự kiện này ";
$mj_fill_time_begin = "Bạn phải nhập giờ bắt đầu";
$mj_fill_time_end = "Bạn phải nhập ngày kết thúc";
$mj_fill_valid_time_begin = "Bạn có để chèn một ngày bắt đầu hợp lệ";
$mj_fill_valid_time_end = "Bạn cần phải nhập một thời gian kết thúc hợp lệ";
$mj_delete_confirm = "Xác nhận xóa sự kiện?";
$mj_invalid_day = "Ngày này không tồn tại trong tháng được lựa chọn";
$mj_date_incompatibility = "Ngày kết thúc không không được trước ngày bắt đầu ";
$mj_repeat_date_incompatibility = "Ngày kết thúc lặp có không thể trước ngày bắt đầu.";
$mj_event_delete_confirm = "Xác nhận xóa sự kiện?";
$mj_event_delete_all_confirm = "Bạn có xác nhận việc hủy bỏ sự kiện này và tất cả các lần lặp lại của nó ?";
$l_view_agenda_desc = 'Khung lịch, khung nhìn này có thể chỉnh sửa';
$l_view_planning_desc = 'Khung nhìn kế hoạch, khung nhìn này không thể chỉnh sửa';
$l_view_printable_desc = 'Chế độ in, khung nhìn này không thể chỉnh sửa';
$l_view_list_desc = 'Khung danh sách, khung nhìn này không thể chỉnh sửa';
$l_view_week_desc = 'Khung tuần';
$l_view_day_desc = 'Khung ngày ';
$l_view_month_desc = "Khung tháng";
$l_expand_all = "Mở rộng hết";
$l_edit_full = "Nâng cao";
$l_confirm_delete_all = "Thao tác này sẽ loại bỏ tất cả các lần xuất hiện của sự kiện này đối với tất cả người dùng, bạn có chắc bạn muốn tiếp tục?";
$l_confirm_delete_single = "Thao tác này sẽ loại bỏ sự kiện này của tất cả người dùng, bạn có chắc bạn muốn tiếp tục?";
$l_ics_insert = 'Nhập lịch';
$l_ics_file = 'ICS file nhập';
$l_ics_import_ok = 'các sự kiện đã được thêm.';
$l_ics_import_nok = 'các sự kiện không được thêm (định dạng sai).';
$l_add_exception_mail_body = 'Sự kiện được cập nhật trên OBM: %s';
$l_delete_exception_mail_subject = 'Sự kiện được cập nhật trên OBM: %s';
$l_update_state_mail_subject = 'Người tham dự cập nhật trên sự kiện OBM: %s';
$l_resource_group_search = "Khe cắm miễn phí nếu";
$l_resources_one_freebusy = "Một nguồn tài nguyên rảnh phân theo nhóm";
$l_resources_all_freebusy = "Tất cả các nguồn tài nguyên rảnh";
$l_freebusy_autopick_prev = "«";
$l_freebusy_autopick_next = "AutoPick tiếp theo »";
$l_display_entites_freebusy = "Hiển thị người tham dự / tài nguyên bận";
$l_show_calendar = "Xem lịch";
$l_calendar_not_available = "Lịch không tồn tại hoặc không được chia sẻ";
$l_freebusy_check_availability = "Kiểm tra người tham dự và tài nguyên sẵn sàng ";
$l_no_end_repeat = "Không có kết thúc lặp lại";
$l_add_event_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
CUỘC HẸN MỚI
------------------------------------------------------------------

Bạn được mời tham gia vào một cuộc hẹn từ% s đến% s,
về chủ đề % s (vị trí:% s).


:: Thêm thông tin về cuộc hẹn này : 
%s
:: Chấp nhận cuộc hẹn này : 
%s
:: Từ chối cuộc hẹn này : 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi trên %s tại %s %s %s từ OBM
%s";
$l_add_resource_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
ĐẶT CHỖ TÀI NGUYÊN MỚI!
------------------------------------------------------------------

Một đặt chỗ tài nguyên mới được dự kiến ​​trên %s đến %s cho %s
(vị trí:%s).


:: Để chấp nhận hoặc từ chối đặt chỗ: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi trên %s tại %s %s %s từ OBM
%s";
$l_update_event_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
CẬP NHẬT CUỘC HẸN!
------------------------------------------------------------------

Cuộc hẹn %s, ban đầu dự kiến ​​từ %s đến %s (vị trí %s),
đã được cập nhật sẽ diễn ra từ %s đến% s (vị trí: %s).

:: Thêm thông tin về bản cập nhật này: 
%s
:: Chấp nhận bản cập nhật này: 
%s
:: Từ chối bản cập nhật này: 
%s

-------------------------------------------------------------------
email này đã được gửi đến %s lúc %s bởi %s %s từ OBM
%s";
$l_update_resource_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
CẬP NHẬT vIỆC ĐẶT CHỖ TÀI NGUYÊN!
------------------------------------------------------------------

Các đặt trước tài nguyên %s, ban đầu dự kiến ​​từ %s đến %s
(tại: %s) đã được cập nhật sẽ diễn ra từ %s đến %s
(tại: %s).

:: Để chấp nhận hoặc từ chối bản cập nhật này: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi %s tại %s bởi %s %s từ OBM 
%s";
$l_delete_event_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
XÓA CUỘC HẸN!
------------------------------------------------------------------

Cuộc hẹn %s, ban đầu dự kiến ​​từ %s đến %s
(tại: %s) đã bị xóa.

:: Liên hệ với ban tổ chức sự kiện này: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi %s tại %s bởi %s %s từ OBM 
%s";
$l_delete_resource_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
HỦY vIỆC ĐẶT CHỖ TÀI NGUYÊN !
------------------------------------------------------------------

Cuộc đặt trước %s, ban đầu dự kiến ​​từ %s đến %s
(tại: %s) đã bị hủy.

:: Liên hệ với ban tổ chức sự kiện này: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi %s tại %s bởi %s %s từ OBM 
%s";
$l_delete_exception_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
Phục hồi sự xuất hiện của cuộc hẹn!
------------------------------------------------------------------

Một hoặc nhiều lần xuất hiện của cuộc hẹn %s, ban đầu bị hủy 
(%s) đã được phục hồi.

:: Xem thêm thông tin: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi %s tại %s bởi %s %s từ OBM 
%s";
$l_add_exception_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
Hủy sự xuất hiện!
------------------------------------------------------------------

Một hoặc nhiều lần xuất hiện của cuộc hẹn %s, ban đầu được lập
(%s) đã bị hủy.

:: Xem thêm thông tin: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi %s tại %s bởi %s %s từ OBM 
%s";
$l_add_exception_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
CẬP NHẬT TRẠNG THÁI NGƯỜI THAM DỰ
------------------------------------------------------------------

Người tham dự %s đến %s vừa thay đổi đến %s.

:: Để biết thêm thông tin về cuộc hẹn này: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi %s tại %s bởi %s %s từ OBM 
%s";
$l_add_exception_mail_body = 
"email này đã được OBM tự động gửi đến
------------------------------------------------------------------
CUỘC HẸN SẮP DIỄN RA
------------------------------------------------------------------

Cuộc hẹn %s(%s) sẽ tổ chức trong %s phút (tại: %s).

::  Để biết thêm thông tin về cuộc hẹn này: 
%s

-------------------------------------------------------------------
Thông báo này đã được gửi vào %s lúc %s bởi OBM 
%s";
$l_confirm_reset = "Điều này sẽ đặt lại toàn bộ lịch của bạn, sẽ hủy bỏ tất cả các cuộc họp theo lịch trình của bạn. Bạn có chắc bạn muốn tiếp tục?";
$l_js_confirm_reset = 'Điều này không thể được hủy bỏ, bạn có muốn tiếp tục?';
$l_conflict_message = 'Một số người tham dự không có mặt khoảng thời gian này';
$l_conflict_manage = 'Quản lý xung đột';
$l_conflict_force = 'Buộc di chuyển';
$l_conflict_sendmail = 'Thông báo qua email?';
$l_toggle_public_access = "Điều này sẽ cho phép tất cả mọi người mời người dùng này đến cuộc họp. Bạn có muốn tiếp tục không?";
$l_toggle_public_read = "Điều này sẽ làm cho tất cả mọi người có thể đọc được lịch. Bạn có muốn tiếp tục không?";
$l_toggle_public_write = "Điều này sẽ cho phép tất cả mọi người cập nhật, chấp nhận và từ chối sự kiện cho người dùng này. Bạn có muốn tiếp tục không?";
$l_toggle_public_admin = "Điều này sẽ cho phép tất cả mọi người để cập nhật quyền lịch này. Bạn có muốn tiếp tục không ?";
$l_items = "Các mục";
$l_view_printable = "Có thể in";
$l_range_month = "Hàng tháng";
$l_view_agenda = "Lịch";
$l_ics = "Nhập lịch";
$l_warn_date_past = "Ngày bắt đầu sự kiện phải trong quá khứ ";
$l_add_exception_mail_subject = 
"Sửa đổi sự kiện trong OBM : %s
";
$l_range_week = "hàng tháng";
$l_rights_on_my = "Quyền dùng lịch";
$l_rights_my_on = "Quyền dùng lịch của tôi";
$l_alert_mail_subject = "Sự kiện sắp diễn ra ";
$l_cal_view = "Kiểu xem";
$l_range_day = "hàng ngày";
$l_view_planning = "Planning";
$l_view_list = "Danh sách sự kiện";
$l_cal_range = "Thời gian hiển thị";
$l_tag_management = "Quản lý Tag";
$l_other_files = "Các file khác";
$l_other_files_maxsize = "Cảnh báo: kích thước tập tin tối đa là ";
$l_other_files_detached = "Cảnh báo: các tập tin sau đây không được tải lên, xin vui lòng đính kèm lại chúng:";
$l_error_upload = "Tập tin tải lên lỗi.";
$l_other_files_upload_error = "Các tập tin sau đây không thể được tải lên bởi vì họ vượt quá kích thước tối đa cho phép ";
$l_other_files_upload_error_other = "Các tập tin sau đây không thể được tải lên vì lỗi truyền:";
$l_post_fatal_error = "Lỗi: yêu cầu của bạn không thành công vì dữ liệu gửi quá lớn (tập tin tải lên quá lớn?)";
$l_event_before_date = "Sự kiện trước ngày:";
$l_tags = "Tags";
$l_purge_popup_title = "Sổ địa chỉ lọc";
$l_allow_documents = "Cho phép người tham gia đính kèm tài liệu";
$l_tag_fill_color = "Bạn phải chọn một màu.";
$l_delete_meeting = "Xóa các cuộc họp từ lịch của tôi";
$l_search_my_calendar = "Tìm kiếm trong lịch của tôi";
$l_create_in_mine = "Sự kiện mới trong lịch của tôi";
$l_confirm_delete_export = "Các sự kiện từ lịch của bạn sẽ bị xóa, quá trình này không thể được hủy bỏ, bạn có muốn tiếp tục? ";
$l_ics_export_ok = "Các sự kiện đã xuất.";
$l_tag = "Tag";
$l_documents = "Tài liệu";
$l_all_calendar = "Tất cả lịch";
$l_search_result = "Kết quả tìm kiếm";
$l_delete_event = "Xóa cuộc hẹn từ lịch của tôi";
$l_tag_fill_label = "Bạn phải chèn một thẻ.";

// lines below have been created with OBMtranslation (0.5a) on 2009-11-12T18:44:51+01:00
$l_delete_occurrence_message = "Chỉ xóa trường hợp này hoặc tất cả các sự kiện trong chuỗi ?"; 
$l_parent_event = "Sự kiện cha"; 
$l_delete_all_occurrences = "Xóa tất cả các sự kiện trong chuỗi"; 
$l_show_parent_event = "Xem chuỗi sự kiện"; 
$l_delete_event_message = "Xóa sự kiện ?"; 
$l_eventexception_moved_to = "chuyển đến %s"; 
$l_delete_occurrence = "Xoá sự kiện này"; 
$l_eventexception_canceled = "Hủy"; 
$l_event_is_exception = "Sự kiện này đã được thay đổi không còn trong chuỗi"; 
$l_update_occurrence = "Cập nhật sự kiện này"; 
$l_update_event_occurrence = "Cập nhật sự kiện định kỳ"; 
$l_update_all_occurrences = "Cập nhật chuỗi sự kiện"; 
$l_delete_event_occurrence = "Xóa sự kiện định kỳ"; 
$l_update_occurrence_message = "Thay đổi chỉ sự kiện này hay chuỗi các sự kiện ?"; 

//Share calendar
$l_my_share_calendar = "Chia sẻ lịch của tôi";
$l_share_calendar = "Quản lý lịch";
$l_share_calendar_public = "Url từ lịch công khai";
$l_share_calendar_private = "Chính sách địa chỉ Lịch";
$l_share_freebusy = "URL rảnh/bận";
$l_desc_share_adresse_freebusy = "URL này là một địa chỉ cho phép người bên ngoài lấy thông tin bận / rỗi phần mềm nhóm OBM của bạn . Các tiêu đề cuộc họp và chi tiết không được hiển thị. ";
$l_share_calendar_freebusy ="Chia sẻ URL rảnh/bận của bạn";
$l_send_calendar_freebusy = "Gửi email thông tin rảnh / bận rộn của bạn ";
$l_share_mail_search = "nhập email ...";
$l_html = "HTML";
$l_share_ics = "Ical";
$l_share_err_auth = "Không đủ để quyền thực hiện sửa đổi trong chia sẻ chương trình nghị sự!";
$l_share_public = "Sử dụng địa chỉ này để chia sẻ lịch của bạn";
$l_share_reinit_private = "Thiết lập lại url cá nhân";
$l_share_reinit_public = "Thiết lập lại url công khai";
$l_send_calendar_private = "Gửi mail đến url cá nhân";
$l_send_calendar_public = "Gửi mail đến url công khai";
$l_reinit_calendar_private = "Thiết lập lại url cá nhân";
$l_reinit_calendar_public = "Thiết lập lại url công khai";
$l_desc_reinit_adress_public = "Địa chỉ công khai hiện tại sẽ không còn hiệu lực. Bạn sẽ tiếp tục?";
$l_desc_reinit_adress_private = "Địa chỉ cá nhân hiện tại sẽ không còn hiệu lực. Bạn sẽ tiếp tục?";
$l_desc_share_adresse_public = "URL của chương trình nghị sự là URL công khai cho lịch . Địa chỉ này cho phép người dùng khác để xem lịch công khai của bạn , các sự kiện công khai thông qua một trình duyệt web. ";
$l_desc_share_adresse_private = "Địa chỉ tin chương trình nghị sự của bạn được dành riêng cho sử dụng cá nhân. Tất cả các thông tin trên lịch của bạn sẵn có qua mối quan hệ riêng tư của bạn.";
$l_send = "Gửi";
$l_reinit_ok = "Thiết lập lại url thành công";
$l_share_ok = "chia sẻ hợp lệ";
$l_mail_ok = "Email đã được gửi";
$l_add_shared_calendar_ok = "Thêm lịch chia sẻ. Một số liên lạc tương ứng đã được tạo ra.";

$l_refresh = "Refresh";

$l_fontSize = "Cỡ chữ";
$l_fontSize_small = "Nhỏ";
$l_fontSize_medium = "Trung bình";
$l_fontSize_big = "To";

$l_filesize_units = array('Bytes','Kb','Mb','Gb','Tb','Pb');
$l_space_left = "trái";

// additional obm event description informations
$l_obm_reserved_event_data_attachment_begin = "// DANH SÁCH TÀI LIỆU KÈM THEO (DỮ LIỆUOBM RESERVED, KHÔNG SỬA NỘI DUNG) ";
$l_obm_reserved_event_data_attachment_end = "// KẾT THÚC DANH SÁCH TÀI LIỆU KÈM THEO ";

$l_event_add_organizer = "Ban tổ chức đã thêm người tham dự.";

// comments 
$l_comments = "Bình luận";
$l_addedit_comment = "Thêm / Sửa bình luận";
// alert popup
$l_add_alarm = "Thêm cảnh báo";
$l_addedit_alarm = "Thêm / Sửa cảnh báo";
// decision popup
$l_decision_ACCEPTED = "Chấp nhận";
$l_decision_NEEDS_ACTIONS = "Đợi";
$l_decision_DECLINED = "Từ chối";
$l_decision_situation = "Bạn chọn đến sự kiện <b id=\"yourDecision\"></b> : ";
$l_decision_possibility = "Bạn có thể bình luận quyết định của bạn nếu bạn muốn.";
$l_comment_decision = "Bình luận quyết định của bạn";
$l_without_comment = "Phản hồi mà không bình luận";
$l_with_comment = "Phản hồi có bình luận";
$l_remainingChar= "Ký tự còn lại";

// Edit occurrence
$l_edit_event_occurrence = 'Thay đổi sự tham gia cuộc hẹn này';
$l_edit_occurrence_message = 'Chỉ chỉnh sửa sự kiện này hoặc tất cả các sự kiện trong chuỗi?';
$l_edit_occurrence = 'Chỉnh sửa sự kiện này';
$l_edit_all_occurrences = 'Chỉnh sửa tất cả các sự kiện trong chuỗi';
$l_is_occurrence_of_parent_event = 'Sự kiện này là một phần của một chuỗi sự kiện';
$l_exception_already_set = "Vấn đề đồng bộ hóa: xin vui lòng làm mới lịch của bạn";

$l_resource_rights_information = "Read right on selected resource(s) is required";
