<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - File : Language : vn
//      - File : obminclude/en/campaign.inc
///////////////////////////////////////////////////////////////////////////////
// $Id: $ //
///////////////////////////////////////////////////////////////////////////////

$l_campaign_archive = "Lưu trữ";
$l_campaign_unarchive = "Không lưu trữ";
$l_created = "Tạo";
$l_ready = "Sẵn sàng";
$l_running = "Đang chạy";
$l_planified = "Lập kế hoạch";
$l_finished = "Hoàn thành";
$l_archived = "Đã lưu";
$l_error_mail_format = "Tập tin thư bị từ chối";
$l_error_target = "Lỗi đích";
$l_error_misc = "Lỗi";
$l_email_exists = "Bạn đã tải lên một tập tin. Bấm vào đây để tải lên tập tin khác.";
$l_email_undefined = "N/A";
$l_email_view = "Xem";
$l_campaign = "Chiến dịch";
$l_name = "Tên";
$l_status = "Trạng thái";
$l_start_date = "Ngày bắt đầu";
$l_end_date = "Ngày kết thúc";
$l_manager = "Người quản lý";
$l_email = "Email";
$l_objective = "Mục đích";
$l_comment = "Bình luận";
$l_progress = "Sự phát triển";
$l_targets = "Các mục tiêu";
$l_listes = "Các danh sách";
$l_users = "Các người dùng";
$l_groups = "Các nhóm";
$l_listss = "Danh sách";
$l_userss = "Người dùng";
$l_groupss = "Nhóm";
$l_target_type = "Loại mục tiêu";
$l_target_desc = "Tên";
$l_subcampaign = "Chiến dịch phụ";
$l_subcampaignss = "$l_subcampaign(s)";
$l_parent_campaign = "Chiến dịch cha";
$l_go = "Đi";
$l_campaign_can_delete = "Chiến dịch có thể bị xóa.";
$l_campaign_found = "Chiến dịch đã tìm thấy.";
$l_campaign_no_found = "Không tìm thấy chiến dịch nào.";
$l_err_name_empty = "Không thể để trống tên";
$l_err_dateanteriority = "Ngày bắt đầu phải trước ngày kết thúc."; 
$l_campaign_not_found = "Không tìm thấy chiến dịch.";

