<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng Việt                                               //
//     - File     : company.inc                                              //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_number = "Số hiệu";
$l_company_name = "Tên công ty";
$l_type = "Loại";
$l_activity = "Phạm vi hoạt động";
$l_nafcode = "NAF Code";
$l_market = "Quản lý Marketing";
$l_web = "Web";
$l_email = "E-Mail";
$l_coord = "Chi tiết";
$l_vat = "EU VAT";
$l_siret = "SIRET";
$l_contact_new = "Liên lạc mới";
$l_deal_new = "Thỏa thuận mới";
$l_project_new = "Dự án mới";
$l_contract_new = "Hợp đồng mới";
$l_internal = "Nội bộ";
$l_naf_manage = "Quản lý NAF Code";
$l_naf_exist = "NAF code hiện có";
$l_naf_new = "NAF Code mới";
$l_naf_label = "Nhãn";
$l_naf_code = "Code";
$l_naf_istitle = "Nó là một tựa đề"; 
$l_add = "Thêm";
$l_insert = "Thêm công ty";
$l_update = "Cập nhật công ty";
$l_checkdelete = "Kiểm tra hoặc xoá công ty";
$l_delete = "Xoá công ty";
$l_naf_update = "Cập nhật NAF Code";
$l_naf_checkdelete = "Kiểm tra hoặc Xóa NAF Code";
$l_naf_delete = "Xóa NAF Code";
$l_naf_insert = "Thêm NAF Code";
$l_select_company = "Chọn công ty";
$l_err_act_empty = "Bạn phải điền các hoạt động của công ty!";
$l_cat_no = "Không có chỉ mục (category) được xác định";
$l_no_display = "Điền vào các trường tìm kiếm và nhấn <Tìm> để lấy các công ty";
$l_found = "Các công ty tìm thấy.";
$l_no_found = "Không có công ty phù hợp với truy vấn đã tìm!";
$l_check_samecompany = "Không có công ty phù hợp với truy vấn đã tìm!";
$l_link_contact = "Công ty sở hữu những liên lạc";
$l_link_contact_no = "Công ty không có liên hệ";
$l_link_deal = "Công ty được tham chiếu bởi thỏa thuận";
$l_link_deal_no = "Công ty không được tham chiếu trong bất kỳ thỏa thuận nào"; 
$l_link_contract = "Công ty được tham chiếu bởi hợp đồng";
$l_link_contract_no = "Công ty không được tham chiếu vào trong bất kỳ hợp đồng"; 
$l_link_project = "Công ty được tham chiếu bởi dự án";
$l_link_project_no = "Công ty không tham chiếu vào trong bất kỳ dự án nào"; 
$l_link_invoice = "Công ty được tham chiếu bởi hoá đơn";
$l_link_invoice_no = "Công ty không được tham chiếu vào trong bất kỳ hoá đơn nào"; 
$l_cant_delete = "Công ty này không thể xóa!";
$l_can_delete = "Công ty này có thể xóa được.";
$l_naf_no = "Không xác định mã NAF";
$l_naf_link_company = "Các công ty này được tham chiếu bởi các mã NAF";
$l_naf_link_company_no = "Không có công ty liên kết với NAF code";
$l_naf_cant_delete = "Mã NAF không thể bị xóa!";
$l_naf_can_delete = "NAF code có thể xóa được.";
$l_delete_confirm = "Xác nhận xoá công ty?"; 
$l_fill_name = "Bạn phải nhập tên trước khi gửi.";
$l_j_check_zip = "Mã vùng Không hợp lệ.";
$l_j_check_phone = "Số điện thoại không hợp lệ.";
$l_j_check_fax = "Số fax không hợp lệ.";
$l_j_check_email = "Địa chỉ email không hợp lệ. Xác nhận tên miền";
$l_j_check_web = "Địa chỉ web không hợp lệ.";
$l_j_select_company = "Bạn phải chọn một công ty !";
$l_j_naf_create = "Bạn phải nhập mã NAF để tạo nó !";
$l_company_display = "Hiển thị tùy chọn danh sách các công ty ";
$l_phone_labels = array ('WORK_VOICE' => 'Phone', 'CELL_VOICE' => 'Mobile phone', 'WORK_FAX' => 'Fax', 'OTHER' => 'Other phone');
$l_email_labels = array ('INTERNET' => 'email', 'OTHER' => 'Other');
$l_address_labels = array ('HQ' => 'Headquarters', 'OTHER' => 'Other');
$l_website_labels = array ('URL' => 'Website', 'OTHER' => 'Other');
$l_j_naf_update = "Bạn phải chọn một mã NAF và cập nhật trước khi xác nhận.";
$l_j_cat_deep = "Các chỉ mục (category) không thể có nhiều hơn ba mức";
$l_j_naf_delete = "Chọn một mã số NAF để xác nhận hoặc để xóa!";
$l_comment = "Bình luận";

