<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng Việt                                                  //
//     - File     : contact.inc                                              //
// 1999-01-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_middlename = 'Tên đệm';
$l_mname = 'Tên đệm';
$l_commonname = 'Tên thường dùng';
$l_suffix = 'Suffix';
$l_market = "Người phụ trách";
$l_function = "Chức năng";
$l_title = "Tên công việc";
$l_minihphone = "(Nhà)";
$l_minimphone = "(Di động)";
$l_no_name = "Không tên";
$l_email = "E-Mail";
$l_email_other = "E-Mail khác";
$l_mailing_ok = "Cho phép gửi thư";
$l_mailok = "Cho phép gửi thư";
$l_mailing_ok_only = "Chỉ cho phép gửi thư";
$l_private_only = "Chỉ địa chỉ liên lạc riêng tư";
$l_newsletter = "Bản tin";
$l_news = "Tin tức";
$l_code = "Mã";
$l_letter = "Đề thư"; 
$l_comment1 = "Bình luận";
$l_comment2 = "Bình luận 2";
$l_comment3 = "Bình luận 3";
$l_date_after = "Đăng ký có hiệu lực ngày";
$l_date_before = "Hạn đăng ký trước";
$l_mailing_ok_first = "Thư.";
$l_other_infos = "Thông tin khác"; 
$l_birthday = "Sinh nhật"; 
$l_anniversary = 'Ngày lễ';
$l_assistant = 'Trợ lý';
$l_spouse = 'Vợ hoặc chồng';
$l_synchronisation = "Đăng ký";
$l_contact_name = "Tên liên hệ";
$l_from_company = "Từ Công ty";
$l_telother = "Điện thoại khác";
$l_contact_select_company = "Lựa chọn công ty để liên hệ."; 
$l_kind_manage = "Quản lý loại liên lạc";
$l_kind_exist = "Các loại hiện có";
$l_kind_no = "Không có loại xác định";
$l_kind_new = "Loại mới";
$l_header = "Tiêu đề";
$l_subscription = "Đăng ký";
$l_subscription_list = "Danh sách đăng ký";
$l_subscription_new= "Đăng ký mới";
$l_insert = "Thêm liên lạc"; 
$l_update = "Cập nhật liên lạc";
$l_checkdelete = "Kiểm tra hoặc Xóa liên lạc"; 
$l_delete = "Xóa liên lạc";
$l_kind_update = "Cập nhật Loại";
$l_kind_checkdelete = "Kiểm tra hoặc Xóa Loại";
$l_kind_delete = "Xóa Loại";
$l_kind_insert = "Thêm Loại";
$l_add_comment1 = "Thêm một bình luận";
$l_upd_comment1 = "Cập nhật bình luận";
$l_add_comment2 = "Thêm một bình luận 2";
$l_upd_comment2 = "Cập nhật bình luận 2";
$l_add_comment3 = "Thêm một bình luận 3";
$l_upd_comment3 = "Cập nhật bình luận 3";
$l_copy = "Copy";
$l_exportation = "Xuất";
$l_download_contact_card = "Tải thông tin liên lạc"; 
$l_vcard = "Vcard";
$l_sync_contact = "Đồng bộ PDA ";
$l_sync = "Đăng ký đồng bộ hóa";
$l_desync = "Hủy đăng ký đồng bộ hóa";

// $l_toggle_public_access = "This will allow everybody to invite this user to a meeting. Do you want to continue ?";
$l_toggle_public_read = "Điều này sẽ làm cho tất cả mọi người có thể đọc được cuốn sách địa chỉ  . Bạn có muốn tiếp tục?";
$l_toggle_public_write = "Điều này sẽ cho phép tất cả mọi người cập nhật sổ địa chỉ này. Bạn có muốn tiếp tục?";
$l_toggle_public_admin = " Điều này sẽ làm cho tất cả mọi người có thể cập nhật quyền cuốn sách địa chỉ  . Bạn có muốn tiếp tục?";


// Address books
$l_sync_ad = "Đăng ký";
$l_desync_ad = "Hủy đăng ký";
$l_delete_ad = "Xóa";
$l_update_ad = "Cập nhật";
$l_confirm_delete_ad = "Xóa sổ địa chỉ ";


// Messages
$l_check_samecontact = "Những địa chỉ liên lạc này có vẻ tương tự như mục nhập mới này!";
$l_link_deal = "Liên lạc tham gia vào một số giao dịch";
$l_link_deal_no = "Liên lạc không tham gia vào giao dịch nào"; 
$l_link_contract = "Liên lạc tham gia vào một số hợp đồng";
$l_link_contract_no = "Liên lạc không tham gia vào hợp đồng nào"; 
$l_link_list = "Liên lạc đăng ký vào một số danh sách";
$l_link_list_no = "Liên lạc không đăng ký vào danh sách nào"; 
$l_link_publication = "Liên lạc có số đăng ký";
$l_link_publication_no = "Liên lạc không có số đăng ký"; 
$l_cant_delete = "Liên lạc không thể xóa !"; 
$l_can_delete = "Liên lạc có thể xóa.";
$l_no_display = "Điền thông tin tìm kiếm và nhấn <Tìm> để lấy địa chỉ liên lạc này"; 
$l_found = "Những Liên lạc được tìm thấy.";
$l_no_found = "Không có Liên lạc phù hợp với truy vấn đã tìm!"; 
$l_no_export = "Không có Liên lạc để xuất!";
$l_kind_link_company = "Các công ty này được tham chiếu";
$l_kind_link_company_no = "Không có công ty nào được tham chiếu";
$l_kind_cant_delete = "Loại không thể xóa!"; 
$l_kind_can_delete = "Loại có thể xóa.";
$l_birthday_event_title = "Sinh nhật của %s";
$l_anniversary_event_title = "Ngày lễ của %s";
$l_fill_lastname = "Bạn phải điền họ trước khi gửi."; 
$l_fill_company = "Bạn phải chọn một công ty trước khi gửi.";
$l_fill_phone = "Bạn phải điền số điện thoại trước khi gửi."; 
$l_delete_confirm = "Xác nhận xóa Liên lạc?"; 
$l_j_check_phone = "Số điện thoại không hợp lệ.";
$l_j_check_hphone = "Số điện thoại cá nhân không hợp lệ.";
$l_j_check_mphone = "Số điện thoại di động không hợp lệ.";
$l_j_check_fax = "Số fax không hợp lệ.";
$l_j_check_email = "Địa chỉ email không hợp lệ. Kiểm tra miền."; 
$l_j_select_contact = "Bạn phải chọn một Liên lạc !";
$l_j_kind_delete = "Bạn phải chọn một loại để kiểm tra hoặc xóa !";
$l_j_kind_update = "Bạn phải chọn một loại và nhập tên mới để cập nhật nó!";
$l_j_kind_create = "Bạn phải điền tất cả các loại thông tin tạo mới!"; 
$l_contact_display = "Hiển thị tùy chọn cho danh sách Liên lạc"; 
$l_timecreate = "Tạo mới";
$l_timeupdate = "Cập nhật cuối";
$l_publication_title = "Tiêu đề";
$l_renewal = "Tự động gia hạn";
$l_recept = "Chế độ tiếp nhận";
$l_quantity = "Số lượng";
$l_no_found_subscription = "Không tìm thấy đăng ký cho liên hệ này!";
$l_vcf_file = "VCF file để thêm";
$l_phone_labels = array ('HOME_VOICE' => 'Điện thoại nhà', 'WORK_VOICE' => 'Điện thoại nơi làm việc', 'CELL_VOICE' => 'Điện thoại di động', 'HOME_FAX' => 'fax tại nhà', 'WORK_FAX' => 'fax nơi làm việc', 'PAGER' => 'Máy nhắn tin', 'OTHER' => 'Điện thoại khác');
$l_email_labels = array ('INTERNET' => 'Nhà', 'OTHER' => 'Khác');
$l_address_labels = array ('HOME' => 'Nhà', 'WORK' => 'Nơi làm việc', 'OTHER' => 'Khác');
$l_website_labels = array ('URL' => 'Trang chủ', 'BLOG' => 'Blog',  'CALURI' => 'Lịch', 'OTHER' => 'Khác');
$l_im_labels = array('XMPP' => 'Jabber', 'X_GTALK' => 'Google Talk', 'AIM' => 'AIM', 'YMSGR' => 'Yahoo', 'MSN' => 'MSN', 'X_ICQ' => 'ICQ', 'OTHER' => 'Other');
$l_company_phone_labels = array ('COMPANY_WORK_VOICE' => 'Company\'s phone', 'COMPANY_CELL_VOICE' => 'Company\'s mobile', 'COMPANY_WORK_FAX' => 'Company\'s fax', 'COMPANY_OTHER' => 'Company\'s other phone');
$l_company_email_labels = array ('COMPANY_INTERNET' => 'Company\'s mail', 'COMPANY_OTHER' => 'Company\'s other');
$l_company_address_labels = array ('COMPANY_HQ' => 'Company\'s headquarters', 'COMPANY_OTHER' => 'Company\'s other');
$l_company_website_labels = array ('COMPANY_URL' => 'Company\'s website', 'COMPANY_OTHER' => 'Company\'s other');
// Error Messages
$l_err_length_express_postal = "Trường 'EXPRESS POSTAL' có tối đa 16 ký tự";
$l_err_length_express_postal = "Field 'ZIP CODE' có tối đa 14 ký tự";
$l_add_fields =  'Thêm trường';
