<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng Việt                                               //
//     - File     : cv.inc                                                   //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_title = "Tiêu đề";
$l_timeupdate = "Cập nhật ngày";
$l_timecreate = "Ngày tạo";
$l_lastname = "Họ";
$l_firstname = "Tên";
$l_login = "Login";
$l_keyword_title = "Từ khóa trong tiêu đề";
$l_keyword_education = "Từ khóa trong đào tạo";
$l_project_name = "Dự án tham chiếu";
$l_deal_name = "Thỏa thuận tham chiếu";
$l_education = "Đào tạo";
$l_location = "Địa chỉ";
$l_phone = "Điện thoại";
$l_additionalrefs = "Tham chiếu bổ sung";
$l_ref = "Tham chiếu";
$l_refs = "Nhiều tham chiếu";
$l_project_date = "Ngày";
$l_project_duration = "Thời hạn";
$l_project_desc = "Mô tả";
$l_project_tech = "Mô tả kỹ thuật";
$l_personal = "Thông tin cá nhân";
$l_user = "Người sử dụng";
$l_role = "Vai trò";
$l_export = "Xuất";
$l_anonymous = "Vô danh";
$l_template = "Bản mẫu";
$l_template_kind = "Loại bản mẫu";
$l_default_template = "Mẫu mặc định";
$l_other_template = "Mẫu khác (tài liệu OBM)";
$l_unreferenced_template = "Mẫu khác";
$l_template_selection = "Lựa chọn bản mẫu";
$l_defaultodttemplate_document = "Tài liệu";
$l_defaultodttemplate_label = "Nhãn";
$l_defaultodttemplate_manage = "Quản lý mẫu Odt mặc định";
$l_defaultodttemplate_exist = "Mẫu mặc định hiện có";
$l_cv_display = "Hển thị danh sách CV tùy chọn";
$l_select_user = "Chọn một người dùng";
$l_select_cv = "Chọn một CV";
$l_update = "Cập nhật CV";
$l_insert = "Thêm CV";
$l_delete = "Xóa CV";
$l_duplicate = "Bản sao";
$l_add_ref = "Thêm một tham chiếu";
$l_add_additionalref = "Thêm một tham chiếu bổ sung";
$l_select_ref = "Chọn một dự án";
$l_select_template = "Chọn một mẫu";
$l_template_delete = "Xóa mẫu";
$l_template_update = "Cập nhật mẫu";
$l_template_insert = "Thêm mẫu";
$l_no_display = "Điền vào các trường tìm kiếm và nhấn <Tìm> để lấy CV.";
$l_found = "CV đã tìm thấy.";
$l_no_found = "Không tìm thấy CV phù hợp với truy vấn!";
$l_insert_ok = "CV đã được thêm thành công.";
$l_insert_error = "Thêm CV đã thất bại!";
$l_update_ok = "CV đã được cập nhật thành công.";
$l_update_error = "Việc cập nhật CV đã thất bại!";
$l_delete_ok = "CV đã được xóa thành công.";
$l_delete_error = "Việc xoá CV đã thất bại!";
$l_cant_delete = "CV không thể xóa!";
$l_can_delete = "CV có thể bị xóa.";
$l_delete_confirm = "Xác nhận xóa CV?";
$l_err_title_empty = "Bạn phải điền vào các tiêu đề của CV trước khi gửi!"; 
$l_defaultodttemplate_insert_ok = "Mẫu đã được thêm thành công.";
$l_defaultodttemplate_insert_error = "Chèn bản mẫu đã thất bại!";
$l_defaultodttemplate_update_ok = "Mẫu đã được cập nhật thành công.";
$l_defaultodttemplate_update_error = "Việc cập nhật mẫu đã thất bại!";
$l_defaultodttemplate_delete_ok = "Mẫu đã được xóa thành công.";
$l_defaultodttemplate_delete_error = "Việc xóa các mẫu đã thất bại!";
$l_loading = "Đang tải....";
$l_loaded = "Tài liệu  đã được tải lên thành công !";
$l_js_fill_title = "Bạn phải điền vào các tiêu đề của CV trước khi gửi.";
$l_j_already_added = "Dự án này đã được bổ sung vào tham chiếu CV !";

