<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - File : Language : vi
//      - File : obminclude/vi/imap_archive.inc
///////////////////////////////////////////////////////////////////////////////
// $Id: $ //
///////////////////////////////////////////////////////////////////////////////

$l_daily = "Hàng ngày";
$l_weekly = "Hàng tuần";
$l_monthly = "Hàng tháng";
$l_yearly = "Hàng năm";
$l_monday = "Thứ hai";
$l_tuesday = "Thứ ba";
$l_wednesday = "Thứ tư";
$l_thursday = "Thứ năm";
$l_friday = "Thứ sáu";
$l_saturday = "Thứ bảy";
$l_sunday = "Chủ nhật";
$l_last = "Cuối cùng";
$l_service_activating = "Kích hoạt dịch vụ";
$l_activating = "Kích hoạt";
$l_scheduling = "Lập kế hoạch";
$l_repeat_kind = "Loại lặp lại";
$l_weekly_repeat_kind = "Ngày nghỉ hàng tuần trong tuần";
$l_monthly_repeat_kind = "Ngày hàng tháng của tháng";
$l_yearly_repeat_kind = "Ngày hàng năm của năm";
$l_hour = "Giờ";
$l_minute = "Phút";
$l_next_run = "Chạy tiếp theo";
$l_folder = "Thư mục";
$l_excluded_folder = "Thư mục loại trừ";
$l_excluded_users = "Người sử dụng loại trừ";
$l_name = "Tên";
$l_delete = "Xóa";
$l_remove_archive = "Loại bỏ từ kho lưu trữ";
$l_mailing_feedback = "Gửi email đến";
$l_mailing_email = "Dịa chỉ email";
$l_past_operations = "Hoạt động trong quá khứ";
$l_start_time = "Thời gian bắt đầu";
$l_end_time = "Kết thúc thời gian";
$l_status = "Tình trạng";
$l_last_fail = "Thất bại cuối cùng";
$l_simulation = "mô phỏng";
$l_manual_launch = "Dẫn ra mắt";
$l_status_error = "lỗi";
$l_status_success = "Ok";

$l_email_address_not_found = "Không thể tìm thấy địa chỉ email của bạn cho tên miền này";
$l_imap_archive_server_not_found = "Không thể tìm thấy một máy chủ lưu trữ IMAP cho tên miền này";
$l_imap_archive_server_unreachable = "Máy chủ lưu trữ IMAP không thể kết nối";
$l_domain_configuration_not_found = "Cấu hình lưu trữ IMAP không tìm thấy cho tên miền này";
$l_domain_configuration_disable = "Cấu hình lưu trữ vô hiệu hóa IMAP cho tên miền này";
$l_could_not_login_imap_archive_server = "Không thể đăng nhập vào máy chủ lưu trữ IMAP";
$l_archiving_running = "Lưu trữ các bản ghi hiện tại";
$l_unsupported_iframe = "Trình duyệt của bạn không hỗ trợ iframe.";
$l_archiving_launched = "Các kho lưu trữ có-beens Ra mắt thành công.";
$l_excluded_folder_error = "Thư mục loại trừ không hợp lệ! Nó không được chứa ký tự đặc biệt";
$l_confirm_manual_launch = "Một tab mới sẽ được mở ra với các bản ghi quá trình lưu trữ trong đó. Bạn có chắc chắn bạn muốn kích hoạt lưu trữ bằng tay bây giờ?";
