<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng việt                                               //
//     - File     : lead.inc                                                 //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

$l_insert = "Chèn khách hàng tiềm năng"; 
$l_update = "cập nhật khách hàng tiềm năng"; 
$l_delete = "Xóa khách hàng tiềm năng"; 
$l_select_company = "Chọn công ty"; 
$l_can_delete = "Có thể xóa khách hàng tiềm năng.";
$l_cant_delete = "lead không thể xóa!"; 
$l_err_name_empty = "Bạn phải nhập tên!"; 
$l_err_source_empty = "Bạn phải điền vào nguồn của khách hàng tiềm năng!"; 
$l_err_market_empty = "Bạn phải nhập người quản lý!"; 
$l_no_display = "Điền vào các trường tìm kiếm và nhấn <Tìm> để lấy lại khách hàng tiềm năng"; 
$l_found = "Khách hàng tiềm năng đã tìm thấy.";
$l_no_found = "Không khách hàng tiềm năng mà phù hợp với truy vấn đã tìm!"; 
$l_fill_name = "Bạn phải điền tên trước khi gửi !"; 
$l_fill_datealarm = "Bạn phải điền ngày báo !"; 
$l_fill_company = "Bạn phải điền công ty trước khi gửi!"; 
$l_invalid_date = "Định dạng ngày không hợp lệ (MM/JJ/AAAA hoặc AAAA-MM-JJ).";
$l_delete_confirm = "Xác nhận xóa khách hàng tiềm năng?"; 
$l_lead_display = "Hiển thị tùy chọn cho các danh sách khách hàng tiềm năng"; 

