<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng Việt                                               //
//     - File     : list.inc                                                 //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_subject ="Chủ đề";
$l_query = "Truy vấn";
$l_static = "Tĩnh";
$l_mode = "Chế độ";
$l_list_contact = "Đang có liên lạc";
$l_list_display = "Hiển thị các tùy chọn cho danh sách"
$l_contact_display = "Hiển thị các tùy chọn cho danh sách liên hệ"; 
$l_list_set = "Cài đặt danh sách";
$l_criterion = "Tiêu chí tìm kiếm";
$l_timeafter = "Cập nhật sau";
$l_timebefore = "Cập nhật trước";
$l_market = "Chịu chách nhiệm";
$l_expert = "Chuyên gia";
$l_normal = "Bình thường";
$l_renew = "Tự động gia hạn";
$l_recept = "Chế độ tiếp nhận";
$l_mailing = "Chỉ kích hoạt Email";
$l_contact_archive = "Liên hệ lưu trữ";
$l_info_pub = "Thông tin công bố";
$l_function = "Chức năng";
$l_service = "Dịch vụ";
$l_letter = "Bìa thư"; 
$l_quantity = "Số lượng";
$l_insert = "Chèn";
$l_update = "Cập nhật";
$l_delete = "Xóa";
$l_add = "Thêm danh sách";
$l_add_criterion = "Thêm một tiêu chí";
$l_or = "Hoặc";
$l_not = "Không";
$l_and = "Và";
$l_empty = "&nbsp;";
$l_exclude = "Loại trừ";
$l_name_list_nomatch = "Tên danh sách hợp lệ";
$l_list_exists = "Danh sách này đã tồn tại";
$l_check_samelist = "Danh sách này giống với phần nhập mới !";
$l_j_check_email = "Địa chỉ email không hợp lệ.";
$l_has_contact = "Liên lạc đã được lưu danh sách này";
$l_cant_delete = "Danh sách này không thể xóa "; 
$l_can_delete = "Danh sách này có thể xóa.";
$l_list_wizard = "Tìm kiếm chung";
$l_no_display = "Điền vào trường tìm kiếm và nhấn < tìm > để lấy danh sách"; 
$l_found = "Các danh sách đã tìm thấy .";
$l_no_found = "Không có danh sách phù hợp với truy vấn đã tìm!"; 
$l_static_con_found = "Liên hệ đăng ký tĩnh";
$l_no_static_contact = "Không có liên hệ đăng ký tĩnh";
$l_dyn_con_found = "Liên lạc được tìm thấy";
$l_no_dyn_contact = "Không tìm thấy liên lạc";
$l_add_contact = "Thêm liên lạc vào danh sách" ;
$l_del_contact_sel = "Loại bỏ liên lạc";
$l_contact_added = "Thêm liên lạc";
$l_contact_removed = "Xóa liên lạc";
$l_fill_name = "Tên danh sách phải được điền!"; 
$l_fill_subject = "Chủ đề phải được điền!"; 
$l_invalid_query = "Truy vấn không hợp lệ !"; 
$l_banned_word = "Từ cấm";
$l_incoherent_criteria = "Tiêu chí nhập vào không hợp lý!";
$l_err_list_coh_pub = "$l_info_pub chọn trong khi các tiêu chí công bố giống nhau kết hợp với VÀ !";
$l_hungry_query = "Truy vấn cần nhiều tài nguyên!"; 
$l_warning_exp_to_nor = "Cảnh báo, bạn sẽ mất truy vấn hiện tại. Tiếp tục không?";
$l_warning_nor_to_exp = "Cảnh báo, truy vấn được tạo ra sẽ có thể bị chỉnh sửa trực tiếp tại SQL. Nếu bạn bật chế độ bình thường, bạn sẽ mất các thay đổi mà bạn đã tự làm. Tiếp tục không ?"; 
$l_status = "Trạng thái"; 
$l_j_select_list = "Bạn phải chọn một danh sách !"; 
$l_publication = "Công bố"; 

