<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng việt                                               //
//     - File     : organizationalchart.inc                                  //
///////////////////////////////////////////////////////////////////////////////
// $Id: organizationalchart.inc
///////////////////////////////////////////////////////////////////////////////

$l_detail = "Chi tiết";
$l_title = "Tiêu đề";
$l_add_child_tooltip = "Thêm một nút con";
$l_zoom = "Phóng";
$l_zoom_big = "To";
$l_zoom_small = "Nhỏ";
$l_outline = "Phác thảo";
$l_insert = "Chèn sơ đồ tổ chức";
$l_update = "Cập nhật sơ đồ tổ chức";
$l_ldif_export = "Xuất ra LDIF";
$l_svg_export = "Xuất ra SVG";
$l_pdf_export = "Xuất ra PDF";
$l_no_display = "Điền vào các trường tìm kiếm và nhấn <Tìm> để lấy lại sơ đồ tổ chức"; 
$l_found = "sơ đồ tổ chức đã tìm thấy";
$l_no_found = "Không có sơ đồ tổ chức phù hợp với truy vấn đã tìm!"; 
$l_can_delete = "Sơ đồ tổ chức có thể xóa";
$l_cant_delete = "Sơ đồ tổ chức không thể xóa"; 
$l_fill_name = "Bạn phải điền đầy đủ tên biểu đồ tổ chức trước khi gửi."; 
$l_fill_ogroup_name = "Bạn phải điền tất cả các tên nút trước khi gửi."; 
$l_js_delete_node = "Bạn có thực sự muốn xóa nút này không ?"; 
$l_js_delete_chart = "Bạn có thực sự muốn xóa biểu đồ tổ chức này không ?";
$l_organizationalchart_display = "Hiển thị tùy chọn cho các danh sách sơ đồ tổ chức"; 

