<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng việt                                               //
//     - File     : password.inc                                             //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

$l_old_password = "Mật khẩu hiện tại";
$l_new_password = "Mật khẩu mới";
$l_new_password_bis = "Xác nhận mật khẩu mới";
$l_wrong_password = "Mật khẩu hiện tại không hợp lệ!";
$l_new_password_differ = "Mật khẩu mới khác!"; 
$l_password_invalid = "Mật khẩu mới không hợp lệ - phải có từ 4 đến 12 ký tự (chữ và số hoặc -\$\&~#{([|_`^@);]+=}%!:/.,?<>\")!";
$l_fill_password = "Bạn phải nhập mật khẩu trước khi xác nhận."; 

