<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng việt                                                  //
//     - File     : group.inc                                                //
// 2003-08-22 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-09T15:20:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T16:32:41+02:00 using OBMtranslation (0.4.1)

$l_nb_resource = "#Tài nguyên";
$l_resourcegroup_resource = "Có nguồn tài nguyên";
$l_resourcegroup_display = " Hiển thị tùy chọn các danh sách nhóm ";
$l_resource_display = "Hiển thị tùy chọn các danh sách tài nguyên";
$l_resourcegroup = "Nhóm tài nguyên"; 
$l_resourcegroups = "Nhóm tài nguyên";
$l_qty = "Số lượng";
$l_insert = "Chèn nhóm";
$l_update = "Cập nhật nhóm"; 
$l_delete = "Xóa nhóm"; 
$l_add = "Thêm các nhóm này";
$l_fill_name = "Bạn phải điền vào tên nhóm"; 
$l_resourcegroup_exists = "Nhóm này đã tồn tại !";
$l_warn_delete = "Tài nguyên đã được gán trong nhóm này";
$l_system_no_priv = "Một nhóm hệ thống không thể trở thành riêng tư!";
$l_only_owner_priv = "Chỉ có chủ sở hữu nhóm có thể thiết lập một nhóm riêng!";
$l_add_resource = "Thêm tài nguyên";
$l_add_resourcegroup = "Thêm nhóm (trong danh sách các nhóm có thể)";
$l_del_resource_sel = "Loại bỏ các nguồn tài nguyên này";
$l_del_resourcegroup_sel = "Xóa nhóm"; 
$l_resource_added = "Đã thêm tài nguyên"; 
$l_resource_removed = "Đã bỏ tài nguyên "; 
$l_resourcegroup_added = "Đã thêm nhóm"; 
$l_resourcegroup_removed = "Đa loại bỏ nhóm  "; 
$l_no_display = "Điền vào các lĩnh vực tìm kiếm và nhấn <Tìm> để lấy các nhóm";
$l_no_resource = "Không có tài nguyên đã đăng ký.";
$l_no_resourcegroup_resourcegroup = "Không có nhóm đã đăng ký. "; 
$l_found = "Nhóm đã tìm thấy.";
$l_resource_member = "Tài nguyên đã đăng ký.";
$l_resourcegroup_member = "Nhóm đã đăng ký.";
$l_no_found = "Không có nhóm phù hợp với truy vấn đã được tìm thấy!"; 
$l_add_resource = "Thêm tài nguyên";
$l_add_group = "Thêm nhóm (vào các nhóm có thể)";
$l_del_resource_sel = "Loại bỏ các nguồn tài nguyên này";
$l_del_group_sel = "Loại bỏ các nhóm này";
$l_resource_added = "Đã thêm tài nguyên";
$l_resource_removed = "Đã loại bỏ tài nguyên";
$l_group_added = "Đã thêm nhóm";
$l_group_removed = "Đã bỏ nhóm";
$l_no_resource_added = "Không có người dùng để thêm";
$l_no_resource_deleted = "Không có người sử dụng để loại bỏ";
$l_no_group_added = "Không có nhóm để thêm";
$l_no_group_deleted = "Không có nhóm để loại bỏ";
$l_check_samegroup = "Các nhóm này có vẻ giống với nhóm đã được điền";
$l_cant_delete_system = "Không thể xóa nhóm hệ thống!"; 
$l_cant_delete_public = "Chỉ có người tạo có thể xóa nhóm này!";
$l_add_resourcegroup = "Thêm nhóm";
$l_email_exist = "Địa chỉ email đã được sử dụng"; 
$l_no_resourcegroup_added = "Không có nhóm được thêm"; 
$l_j_check_email = "Địa chỉ email không hợp lệ!"; 
$l_no_resourcegroup_deleted = "Không có nhóm để xóa"; 
$l_check_sameresourcegroup = "Các nhóm này có vẻ giống với nhóm đã gửi"; 

