<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng việt                                               //
//     - File     : user.inc                                                 //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_desc  = "Mô tả";
$l_qty  = "Số lượng";
$l_check_resourcecreate = " Mục thuộc sở hữu của người dùng này.";
$l_check_resourceupdate = " Mục được cập nhật mới nhất của người dùng này.";
$l_no_resource = "Không có trường dữ liệu trong bảng này";
$l_fill_name = "Bạn phải điền tên trước khi gửi.";
$l_rtype = "Loại dữ liệu";
$l_rtype_manage = "Quản lý loại dữ liệu";
$l_rtype_property = "Tài sản";
$l_rtype_kind = "Loại";
$l_rtype_insert = "Tạo loại dữ liệu";
$l_rtype_update = "Cập nhật loại dữ liệu";
$l_rtype_checkdelete = "Kiểm tra hoặc xóa loại dữ liệu";
$l_ritem = "Mục";
$l_ritem_add = "Thêm mục";
$l_ritem_manage = "Quản lý mục";
$l_ritem_insert = "Tạo mục";
$l_ritem_update = "Cập nhật mục";
$l_no_item_available = "Không có mục có sẵn cho dữ liệu này";
$l_confirm_delete_item = "Bạn có thực sự muốn xóa mục này không ?";
$l_resource = "Nguồn dữ liệu";
$l_resources = "Nguồn dữ liệu";
$l_users = "Người dùng";
$l_insert = "Tạo nguồn dữ liệu";
$l_update = "Cập nhật nguồn dữ liệu";
$l_checkdelete = "Kiểm tra hoặc Xóa nguồn";
$l_reset = "Thiết lập lại ưu tiên dữ liệu theo mặc định";
$l_delete = "Xóa nguồn";
$l_add = "Thêm các nguồn dữ liệu này";
$l_no_display = "Điền vào các mục tìm kiếm và nhấn <Tìm> để lấy nguồn dữ liệu";
$l_found = "dữ liệu được tìm thấy.";
$l_no_found = "Không có nguồn dữ liệu phù hợp với yêu cầu!";
$l_cant_delete = "Nguồn dữ liệu không thể bị xóa !";
$l_can_delete = "Nguồn dữ liệu có thể bị xóa.";
$l_check_sameuser = "Những dữ liệu này có vẻ giống với mục vừa nhập !";
$l_exist_error = "Tên này đã tồn tại!";
$l_add_resources = "Thêm nguồn lực";
$l_j_check_number = "Số lượng không hợp lệ.";
$l_j_create_type_first = "Bạn phải tạo loại dữ liệu trước khi tạo mục!";
$l_resource_display = "Hiển thị tùy chọn cho danh sách nguồn dữ liệu";
$l_toggle_public_access = "Điều này sẽ cho phép tất cả mọi người đặt hẹn cho dữ liệu này. Bạn có muốn tiếp tục không ?";
$l_toggle_public_read = "Điều này sẽ cho phép tất cả mọi người xem lịch của nguồn dữ liệu này. Bạn có muốn tiếp tục không ?";
$l_toggle_public_write = "Điều này sẽ cho phép tất cả mọi người có thể cập nhật, chấp nhận và từ chối đặt hẹn cho dữ liệu này. Bạn có muốn tiếp tục không ?";
$l_toggle_public_admin = "Điều này sẽ cho phép tất cả mọi người cập nhật các dữ liệu này. Bạn có muốn tiếp tục không?";
$l_check_samename = "Những dữ liệu này có tên tương tự như mục vừa nhập!";
$l_name_error = "Bạn phải nhập tên!";
