<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Tiếng việt                                                  //
//     - File     : settings.inc                                             //
// 1999-03-18 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_cur_settings = "Thiết lập hiện tại của bạn";
$l_auto_display = "Hiển thị danh sách tự động";
$l_submit = "Xác nhận";
$l_cur_lang = "Ngôn ngữ hiện tại của bạn";
$l_cur_theme = "Chủ đề hiện tại của bạn";
$l_new_settings = "Để thay đổi thiết lập của bạn, hãy chọn ở đây các thông số mới";
$l_set_lang = "Chọn ngôn ngữ của bạn";
$l_set_theme = "Chọn chủ đề của bạn";
$l_set_menu = "Hiển thị menu";
$l_set_rows = "#Hàng trên mỗi trang";
$l_set_todo = "Sắp xếp thứ tự các nhiệm vụ cần làm";
$l_set_date_upd = "Định dạng ngày vào";
$l_set_date = "Định dạng ngày";
$l_set_commentorder = "Hiển thị bình luận";
$l_set_display_days = "Lịch hiển thị các ngày trong tuần ";
$l_set_cal_interval = "Khoảng thời gian  trong lịch";
$l_set_cal_first_hour = "Giờ bắt đầu trong Lịch";
$l_set_cal_last_hour = "Giờ kết thúc trong Lịch";
$l_set_cal_alert = "Nhắc nhở lịch (phút)";
$l_set_csv_sep = "Dấu phân cách CSV";
$l_set_debug = "Mức Debugging";
$l_send_mail = "Chấp nhận email mời họp";
$l_send_mail_participation = "Chấp nhận email tham gia cuộc họp";

$l_update_ok = "Cài đặt cập nhật thành công";

$l_da_iso = "yyyy-mm-dd";
$l_da_en = "mm/dd/yyyy";
$l_da_fr = "dd/mm/yyyy";
$l_da_txt = "dd tháng yyyy";

$l_da_dmy = "dmy";
$l_da_mdy = "mdy";

$l_deadline = "Hạn cuối";

$l_me_txt = "Văn bản";
$l_me_ico = "icon";
$l_me_both = "văn bản+icon";

$l_co_chro = "Theo thứ tự thời gian";
$l_co_rev = "Đảo ngược";

$l_csvd_sc = ";";
$l_csvd_tab = "tab";
$l_with_weekend = "Bao gồm cuối tuần";
$l_without_weekend = "Không bao gồm cuối tuần";
$l_set_public_fb = "Công khai thông tin rảnh / bận rộn của bạn";

$l_set_topbar = "Kích hoạt thanh công cụ OBM Topbar.";
$l_browser_notification = "Thêm một máy tính để bàn thông báo popup cho các sự kiện và mail (không tương thích Internet Explorer)";
