<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                  //
//     - File     : account.inc                                              //
// 2002-08-01 Augusto Fagioli - augusto@fagioli.biz                          //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Labels et textes
$l_label_start = "Inizio Etichetta";
$l_bank = "Banca";
$l_balance = "Saldo";
$l_initial_balance = "Creazione Saldo";
$l_choose_balance_date = "Data Saldo";
$l_expected_date = "Data Prevista";
$l_amount = "Totale";

$l_include_expected = "Inserisci le operazioni richieste?";
$l_in_total ="Nel  Totale";
$l_out_total = " Totale Fuori ";
$l_total ="Saldo Previsto ";
$l_old_balance = "Saldo odierno";
$l_nb_expected_used = " operazioni previste per il calcolo.";
$l_expected = "previsto";
$l_used_payments = "Pagamenti Considerati nel conteggio del saldo ";
$l_used_expected_payments = "Pagameni previsti usati nel calcolo del saldo";

// Actions
$l_insert= "Inserisci Account";
$l_update = "Aggiorna Account";
$l_delete = "Cancella Account";
$l_delete_confirm = "Confermi l'eliminazione dell'account ?";
$l_compute_balance = "Elabora Saldo";

// Messages
$l_no_display = "Riempi i campi di ricerca e premi  < Trova > per ricevere gli account";
$l_found="Account trovati.";
$l_no_found="Non sono presenti corrispondenze per gli account cercati ";
$l_delete_ok = "Account eliminato .";
$l_delete_error = "Eliminazione Account Fallita !";
$l_insert_ok = "Account inserito .";
$l_insert_error = "Inserimento account Fallito  !";
$l_update_ok = "Account Aggiornato .";
$l_update_error = "Aggiornamento account fallito !";
$l_query_error = "Problemi nell'esecuzione della ricerca...";
$l_impossible_deletion = " alcuni pagamenti sono associati a questo account. Impossibile cancellare";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$lj_check_number = "\\nNumero account non valido ! ";
$lj_fill_number = " Inserisci prima il numero ! ";
$lj_fill_bank = "Inserisci prima la Banca !";
$lj_confirm_no_bank="Questo accoutn non è associato a banche. Click OK per confermare.";

// For the display parameters modification screen
$l_account_options = "Visualizza le opzioni per la lista di account ";
$l_payment_options = "Visualizza le opzioni per la lista di pagamenti ";
