<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italiano                                                 //
//     - File     : company.inc                                              //
// 2002-08-01 Augusto Fagioli                                                //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_number = "Numero";
$l_aka = "Altri nome";
$l_company_name = "Nome Azienda";
$l_kind = "Tipo";
$l_market = "Person in charge";
$l_activity = "Attività";
$l_company_kind = "Tipo Azienda";
$l_country = "Nazione";
$l_fax = "Fax";
$l_web = "Web";
$l_email = "E-Mail";

// Labels and texts
$l_contact_new = "Nuovo Contatto";
$l_deal_new = "Nuovo Deal";
$l_project_new = "Nuovo Projet";
$l_contract_new = "Nuovo Contratto";
$l_kind_manage = "Tipo Gestione Azienda";
$l_kind_exist = "Tipi esistente";
$l_kind_new = "Nuovo Tipo";
$l_act_manage = "Attività Gestione Azienda";
$l_act_exist = "Attività esistente";
$l_act_new = "Nuova Attività";
$l_internal = "Interno";

// Titres
$l_company = "Azienda";

// Actions
$l_insert = "Inserisci Azienda";
$l_update = "Aggiorna Azienda";
$l_checkdelete = "Controlla o Elimina Azienda";
$l_delete = "Elimina Azienda";
$l_kind_update = "Aggiorna Tipo";
$l_kind_checkdelete = "Controlla o Elimina Tipo";
$l_kind_delete = "Elimina Tipo";
$l_kind_insert = "Inserisci Tipo";
$l_act_update = "Aggiorna Attività";
$l_act_checkdelete = "Controlla o Elimina Attività";
$l_act_delete = "Elimina Attività";
$l_act_insert = "Inserisci Attività";
$l_select_company = "Seleziona Azienda";

// Messages
$l_err_act_empty = "Scrivi azienda attività";

$l_no_display = "Riempi i  campi  e premi < Trova> per la ricerca";
$l_found = "Aziende Trovate.";
$l_no_found = "Nessuna  Azienda trovata !";
$l_delete_ok = "Azienda eliminata .";
$l_delete_error = " Eliminazione Azienda fallita !";
$l_insert_ok = " Azienda inserita .";
$l_insert_error = "Inserimento Azienda fallito !";
$l_check_samecompany = "Queste Aziende sembra simili alla nuova ...";
$l_update_ok = "Azienda modificata.";
$l_update_error = "Modifica Azienda Fallita !";
$l_query_error = "Errore critico nell'esecuzione della query.";
$l_link_contact = "Questi contatti sono di questa Azienda";
$l_link_contact_no = "l' Azienda non ha contatti";
$l_link_deal = "l'Azienda ha degli impegni";
$l_link_deal_no = "l'Azienda non ha degli impegni";
$l_link_contract = "l'Azienda ha degli contratti";
$l_link_contract_no = "l'Azienda non ha degli contratti";
$l_link_project = "l'Azienda ha dei progetti";
$l_link_project_no = "l'Azienda non ha degli progetti";
$l_cant_delete = "Azienda non eliminabile !";
$l_can_delete = "Azienda eliminabile !";
$l_kind_insert_ok = "Tipo inserito.";
$l_kind_insert_error = "Inserimento tipo fallito !";
$l_kind_delete_ok = "Tipo eliminato.";
$l_kind_delete_error = "Eliminazione tipo fallita !";
$l_kind_update_ok = "Tipo modificato.";
$l_kind_update_error = "Modifica tipo fallito !";
$l_kind_link_company = " Aziende legate a  ";
$l_kind_link_company_no = "Azienda non legata";
$l_kind_cant_delete = "Tipo non eliminabile.";
$l_kind_can_delete = "Tipo eliminabile.";
$l_act_insert_ok = "Attività inserita.";
$l_act_insert_error = "Inserimento attività fallito !";
$l_act_delete_ok = "Attività eliminata.";
$l_act_delete_error = "Eliminazione attività fallita !";
$l_act_update_ok = "Attività modificata.";
$l_act_update_error = "Modifica Attività fallito !";
$l_act_link_company = " Aziende legate a  ";
$l_act_link_company_no = "Azienda non legata";
$l_act_cant_delete = "Attività non eliminabile.";
$l_act_can_delete = "Attività eliminabile.";

// Java Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_delete_confirm = "Conferma eliminazione  Azienda ?";
$l_fill_name = "Inserisci prima il Nome .";
$l_j_check_zip = "CAP  non valido.";
$l_j_check_phone = "Telefono non  valido.";
$l_j_check_fax = "Fax non  valido.";
$l_j_check_email = " Indirizzo Email non  valido.";
$l_j_check_web = " Indirizzo  Web non  valido.";
$l_j_kind_delete = "Scegli un tipo da controllare o eliminare !";
$l_j_kind_update = "Scegli un tipo e inserisci il nuovo nome per la modifica !";
$l_j_kind_create = "Inserisci nuovo tipo per crearlo  !";
$l_j_act_delete = "Scegli una Attività da controllare o eliminare !";
$l_j_act_update = "Scegli una Attività e inserisci il nuovo nome per la modifica !";
$l_j_act_create = "Inserisci nuova Attività per crearla !";
$l_j_select_company = "Scegli Azienda !";

// For the display parameters modification screen
$l_company_display = "Mostra opzioni lista Aziende";

</script>
