<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                 //
//     - File     : computer.inc                                            //
// 05-08-2002 Augusto FAgioli                                               //
//////////////////////////////////////////////////////////////////////////////
$l_compu_name = "Nome  macchina" ;
$l_compu_domain_name = "Nome del dominio" ;
$l_compu_ip = "Indirizzo ip della macchina" ;
$l_compu_user = "Utilizzatore della macchina" ;
$l_compu_comments = "Note" ;
$l_compu_date_lastscan = "Data ultimo scan" ;
$l_compu_auth_userscan = "Autorizza utente per scansione" ;
$l_compu_creator = "Creazione del....'ordinateur" ;
$l_compu_datecreation = "Data creazione" ;
$l_compu_lastupdater = "Ultimo pezzo sostitutito" ;
$l_compu_date_lastupdate = "Data ultima sostituzione" ;

$l_last_deal = "Ultimo  affaire";
$l_last_contact = "ultimo contatto";
$l_last_company = "ultima società";

//Options;
$l_compu_option = "Opzioni d'affichage des ordinateurs" ;
$l_services_option = "Opzioni d'affichage dei servizi" ;

//Services:
$l_port_service_name = "Nome servizio" ;
$l_port_service_port = "Porta servizio" ;
$l_port_service_proto = "Protocollo serviozio" ;
$l_port_service_desc = "Descrizione servizio" ;
$l_port_service_status = "Status servizio" ;

$l_port_del = "Elimina" ;
$l_port_add = "Aggiungi" ;
$l_port_add2 = "Aggiungi i servizi selezionati" ;
$l_port_del = "Enlever le porte selezionate" ;
$l_port_num = "Nome porta aggiunta :" ;
$l_should_scan = "Clik 'Scan delle porte' per rilevazione." ;
$l_port_found = " Servizi(o) scan(s)" ;


$l_query_display = "Affiché" ;
$l_order_dis = "Ordine d'affichage" ;
$l_action = "Azione" ;
$l_ch_to_dis_no = "Non afficher questo campo" ;
$l_ch_to_dis_no_help = "Il campo è stato affiché<br>Clik sull'icona se vous ne souhaitez afficher pas questo campo" ;
$l_ch_to_dis_yes = "Afficher questo campoo" ;
$l_ch_to_dis_yes_help = "Il campo non è <br>Clik sull'icone paer souhaitez afficher questo campo" ;
$l_dis_obligatory = "L'affichage del campo obbligatoria" ;
$l_dis_obligatory_help = "Questa icona significa che è obbligatorio d'afficher questo campo" ;
$l_down_option = "Scalare  l'optione di una tacca" ;
$l_down_option_help  = "Clik sull'icona scalare il campo di una tacca" ;
$l_up_option = "Monter cette option d'un tacca" ;
$l_up_option_help = "Clik sull'icona pour monter il campo di una tacca" ;
$l_subject = "Oggetto" ;

$l_services_found = " servizi trovati  à ajouter" ;

$l_save_compu = "Enregistrer l'ordionateur" ;
$l_update_compu = "Mettre à jour l'ordinateur";
$l_ip_novalid = "L'Indirizzo ip è già occupato" ;
$l_domain_name_novalid = "Nome dominio già occupato" ;
$l_compu_name_short = "Nome" ;
$l_compu_domain_short = "dominio" ;
$l_compu_user_short = "Utente" ;
$l_compu_ip_short = "Indirizzo ip" ;
$l_find = "Cerca" ;
$l_no_display = "Renseigner les crit&egrave;res souhait&eacute;s et cliquer sur < Chercher > pour obtenir les ordinateurs correspondants.";
$l_no_compu = "Nessun ordinateur corrisponde ai criteri." ;
$l_compu_found = "Ordinateurs trovato" ;


$l_compu_ip_ok = "L'Indirizzo ip ha risposto al ping" ;
$l_compu_ip_no = "L'Indirizzo ip irraggiungibile" ;
$l_compu_ip_diff = "L'Indirizzo ip correspondant al nome di dominio è : " ;
$l_compu_data = "Données sur l'ordinateur" ;
$l_compu_status = "Status" ;
$l_compu_name_ok = "Nome macchina + Nome dominio è valido con questo ip" ;
$l_compu_name_ok2 = "Nome macchina + Nome dominio è valido con ip indicato  au dessus" ;
$l_compu_name_ok_notip = "Nome macchina + Nome dominio è valido .<br>
                          L'ip correspondente a questa macchina è  : " ;
$l_compu_name_no = "Nome macchina + Nome dominio non  corrispond e all'ip" ;
$l_compu_name_no2 = "Nome macchina + Nome de dominio non risponde" ;
$l_compu_name_no_res = "Le serveur n'arrive pas à résoudre cette ip en Nome. <br>Vérifier le serveur DNS." ;
$l_compu_name_else = "Le serveur à résoulu un autre Nome pour cette Indirizzo ip : " ;
$l_compu_should_chg = "Vous devriez modifier les informations sur l'ordinateur, comme conseillé." ;
$l_compu_test_compu = "Vous devriez tester si l'ordinateur est bien branché. <br>Sinon toutes les informations réseaux sur cette macchina sont érronées." ;


//Action
$l_compu_compu = "Richiedente" ;
$l_compu_infos = "Informazioni sul richiedente" ;
$l_compu_verify = "Verificare le informazioni" ;
$l_dis_choice = "Scelta d'affichage" ;
$l_add_port = "aggiunta porte" ;
$l_del_port = "Enlever le porte" ;
$l_update_port = "Scan delle porte" ;
$l_modify_compu = "Modifica richiedente" ;
$l_del_compu = "Eliminare il richiedente" ;

//Computer options

// Champs specifiques
// Format de Data et heure pour MySQL pour affichage dans ecran detail affaire
// Specifics fields
// MySQL Data and time format for display in the deal detail screen
$l_time_format = "%d-%m-%Y %H:%i";
$l_date_format = "%d-%m-%Y %H:%i";
