<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italiano                                                 //
//     - File     : contact.inc                                              //
// 1999-01-24 Augusto Fagili                                                 //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_company = "Azienda";
$l_lastname = "Cognome";
$l_firstname = "Nome";
$l_kind = "Tipo";
$l_function = "Funzione";
$l_phone = "Tel.";
$l_hphone = "Tel. Casa";
$l_minihphone = "(casa)";
$l_mphone = "Cell.";
$l_minimphone = "(minitel)";
$l_email = "E-Mail";
$l_mailing_ok = "Mailing enabled";
$l_fax = "Fax";
$l_address = "Indirizzo";
$l_postcode = "ZIP";
$l_expresspostal = "CAP";
$l_town = "Città";
$l_country = "Nazione";
$l_visibility ="Accesso";

// Labels and texts
$l_contact_name = "Nome Contatto";
$l_from_company = "Azienda";
$l_telother = "Altro Tel";
$l_private = "Privato";
$l_public = "Pubblico";
$l_contact_select_company = "Scegli l'azienda per il contatto.";

// Titles
$l_contact = "Contatto";

// Actions
$l_insert = "Inserisci Contatto ";
$l_update = "Modifica Contatto";
$l_checkdelete = "Controlla o elimina il Contatto";
$l_delete = "Elimina il ";
$l_add = "Aggiungi i contatti";

// Messages
$l_check_samecontact = "Quasti contatti sembrano simili al nuovo  !";
$l_link_deal = "Qusto contatto ha deals in corso";
$l_link_deal_no = "Il contatto non ha ";
$l_link_list = "Il contatto è registrato in queste liste";
$l_link_list_no = "Il Contatto non è registrato in nessuna lista";
$l_cant_delete = "Il contatto non può essere eliminato!";
$l_can_delete = "Il contatto può essere eliminato.";
$l_no_display = "Riempi i campi e click <TROVA> per eseguire la ricerca";
$l_found = "contatti trovati.";
$l_no_found = "Non sono stato trovati contatti !";
$l_delete_ok = "Contatto eliminato.";
$l_delete_error = "Eliminazione contatto fallita!";
$l_insert_ok = "Contatto inserito .";
$l_insert_error = "Inserimento contatto fallito!";
$l_update_ok = "Contatto modificato .";
$l_update_error = "Modifica contatto fallita !";
$l_query_error = "Errore durate la ricerca";

// JavaScript Messages (specials charcaters must be escaped whith \ -> \\)
$l_fill_lastname = "Inserisci prima il Cognome.";
$l_fill_company = "Scegli prima una Azienda.";
$l_fill_phone = "Scrivi prima il telefono.";
$l_delete_confirm = "Confermi eliminazione contatto ?";
$l_j_select_company =  "Seleziona una azienda!";
$l_j_check_phone = "Numero telefono non valido.";
$l_j_check_hphone = "Numero telefono privato non valido.";
$l_j_check_mphone = "Numero cellulare non valido.";
$l_j_check_fax = "Numero fax non valido.";
$l_j_check_email = "Indirizzo email non valido.";

// For the display parameters modification screen
$l_contact_display = "Opzioni visualizzazine della lista contatti";
