<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                  //
//     - File     : group.inc                                                //
// 2003-09-01 Pierre Baudracco - Augusto Fagioli                             //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

$l_group = "Gruppo";

// Database fields
$l_system = "Sistema";
$l_desc = "Descrizione";
$l_email = "E-mail";
$l_creator = "Creatore";
$l_date_creation = "Creazione";
$l_updater = "Aggiornato da ";
$l_date_last_update = "Ultima modifica";

// Labels et textes
$l_nb_user = "# Utenti";
$l_group_user = "con utente:";
$l_group_display = "Mostra opzioni per le liste dei gruppi";
$l_user_display = "Mostra opzioni per liste di utenti";
$l_desc = "Descrizione";

// Contact
$l_lastname = "Cognome";
$l_firstname = "Nome";
$l_function = "Funzione";

// Actions
$l_insert = "Inserisci Gruppo";
$l_update = "Aggiorna  Gruppo";
$l_delete = "Elimina Gruppo";
$l_add = "Aggiungi questi  Gruppi";

// Messages
$l_insert_ok = "Gruppo inserito.";
$l_insert_error = "Creazione Gruppo non riuscita";
$l_update_ok = "The Gruppo modificato";
$l_update_error = "Modifica Gruppo non riuscita";
$l_delete_ok = "Gruppo eliminato ";
$l_delete_error = "Eliminazione Gruppo non riuscita";
$l_fill_name = "YInserisci nome del gruppo";
$l_group_exists = "Il Gruppo già esiste";
$l_j_check_email = "indirizzo email non valido";
$l_warn_delete = "Utenti registrati nel Gruppo";
$l_email_exist = "email già in uso";

$l_no_display = "Riepi i campi di ricerca e premi  < TROVA > per l'elenco dei Gruppi";
$l_no_user = "Utenti non registrati";
$l_no_group_group = "Non esistono gruppi";
$l_found = "Gruppi trovati";
$l_user_member = "utenti registrati ";
$l_group_member = "Gruppi registrati ";
$l_no_found = "Non sono stati trovati Gruppi";
$l_add_user = "Aggiungi Utenti";
$l_add_group = "Aggiungi Gruppi (entro i possibili Gruppi)";
$l_del_user_sel = "Elimina questi utenti ";
$l_del_group_sel = "Elimina questi gruppi";
$l_user_added = "Utenti aggiunti ";
$l_user_removed = "Utenti eliminati";
$l_group_added = "Gruppi Aggiunti ";
$l_group_removed = "Gruppi eliminati";
$l_no_user_added = "Nessun utente da aggiungere";
$l_no_user_deleted = "Nessun utente da eliminare";
$l_no_group_added = "Nessun gruppo da aggiungere";
$l_no_group_deleted = "Nessun gruppo da eliminare";
$l_check_samegroup = "Questi Gruppi sono simili ai gruppi selezionati ";

</SCRIPT>