<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                  //
//     - File     : group.inc                                                //
// 2003-09-01 Pierre Baudracco - Augusto Fagioli                             //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T17:44:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T10:25:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T10:28:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T10:35:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T10:37:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T10:37:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T10:47:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T10:59:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:03:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:15:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:18:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:18:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:21:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:24:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:25:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:29:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:29:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:35:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:46:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:47:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:48:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:48:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:48:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:49:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:50:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:50:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:51:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:52:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:53:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:54:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:56:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:57:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:58:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:58:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:59:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:59:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:00:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:01:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:01:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:02:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:02:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:03:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:04:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:05:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:07:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:07:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:08:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:10:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:10:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:10:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:11:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:12:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:13:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:14:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:15:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:15:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:16:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:16:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:17:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:19:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:19:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:20:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:20:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:22:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:22:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:23:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:25:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:26:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:28:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:30:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:33:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:15:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:17:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:20:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:23:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:25:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:30:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:32:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:32:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:37:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:40:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:41:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:45:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:51:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:53:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:55:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:02:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:12:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:14:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:17:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:22:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:22:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:26:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:26:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:27:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:44:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:46:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:59:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:01:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:08:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:27:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:31:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:09:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:27:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:27:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:46:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:22:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:45:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:45:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:47:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:49:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:01:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:02:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:05:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:06:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:10:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:14:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:15:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:16:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:17:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:18:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:21:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:21:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:23:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:24:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:25:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:30:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:32:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:34:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:35:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:37:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:37:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:39:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:43:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:54:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:54:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:55:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:55:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:57:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:57:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:58:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:58:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:59:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:00:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:03:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:06:26+02:00 using OBMtranslation (0.4.1)

$l_system = "Sistema";
$l_nb_user = "# Utenti";
$l_group_user = "Utente:";
$l_group_display = "Opzioni visualizzazione dell'elenco gruppi"; 
$l_user_display = "Opzioni visualizzazione elenco utenti.";
$l_lastname = "Cognome";
$l_firstname = "Nome";
$l_function = "Funzione";
$l_insert = "Inserisci Gruppo";
$l_update = "Aggiorna Gruppo";
$l_delete = "Elimina Gruppo";
$l_add = "Aggiungi questi Gruppi";
$l_fill_name = "Inserisci il nome del gruppo.";
$l_group_exists = "Il Gruppo esiste già!"; 
$l_j_check_email = "Indirizzo email non valido!";
$l_warn_delete = "Utenti registrati nel Gruppo";
$l_email_exist = "Email già in uso!";
$l_no_display = "Riepi i campi di ricerca e premi < CERCA > per ottenere l'elenco dei Gruppi.";
$l_no_user = "Utenti non registrati";
$l_no_group_group = "Non esistono gruppi";
$l_found = "Gruppi trovati";
$l_user_member = "utenti registrati ";
$l_group_member = "Gruppi registrati ";
$l_no_found = "Non sono stati trovati Gruppi!";
$l_add_user = "Aggiungi Utenti";
$l_add_group = "Aggiungi Gruppi (entro i possibili Gruppi)";
$l_del_user_sel = "Elimina questi utenti";
$l_del_group_sel = "Elimina questi gruppi";
$l_user_added = "Utente(i) aggiunto(i) ";
$l_user_removed = "Utente(i) eliminato(i)";
$l_group_added = "Gruppo(i) Aggiunto(i) ";
$l_group_removed = "Gruppo(i) eliminato(i)";
$l_no_user_added = "Nessun utente da aggiungere";
$l_no_user_deleted = "Nessun utente da eliminare";
$l_no_group_added = "Nessun gruppo da aggiungere";
$l_no_group_deleted = "Nessun gruppo da eliminare";
$l_check_samegroup = "Questi Gruppi sono simili al gruppo selezionato. Confirmi la creazione di questo gruppo?";
$l_cant_delete_system = "I gruppi sistema non possono essere eliminati!";
$l_contacts = "Membri esterni";
$l_mailing = "Mailing list";
$l_err_system_samba = "La modifica dei permessi di un gruppo sistema windows non è autorizzata.";
$l_cant_delete_domain_group = "I gruppi di dominio sono gestiti automaticamente da OBM e non possono essere eliminati.";
$l_cant_update_domain_group = "I gruppi di domino predefiniti sono gestiti automaticamente da OBM e non possono essere modificati."; 
$l_add_groups = "Aggiungi gruppi";
$l_only_owner_priv = "Solo il proprietario del gruppo lo può definire privato!";
$l_cant_delete = "Il gruppo non può essere eliminato!";
$l_warn_group_diff_privacy = "Alcuni gruppi non sono stati aggiunti. Hai provato di aggiungere dei gruppi privati nel gruppo pubblico!";
$l_smb = "Windows";
$l_err_private_email = "I gruppi privati non possono avere indirizzo Email!";
$l_groupname_error = "Nome gruppo scorretto!";
$l_system_no_priv = "Un gruppo sistema non può essere privato!";
$l_can_delete = "Il gruppo può essere eliminato.";
$l_err_cant_delete_default_user_group = "Il gruppo predefinito degli utenti, non può essere eliminato!"; 

