<script language="php">
////////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                    //
//     - File     : import.inc                                                //
// 2009-09-11     : Cristina Grigore                                         //
////////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T17:44:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:22:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T09:01:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:04:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:05:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:07:56+02:00 using OBMtranslation (0.4.1)

$l_result = "Risultato";
$l_update = "Modifica";
$l_comp_insert = "Inserisci azienda";
$l_similar_company = "Azienda simile";
$l_csvd_tab = "tab";
$l_auto_resolv = "Risoluzione automatica dei conflitti dell'azienda.";
$l_always_ask = "Chiedi sempre cosa fare in caso di conflitto.";
$l_always_do_nothing = "Non fare mai niente se l'azienda è considerata identica.";
$l_conflict = "Conflitto";
$l_mailing_ok_msg = "'X', '1', 'Y' per posta attiva";
$l_delete = "Elimina";
$l_invalid_rows = "Righe invalide";
$l_format = "Formato";
$l_csv_sep = "Separatore CSV";
$l_enclosed = "Campi chiusi da";
$l_mapping = "Corrispondenza campi";
$l_field_num = "# campo";
$l_default = "Valore di default";
$l_lines_processed = "Righe elaborate";
$l_similar_contact = "Contatto simile";
$l_always_update_similar = "Aggiorna sempre se solo un'azienda è considerata identica o simile.";
$l_comp_update = "Modifica un'azienda esistente";
$l_con_insert = "Inserisci un contatto";
$l_import_end = "Import finito";
$l_conflict_detected = "Conflitto rilevato";
$l_found = "Trovato";
$l_contact_defaultname = "Contatto senza Nome";
$l_con_nothing = "Tieni il contatto corrente";
$l_invalid_row = "Riga non valida!";
$l_no_found = "Nessun import trovato!";
$l_fill_name = "Il nome dell'Import deve essere riempito!";
$l_used_company = "Azienda utilizzata";
$l_always_update_same = "Aggiorna sempre se l'azienda è considerata identica.";
$l_nb_insert = "Inserimenti";
$l_warn_delete = "Conferma eliminazione import?";
$l_field = "Campo";
$l_insert = "Inserisci l'import";
$l_test_file = "Testare il file";
$l_con_update = "Modifica il contatto esistente";
$l_name_import_nomatch = "Nome import non valido!";
$l_check_sameimport = "Questi import sembrano simili al nuovo inserito!";
$l_no_display = "Riempi i campi di ricerca e premi  < Cerca > per ottenere l'elenco degli import.";
$l_same_company = "Lo strumento di import stima che questa azienda e quella importata sono identiche.";
$l_import = "Import"; 
$l_sample_file = "Verifica con file di esempio"; 
$l_conflict_rows = "Righe in conflitto";
$l_csvd_sc = ";";
$l_info = "Informazione"; 
$l_nb_update = "aggiornamenti"; 
$l_comp_nothing = "Non modificare"; 
$l_import_exists = "Questo import esiste già!"; 
$l_always_insert = "Crea sempre un'azienda se non esiste un'altra identica."; 
$l_check_file = "Verifica il file"; 
$l_company_defaultname = "Azienda senza Nome"; 

