<script language="php">
////////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                   //
//     - File     : people.inc                                                //
// 2009-09-11     : Cristina Grigore                                         //
////////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T17:44:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T16:13:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T16:18:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T16:22:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T16:22:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T16:36:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:02:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:13:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:23:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:32:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:36:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:38:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:52:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:53:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:54:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T17:56:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T18:03:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T18:09:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-14T18:10:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:12:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:13:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:14:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:15:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:15:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:16:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:16:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:17:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:19:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:19:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:20:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:20:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:22:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:22:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:23:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:25:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:26:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:28:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:30:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:33:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:15:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:17:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:20:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:23:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:25:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:26:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:30:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:32:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:32:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:37:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:40:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:41:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:45:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:51:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:53:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:55:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:02:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:12:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:14:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:17:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:22:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:22:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:26:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:26:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:27:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:44:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:46:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:59:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:01:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:08:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:27:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:31:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:09:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:27:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:27:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:46:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:22:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:33:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:34:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:35:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:35:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:37:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:39:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:40:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:40:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:42:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:42:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:45:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:45:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:47:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:47:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:49:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:50:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:51:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:54:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:54:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:56:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:56:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:57:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:58:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:59:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T10:59:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:00:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:01:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:02:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:03:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:05:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:06:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:06:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:10:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:10:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:13:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:15:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:18:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:20:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:20:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:22:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:22:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:23:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:24:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:27:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:28:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:30:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:31:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:32:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:33:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:34:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:35:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:36:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:36:33+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:37:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:37:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:38:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:39:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:40:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:41:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:42:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:42:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:45:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:45:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:47:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T11:49:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:01:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:02:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:05:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:06:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:10:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:14:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:15:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:16:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:17:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:18:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:21:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:21:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:23:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:24:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:25:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:30:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:32:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:34:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:35:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:37:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:37:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:39:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:43:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:54:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:54:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:55:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:55:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:57:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:57:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:58:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:58:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:59:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:00:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:03:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:06:25+02:00 using OBMtranslation (0.4.1)

$l_delegation = "Delega";
$l_perms = "Permessi";
$l_j_check_email = "Indirizzo email non valido. Controlla il dominio.";
$l_lname_error = "Il nome deve essere riempito correttamente!";
$l_password = "Password";
$l_login_in_use = "L'username è stato attribuito ad un'altro utente!";
$l_exp = "Giorni prima della scadenza ";
$l_email_error = "L'indirizzo email inserito non è valido";
$l_uemail_exist = "L'indirizzo email è stato inserito più volte!";
$l_login = "Username"; 
$l_password_error = "La password non è valida: da 4 a 12 caratteri (alfanumerici o -\$\&~#{([|_`^@);]+=}%!:/.,?<>\)!";
$l_found = "utenti trovati";
$l_account_dateexp = "Scadenza";
$l_perms_editor = "Editore";
$l_update_group = "Modificare i gruppi di utenti";
$l_image_size_error = "La foto non deve superare 96px x 96px e non deve essere superiore a 100kb";
$l_perms_admin = "Amministratore";
$l_fax2 = "$l_fax 2";
$l_email_exist = "L'indirizzo email inserito è già utilizzato!";
$l_last_admin_error = "Il profilo dell'ultimo amministratore non può essere modificato!";
$l_cant_delete = "L'utente non può essere eliminato!";
$l_link_timetask = "L'utente è inserito nella gestione di tempo del progetto";
$l_image_type_error = "La foto deve essere un file di tipo immagine (gif, jpeg o png)";
$l_datebegin = "Data di inizio";
$l_email = "Email";
$l_link_timetask_no = "L'utente non è inserito nella gestione tempo del progetto";
$l_group_member = "Membro gruppi";
$l_add_users = "Aggiungere utenti";
$l_insert = "Inserisci utente";
$l_email_empty = "Devi inserire un indirizzo mail per attivare la posta!";
$l_can_delete = "L'utente può essere eliminato.";
$l_vacation = "Assente";
$l_delete_confirm = "Confermi eliminazione utente?";
$l_dateexp = "Scadenza";
$l_forbidden = "Vietato";
$l_infos = "Informazioni";
$l_password_empty = "Inserisci una password valida - da 4 a 12 caratteri (alfanumerici o  -\$\&~#{([|_`^@);]+=}%!:/.,?<>\)!"; 
$l_phone2 = "$l_phone 2";
$l_no_display = "Riempi i campi di ricerca e premi < Cerca > per ottenere l'elenco utenti"; 
$l_check_userupdate = "voci modificate da questo utente.";
$l_fill_password = "Devi inserire la password prima di validare";
$l_change_login_confirm = "Hai modificato il nome di questo utente. E necessario che l'utente sia sconnesso, durante la modifica, di tutte le applicazioni collegate a OBM(OBM, client di posta, webmail, connettore). Confermi la modificazione di username?  "; 
$l_update = "modifica utente";
$l_check_sameuser = "Questi utenti sembrano simili a questo nuovo inserito!";
$l_reset = "Preferenze predefinite";
$l_delegation_target = "Amministrazione delegata";
$l_password_type = "Password cifrata ";
$l_checkdelete = "Verifica o cancella utente";
$l_check_usercreate = "voci create da questo utente.";
$l_err_delegation_target_profile = "Questo profilo utente non può avere la delega di amministratore!";
$l_delete = "Elimina utente";
$l_group = "Gruppo";
$l_people_display = "Opzioni di visualizzazione dell'elenco utenti";
$l_no_user = "Nessun campo utente in questa tabella";
$l_photo = "Foto";
$l_delete_userobmphoto = "Elimina la foto dell'utente";
$l_add = "Aggiungi questi utenti";
$l_noexperie = "Non scade mai";
$l_lastaccess = "Ultimo accesso";
$l_no_found = "Nessun utente non corresponde a questi criteri";
$l_reset_ok = "Le preferenze dell'utente sono state rimesse ai valori predefiniti";
$l_perms_user = "Utente";
$l_err_delegation_target_outside_target = "La delega di amministrazione deve essere inscritta nel tuo target";
$l_err_delegation_target_outside_domain = "La delega di amministrazione deve essere inscritta nel dominio";
$l_login_error = "L'username deve essere correttamente inseritto! Non può essere vuoto o contenere caratteri speciali.";
$l_fill_login = "Devi inserire l'username prima di validare.";
$l_exist_error = "Un altro utente utilizza questo nome!";
$l_profile_privilege_error = "Permessi insufficienti per gestire questo profilo!";

