<script language="php">
////////////////////////////////////////////////////////////////////////////////
// OBM - Language :                                                           //
//     - File     : planning.inc                                              //
// 2009-10-28                                                                 //
////////////////////////////////////////////////////////////////////////////////
// Modified on 2009-10-28T10:03:12+01:00 using OBMtranslation (0.4.1)


// lines below have been created with OBMtranslation (0.4.1) on 2009-10-28T10:03:12+01:00
$l_err_plannedtask_dateend_empty = "Inserisci una data di fine"; 
$l_reporting = "Reportage"; 
$l_overrun = "Superamento"; 
$l_err_plannedtask_user_empty = "Scegli un utente"; 
$l_period = "Periodo"; 
$l_morning = "Mattina"; 
$l_activities_of = "Attivita di"; 
$l_afternoon = "Pomeriggio"; 
$l_err_plannedtask_activity_empty = "Seleziona una attività"; 
$l_err_plannedtask_datebegin_empty = "Inserisci una data di inizio"; 
$l_err_plannedtask_event_in_conflit = "Evento in conflitto "; 
$l_see = "Visualizza"; 
$l_activity = "Attività"; 
$l_entireday = "Tutto il giorno"; 
$l_err_plannedtask_activity_one = "Scegli una sola attività"; 
$l_err_plannedtask_dateinverted = "La data di inizio non può essere posteriore alla data di fine"; 
$l_err_plannedtask_detected_conflict = "Conflitto scoperto: questa persona è occupata durante questo periodo. Visualizza l'evento qui sotto."; 

