<script language="php">
////////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                   //
//     - File     : publication.inc                                           //
// 2009-09-11     : Cristina Grigore                                          //
////////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T17:44:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:15:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:18:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:18:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:21:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:24:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:25:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:29:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:29:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:35:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:46:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:47:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:48:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:48:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:48:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:49:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:50:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:50:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:51:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:52:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:53:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:54:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:56:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:57:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:58:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:58:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:59:23+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T11:59:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:00:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:01:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:01:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:02:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:02:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:03:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:04:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:05:25+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:07:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:07:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:08:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:10:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:10:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:10:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:11:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:12:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:13:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:14:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:15:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:15:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:16:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:16:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:17:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:19:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:19:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:20:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:20:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:21:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:22:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:22:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:23:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:25:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:26:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:27:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:28:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:30:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T12:33:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:15:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:17:27+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:20:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:23:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:25:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:27:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:30:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:32:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:32:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:37:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:40:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:41:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:45:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:51:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:53:32+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T14:55:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:02:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:12:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:14:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:17:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:22:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:22:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:26:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:26:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:27:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:44:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:46:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T15:59:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:01:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:08:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:27:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T16:31:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:09:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:27:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:27:47+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T17:46:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:12:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-16T18:22:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:01:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:02:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:05:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:06:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:10:58+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:14:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:15:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:16:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:17:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:18:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:21:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:21:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T12:23:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:24:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:25:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:30:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:32:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:34:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:35:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:37:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:37:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:39:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:56+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:41:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:43:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:54:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:54:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:55:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:55:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:57:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:57:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:58:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:58:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T14:59:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:00:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:03:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-17T15:06:26+02:00 using OBMtranslation (0.4.1)

$l_type_insert = "Crea il Tipo";
$l_link_contact = "Dei contatti sono abbonati a questa pubblicazione";
$l_subscription = "Abbonamento";
$l_j_check_year = "L'anno non è corretto.";
$l_j_check_lang = "La lingua indicata non è corretta.";
$l_type_can_delete = "Il tipo può essere eliminato.";
$l_fill_title = "Inserisci il Titolo prima di validare.";
$l_recept_new = "Nuova Modalità di ricevimento";
$l_j_type_update = "Seleziona un tipo ed aggiorna prima di proseguire!";
$l_contact_category1 = "Categoria contatto 1";
$l_check_samepublication = "Queste pubblicazioni sembrano essere simili alla nuova inserita!";
$l_found = "Pubblicazioni trovate.";
$l_j_type_create = "Inserisci un nome di tipo per crearlo!";
$l_renew_checkdelete = "Verifica o Elimina la Modalità di rinnovamento";
$l_type_link_publication = "Queste pubblicazioni sono associate al tipo";
$l_renew_update = "Modifica la Modalità di rinnovamento";
$l_type_manage = "Gestione Tipo di Pubblicazione"; 
$l_type = "Tipo";
$l_recept = "Modalità di ricevimento";
$l_j_type_delete = "Seleziona un tipo da verificare o eliminare!";
$l_cant_delete = "La pubblicazione non può essere eliminata.";
$l_recept_link_publication = "Queste pubblicazioni sono associate alla modalità di ricevimento";
$l_type_delete = "Elimina tipo";
$l_renew_delete = "Elimina Modalità di rinnovamento";
$l_publication_dest = "Destinazione Pubblicazione";
$l_reception = "Modalità di ricevimento";
$l_j_renew_create = "Inserisci un nome di modalità di rinnovamento per crearla!";
$l_j_check_quantity = "Inserisci una quantità valida ";
$l_publication_type = "Tipo di Pubblicazione";
$l_type_link_publication_no = "Nessuna pubblicazione associata al tipo";
$l_type_exist = "Tipi esistenti";
$l_auto_sub = "Abbonamento automatico";
$l_insert = "Inserisci Pubblicazione";
$l_recept_link_publication_no = "Nessuna Pubblicazione associata alla modalità di ricevimento";
$l_j_recept_create = "Inserisci un nome di modalità di ricevimento per crearla!";
$l_can_delete = "La pubblicazione può essere eliminata.";
$l_delete_confirm = "Confirmi eliminazione Pubblicazione?";
$l_type_update = "Modifica Tipo";
$l_renew = "Rinnovamento automatico";
$l_publication_orig = "Pubblicazione originale";
$l_renew_cant_delete = "La modalità di rinnovamento non può essere eliminata!";
$l_recept_can_delete = "La modalità di ricevimeto può essere eliminata";
$l_type_checkdelete = "Verifica o Elimina il Tipo";
$l_no_display = "Riempi i campi di ricerca e premi < Cerca > per ottenere l'elenco delle pubblicazioni."; 
$l_renew_can_delete = "La modalità di rinnovamento può essere eliminata.";
$l_quantity = "Quantità";
$l_publication_title = "Titolo Pubblicazione";
$l_j_renew_delete = "Seleziona una modalità di rinnovamento da verificare o eliminare!";
$l_update = "Modifica Pubblicazione";
$l_recept_insert = "Crea Modalità di ricevimento";
$l_insert_sub = "Inserisci Abbonamento";
$l_renew_link_publication_no = "Nessuna pubblicazione associata alla modalità di rinnovamento";
$l_j_recept_delete = "Seleziona una modalità di ricevimento da validare o eliminare!";
$l_j_fill_lang = "Inserisci la Lingua prima di validare";
$l_type_new = "Nuovo Tipo";
$l_checkdelete = "Verifica o Elimina Pubblicazione";
$l_update_sub = "Modifica Abbonamento";
$l_publication_display = "Opzioni di visualizzazione dell'elenco pubblicazioni"; 
$l_delete = "Elimina Pubblicazione";
$l_renew_insert = "Crea Modalità di rinnovamento";
$l_checkdelete_sub = "Verifica o Elimina Abbonamento";
$l_j_renew_update = "Seleziona una modalità di rinnovamento ed aggiorna prima di validare!";
$l_link_contact_no = "Nessun contatto non è abbonato alla pubblicazione";
$l_renew_exist = "Modalità di rinnovamento esistente"; 
$l_type_cant_delete = "Il tipo non può essere eliminato!";
$l_delete_sub = "Elimina Abbonamento";
$l_recept_checkdelete = "Verifica o Elimina la Modalità di ricevimento";
$l_j_select_publication = "Seleziona una pubblicazione!";
$l_recept_update = "Modifica la Modalità di ricevimento";
$l_no_found = "Nessuna pubblicazione trovata!";
$l_j_recept_update = "Seleziona una modalità di ricevimento ed aggiorna prima di validare.";
$l_recept_manage = "Gestione Modalità di ricevimento"; 
$l_header_new_auto = "Rinnovamento";
$l_recept_cant_delete = "La modalità di ricevimento non può essere eliminata!";
$l_j_fill_quantity = "Specifica una quantità";
$l_renew_new = "Nuova Modalità di ricevimento";
$l_renew_manage = "Gestione Modalità de ricevimento";
$l_recept_delete = "Elimina Modalità di ricevimento";
$l_recept_exist = "Modalità di ricevimento esistenti";
$l_renew_link_publication = "Queste pubblicazioni sono associate alla modalità di ricevimento";

