<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italian                                                 //
//     - File     : settings.inc                                            //
// 01/08/2002 Augusto Fagioli                                               //
//////////////////////////////////////////////////////////////////////////////
// $Id$ //
//////////////////////////////////////////////////////////////////////////////

$l_settings = "Impostazioni";
$l_cur_settings = "Impostazioni Attuali";
$l_auto_display = "Elenco Automatico";
$l_submit = "Conferma";
$l_cur_lang = "Lingua corrente";
$l_cur_theme = "Grafica in uso";
$l_new_settings = "Scegli qui le nuove impostazioni";
$l_set_lang = "Scegli la lingua";
$l_set_theme = "Scegli la grafica";
$l_set_menu = "Menu display";
$l_set_rows = "Quante righe per pagina?";
$l_set_date = "Date format";
$l_set_commentorder = "Comment display";
$l_set_cal_interval = "Calendar interval";
$l_set_csv_sep = "CSV Export separator";
$l_set_debug = "Debugging level";
$l_send_mail = "Accept e-mails";

$l_update_ok = "Settings updated successfully";

$l_dg_id = "Id";
$l_dg_param = "Parameters";
$l_dg_sess = "Session";
$l_dg_sql = "SQL";

$l_da_iso = "yyyy-mm-dd";
$l_da_en = "mm/dd/yyyy";
$l_da_fr = "dd/mm/yyyy";
$l_da_txt = "dd month yyyy";

$l_me_txt = "text";
$l_me_ico = "icon";
$l_me_both = "text+icon";

$l_co_chro = "Chronological";
$l_co_rev = "Reverse";

$l_csvd_sc = ";";
$l_csvd_tab = "tab";
