#!/bin/bash
#
# OBM Plugin to monitor number of connected user on minig-backend
# OBM developper: Sylvain Garcia
#
# Parameters:
#
# 	config   (required)
# 	autoconf (optional - only used by munin-config)
#%# family=auto
#%# capabilities=autoconf

app_name="Minigi-Backend"
app_init_script="/etc/init.d/minig-backend"


case $1 in
  autoconf)
    if [ -e $app_init_script ]; then
      echo 'yes'
      exit 0
    else
      echo "no"
      exit 0
    fi
  ;;
  config)
    echo "graph_args --base 1000 -l 0"
    echo "graph_title users connected to Minig";
    echo "graph_category system";
    echo "graph_info This graph show number of user who use Minig"
    echo "graph_vlabel users"
    echo "users.label users"
    exit 0
  ;;
esac

if [ -e /var/log/minig/minig-backend.log ]; then
  nb_users=`grep "active sessions" /var/log/minig/minig-backend.log | tail -n 1 | cut -d" " -f9`
  echo "users.value $nb_users"
else
  echo "users.value 0"
fi


exit 0
