=head1 NOM

dbUpdate.pl - Script permettant de valider ou annuler les modifications
effectuées en BD. C'est lui qui est exécuté par le formulaire de confirmation
des modifications effectuées dans l'interface (post-it).

=head1 DEPENDANCES

 require OBM::dbUtils;
 require OBM::toolBox;
 use Getopt::Long;

=head1 DESCRIPTION

 Ce script permet de confirmer ou annuler les modifications faites via
 l'interface graphique.

 Il est utilisé par l'outil de mise à jour de l'interface.

=head1 PARAMETRES

 Afin de répondre aux différents cas, ce script prend plusieurs paramètres :

=over 4

=item B<valid>

valide les modifications effectuées. Il copie le contenu de certaines tables BD
de production modifiées par l'interface vers les tables BD correspondantes et
préfixées de 'P_' ;

=item B<cancel>

annule les modifications effectuées. Il copie le contenu des tables BD
préfixées de 'P_' vers les tables BD de production.

=back

 Les tables de la base de données impactées sont :

=over 4

=item table de production 'B<Domain>', table correspondante 'B<P_Domain>' ;

=item table de production 'B<EntityRight>', table correspondante
'B<P_EntityRight>' ;

=item table de production 'B<GroupGroup>', table correspondante 'B<P_GroupGroup>' ;

=item table de production 'B<Host>', table correspondante 'B<P_Host>' ;

=item table de production 'B<MailServer>', table correspondante 'B<P_MailServer>' ;

=item table de production 'B<MailServerNetwork>', table correspondante
'B<P_MailServerNetwork>' ;

=item table de production 'B<MailShare>', table correspondante 'B<P_MailShare>' ;

=item table de production 'B<Samba>', table correspondante 'B<P_Samba>' ;

=item table de production 'B<UGroup>', table correspondante 'B<P_UGroup>' ;

=item table de production 'B<UserObm>', table correspondante 'B<P_UserObm>' ;

=item table de production 'B<UserObmGroup>', table correspondante
'B<P_UserObmGroup>' ;

=back

=cut
