<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Norwegian                                                //
//     - File     : global.inc                                               //
// 2002-08-10 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Common actions
$l_find = "Finn";
$l_back = "Back";
$l_cancel = "Cancel";
$l_close = "Close the window";
$l_validate = "Validate";

// Common messages
$l_all = "Alle";
$l_all_f = "Alle";
$l_none = "---";
$l_comment = "Kommentar";
$l_add_comment = "Add a Kommentar";
$l_upd_comment = "Update Kommentar";
$l_default = "Default";
$l_archive = "Arkiv";
$l_archive_first = "A";
$l_date = "Date";
$l_name = "Namn";
$l_label = "Namn";
$l_phone = "Telefon";
$l_fax = "Fax";
$l_invalid_data = "Ugyldig data";
$l_postcode = "Postnummer";
$l_town = "By";
$l_expresspostal = "Ekspresspost";
$l_country = "Land";
$l_priority = "Priority";
$l_datasource = "Data source";
$l_cat = "Kategori";
$l_visibility = "Access";
$l_private = "Private";
$l_public = "Public";

// OBM_DISPLAY
$l_entries = "Entries";
$l_page_res = "Result pages";
$l_field = "Field";
$l_displayed = "Displayed";
$l_order = "Display order";
$l_move = "Move";
$l_mandatory = "Display of this field is mandatory";
$l_display_no = "Stop displaying this field";
$l_display_yes = "Display this field";
$l_down = "Move the field down one row";
$l_up = "Move the field up one row";

// OBM_DISPLAY help screen
$l_help = "Help";
$l_help_display_yes = "The field is displayed. Click on this button if you want the field not to be displayed";
$l_help_display_no = "The field is not displayed. Click on this button if you want the field to be displayed";
$l_help_mandatory = "This field is mandatory";
$l_help_down  = "Move the field down";
$l_help_up = "Move the field up";

// Tasktype groups
$l_task_fac = "Factured Tasks";
$l_task_int = "Internal Projects";
$l_task_div = "Not Factured Tasks";

// Days and months
$l_monthsofyear = array('January','February', 'March','April','May','June','July','August','September','October','November','December');
$l_monthsofyearshort = array('jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec');
$l_daysofweek = array('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
$l_daysofweekshort = array('Sun','Mon','Tue','Wed','Thu','Fri','Sat');
$l_daysofweekreallyshort = array ('S','M','T','W','T','F','S');

//---------------------------------------------------------------------------//
// Theme headers lang files
//---------------------------------------------------------------------------//

$l_header_com    = "Word to define";
$l_header_prod   = "Word to define";
$l_header_compta = "Word to define";
$l_header_users  = "Word to define";
$l_header_admins = "Word to define";

$l_header_settings = "Oppsett";
$l_header_company = "Firma";
$l_header_contact = "Kontaktar";
$l_header_deal = "Avtaler";
$l_header_list = "Lists";
$l_header_user = "Brukarar";
$l_header_admin = "Administrasjon";
$l_header_computer = "Computers";
$l_header_contract =  "Word to define";
$l_header_incident = "Word to define";
$l_header_account = "Word to define";
$l_header_invoice = "Word to define";
$l_header_payment = "Word to define";
$l_header_time = "Word to define";
$l_header_agenda = "Word to define";

$l_header_title_computer = "COMPUTER" ;
$l_header_title_settings = "OPPSETT";
$l_header_title_company = "FIRMA";
$l_header_title_contact = "KONTAKT";
$l_header_title_deal = "AVTALE";
$l_header_title_list = "LIST";
$l_header_title_user = "BRUKAR";
$l_header_title_admin = "ADMINISTRASJON";
$l_header_title_contract =  "Word to define";
$l_header_title_account = "Word to define";
$l_header_title_incident = "Word to define";
$l_header_title_invoice = "Word to define";
$l_header_title_payment = "Word to define";
$l_header_title_time = "Word to define";
$l_header_title_agenda = "Word to define";

$l_header_new_f = "Ny";
$l_header_new = "Ny";
$l_header_find = "Finn";

$l_header_new_child = "Ny linked Deal";
$l_header_new_parent = "Ny ParentDeal";
$l_header_find_parent = "Find ParentDeal";
$l_header_delete =  "Word to define";

$l_header_reconcile =  "Word to define";
$l_header_duplicate =  "Word to define";
$l_header_compute_balance =  "Word to define";

$l_header_add_contact = "Word to define";

$l_header_reset = "Word to define";

// Admin headers
$l_header_index = "Main";
$l_header_help = "Help";
$l_header_amp = "Show amp";
$l_header_func_unused = "Functions";
$l_header_clear_sess = "Clear sessions";
$l_header_pref_update = "Reset users preferences";

$l_header_agenda = "Agenda";
$l_header_title_agenda = "AGENDA";
$l_header_day = "Jour";
$l_header_week = "Semaine";
$l_header_month = "Mois";
$l_header_new_event = "Nouveau rdv";

$l_header_admin_ref = "Referential";
