<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Norwegian                                                //
//     - File     : global.inc                                               //
// 2002-08-10 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id //
///////////////////////////////////////////////////////////////////////////////

// Common actions
$l_find = "Finn";
$l_back = "Back";
$l_cancel = "Cancel";
$l_close = "Close the window";
$l_validate = "Validate";

// Common messages
$l_all = "Alle";
$l_all_f = "Alle";
$l_archive = "Arkiv";
$l_none = "---";
$l_invalid_data = "Ugyldig data";

// Mysql Date format
$l_datetime_format = "%Y-%m-%d %H:%i:%s"; // Complete Date + Time
$l_date_format = "%Y-%m-%d"; // Date only 
$l_date_text_format = "%a %d %M"; // Date only (text mode eg : Mon 10 Jul)
$l_time_format = "%H:%i:%s"; // Time only

// OBM_DISPLAY
$l_field = "Field";
$l_displayed = "Displayed";
$l_order = "Display order";
$l_move = "Move";
$l_mandatory = "Display of this field is mandatory";
$l_display_no = "Stop displaying this field";
$l_display_yes = "Display this field";
$l_down = "Move the field down one row";
$l_up = "Move the field up one row";

// OBM_DISPLAY help screen
$l_help = "Help";
$l_help_display_yes = "The field is displayed. Click on this button if you want the field not to be displayed";
$l_help_display_no = "The field is not displayed. Click on this button if you want the field to be displayed";
$l_help_mandatory = "This field is mandatory";
$l_help_down  = "Move the field down";
$l_help_up = "Move the field up";


//used by many modules
// days and months
$l_january="January";
$l_february="February";
$l_march="March";
$l_april="April";
$l_may="May";
$l_june="June";
$l_july="July";
$l_august="August";
$l_september="September";
$l_october="October";
$l_november="November";
$l_december="December";

$l_short_january="Jan";
$l_short_february="Feb";
$l_short_march="Mar";
$l_short_april="Apr";
$l_short_may="May";
$l_short_june="Jun";
$l_short_july="Jul";
$l_short_august="Aou";
$l_short_september="Sep";
$l_short_october="Oct";
$l_short_november="Nov";
$l_short_december="Dec";
