<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Norwegian                                                //
//     - File     : global.inc                                               //
// 2002-08-10 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Common actions
$l_find = "Finn";
$l_back = "Back";
$l_cancel = "Cancel";
$l_close = "Close the window";
$l_validate = "Validate";
$l_add = "Add";

// Common messages
$l_all = "Alle";
$l_all_f = "Alle";
$l_none = "---";
$l_undef = "---";
$l_id = "Id";
$l_comment = "Kommentar";
$l_add_comment = "Add a Kommentar";
$l_upd_comment = "Update Kommentar";
$l_default = "Default";
$l_status = "Status";
$l_archive = "Arkiv";
$l_archive_first = "A";
$l_date = "Date";
$l_datebegin = "Begin date";
$l_dateend = "End date";
$l_name = "Namn";
$l_label = "Namn";
$l_phone = "Telefon";
$l_fax = "Fax";
$l_invalid_data = "Ugyldig data";
$l_postcode = "Postnummer";
$l_town = "By";
$l_expresspostal = "Ekspresspost";
$l_country = "Land";
$l_desc = "Beskriving";
$l_priority = "Priority";
$l_local = "Local";
$l_ext_id = "Id ext";
$l_datasource = "Data source";
$l_visibility = "Access";
$l_private = "Private";
$l_public = "Public";
$l_category1 = "Kategori 1";
$l_category2 = "Kategori 2";
$l_aduplicate = "Duplicate";


// OBM_DISPLAY
$l_entries = "Entries";
$l_page_res = "Result pages";
$l_field = "Field";
$l_displayed = "Displayed";
$l_order = "Display order";
$l_move = "Move";
$l_mandatory = "Display of this field is mandatory";
$l_display_no = "Stop displaying this field";
$l_display_yes = "Display this field";
$l_down = "Move the field down one row";
$l_up = "Move the field up one row";

// OBM_DISPLAY help screen
$l_help = "Help";
$l_help_display_yes = "The field is displayed. Click on this button if you want the field not to be displayed";
$l_help_display_no = "The field is not displayed. Click on this button if you want the field to be displayed";
$l_help_mandatory = "This field is mandatory";
$l_help_down  = "Move the field down";
$l_help_up = "Move the field up";

// Tasktype groups
$l_tt = "Task Type";
$l_tt_sales = "Factured Tasks";
$l_tt_resaerch = "Internal Projects";
$l_tt_others = "Not Factured Tasks";

// Days and months
$l_today = "Today";
$l_monthsofyear = array('January','February', 'March','April','May','June','July','August','September','October','November','December');
$l_monthsofyearshort = array('jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec');
$l_daysofweek = array('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday');
$l_daysofweekshort = array('Sun','Mon','Tue','Wed','Thu','Fri','Sat');
$l_daysofweekfirst = array ('S','M','T','W','T','F','S');

//---------------------------------------------------------------------------//
// Theme headers lang files
//---------------------------------------------------------------------------//

$l_section_com    = "Word to define";
$l_section_prod   = "Word to define";
$l_section_compta = "Word to define";
$l_section_user   = "Users";
$l_section_admin  = "Admin";

$l_module_settings = "Oppsett";
$l_module_company = "Firma";
$l_module_contact = "Kontaktar";
$l_module_deal = "Avtaler";
$l_module_list = "Lists";
$l_module_user = "Brukarar";
$l_module_admin = "Administrasjon";
$l_module_computer = "Computers";
$l_module_contract =  "Word to define";
$l_module_incident = "Word to define";
$l_module_account = "Word to define";
$l_module_invoice = "Word to define";
$l_module_payment = "Word to define";
$l_module_time = "Word to define";
$l_module_agenda = "Word to define";

$l_header_new_f = "Ny";
$l_header_new = "Ny";
$l_header_find = "Finn";

$l_header_new_child = "Ny linked Deal";
$l_header_new_parent = "Ny ParentDeal";
$l_header_find_parent = "Find ParentDeal";
$l_header_delete =  "Word to define";

$l_header_reconcile =  "Word to define";
$l_header_duplicate = "Duplicate";
$l_header_compute_balance =  "Word to define";

$l_header_add_contact = "Word to define";

$l_header_reset = "Word to define";

// Admin headers
$l_header_index = "Main";
$l_header_help = "Help";
$l_header_amp = "Show amp";
$l_header_func_unused = "Functions";
$l_header_clear_sess = "Clear sessions";
$l_header_pref_update = "Reset users preferences";

$l_header_agenda = "Agenda";
$l_header_day = "Jour";
$l_header_week = "Semaine";
$l_header_month = "Mois";
$l_header_new_event = "Nouveau rdv";
$l_header_right = "Right management";

$l_header_admin_ref = "Referential";

// Debug
$l_dg_id = "Id";
$l_dg_param = "Parameters";
$l_dg_sess = "Session";
$l_dg_sql = "SQL";

