<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : Norwegian                                               //
//     - File     : settings.inc                                            //
// 2000-07-20 Magni Onsoien                                                 //
//////////////////////////////////////////////////////////////////////////////

$l_cur_settings = "Noverande oppsett";
$l_auto_display = "Automatisk listing ";
$l_submit = "Ok";
$l_cur_lang = "Noverande språk";
$l_cur_theme = "Noverande fargeval";
$l_new_settings = "Velg nye parametre her for å endre oppsettet ditt.";
$l_set_lang = "Velg språk";
$l_set_theme = "Velg fargeval.";

$l_last_deal="Last deal";
$l_last_company = "Last company";
$l_last_contact = "Last contact";
