<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Norwegian                                                //
//     - File     : settings.inc                                             //
// 2000-07-20 Magni Onsoien                                                  //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_cur_settings = "Noverande oppsett";
$l_auto_display = "Automatisk listing ";
$l_cur_lang = "Noverande språk";
$l_cur_theme = "Noverande fargeval";
$l_new_settings = "Velg nye parametre her for å endre oppsettet ditt.";
$l_set_lang = "Velg språk";
$l_set_theme = "Velg fargeval.";
$l_set_rows = "# Rows displayed per page";
$l_set_date = "Date format";
$l_set_cal_interval = "Calendar interval";
$l_set_menu = "Menu display";
$l_set_debug = "Debugging level";

$l_dg_id = "Id";
$l_dg_param = "Parameters";
$l_dg_sess = "Session";
$l_dg_sql = "SQL";

$l_da_iso = "yyyy-mm-dd";
$l_da_en = "mm/dd/yyyy";
$l_da_fr = "dd/mm/yyyy";
$l_da_txt = "dd month yyyy";

$l_da_dmy = "dmy";
$l_da_mdy = "mdy";

$l_me_txt = "text";
$l_me_ico = "icon";
$l_me_both = "text+icon";

$l_csvd_sc = ";";
$l_csvd_tab = "tab";