<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : Norwegian                                               //
//     - File     : user.inc                                                //
// 2000-07-20 Magni Onsoien                                                 //
//////////////////////////////////////////////////////////////////////////////

$l_user_name = "Brukar";
$l_user_perms = "Autorisering";
$l_password = "Passord";
$l_all = "Alle";
$l_find = "Finn";
$l_lastaccess = "Siste pålogging";
$l_email = "@M";
$l_perms_user = "Brukar";
$l_perms_editor = "Redigere";
$l_perms_admin = "Administrator";

$l_invalid_data = "Ugyldig data";

$l_last_deal="Last deal";
$l_last_company = "Last company";
$l_last_contact = "Last contact";

// Titres
$l_user = "Brukar";
$l_user_detail = "Brukardetaljar";
$l_user_new = "Ny brukar";
$l_user_insert = "Legg inn brukar";
$l_user_update = "Endre brukar";
$l_user_delete = "Slett brukar";

// Actions
$l_insert = "Legg inn brukaren";
$l_update = "Oppdater brukaren";
$l_delete = "Slett brukaren";

// Messages
$l_no_display = "Fyll inn søkefeltet og trykk < Finn > for å hente ut brukarar";
$l_found = "found (to translate) !";
$l_no_found = "Ingen brukar passa til søket!";
$l_delete_ok = "Brukaren er sletta.";
$l_delete_error = "Brukaren kunne ikkje slettast!";
$l_insert_ok = "Brukaren er lagt til.";
$l_insert_error = "Brukaren kunne ikkje leggast til!";
$l_update_ok = "Brukaren er oppdatert.";
$l_update_error = "Brukaren kunne ikkje oppdaterast!";
$l_query_error = "Problem med å utføre søket.";

$l_exist_error = "finst alt";
$l_username_error = "Ugyldig brukarnamn";
$l_password_error = "Ugyldig passord";
$l_email_error = "Ugyldig mailadresse";

// JavaScript Messages (specials charcaters must be escaped whith \ -> \\)
$l_fill_username = "\\n Du må fylle inn brukaren før du legg inn.";
$l_fill_password = "\\n Du må fylle inn passord før du legg inn.";
$l_delete_confirm = "Slette brukar?";
$lj_check_email = "Mailadressa er ugyldig.";

// Specifics fields
// MySQL Date and time format for display in the deal detail screen
$l_time_format = "%Y-%m-%d %H:%i:%s";
$l_date_format = "%Y-%m-%d %H:%i:%s";

