=head1 NOM

OBM::ldap - Fait les operations sur les entitées LDAP utilisées par Aliamin

=head1 DEPENDANCES

 use OBM::Parameters::common;
 use OBM::Parameters::ldapConf;
 use Net::LDAP;
 use Net::LDAP::Entry;
 require OBM::Tools::perlUtils;
 use Unicode::MapUTF8 qw(to_utf8 from_utf8 utf8_supported_charset);

=head1 DESCRIPTION

    use OBM::ldap;
    
Ce paquet implémente les fonctions de manipulations de l'annuaire LDAP.

Ce paquet met à disposition une API permettant de créer, modifier,
supprimer les entées LDAP en les synchronisant avec le contenu de la base de
données d'OBM.

=cut
