<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Español                                                  //
//     - File     : admin.inc                                                //
// 2003-11-18 Jaime E. Gomez H.   kasandra@skina.com.co                      //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// labels
$l_check = "Revisando";
$l_database_server = "Motor de Bases de datos";
$l_database = "Base de datos";
$l_host = "Servidor";
$l_session_stats = "Estadísticas de sesiones";
$l_date = "Fecha";
$l_lifetime = "Duración de la sesión de usuario (segundos)";
$l_user_session = " Existencias en ActiveUserObm";
$l_active_user = "Usuarios Activos";
$l_login_date = "Fecha de Ingreso";
$l_last_acces = "Último acceso";
$l_nb_connec = "Número de Hits";
$l_last_page = "Última página";
$l_user_ip = "IP";


// Titles
$l_admin = "Administración";
$l_admin_lang = "Lenguaje de Administración";

// Actions
$l_help = "Ayuda";

