<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Español                                                  //
//     - File     : contract.inc                                             //
// 2003-11-18 Jaime E. Gomez H.   kasandra@skina.com.co                      //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Labels et textes
$l_contract = "Contrato";
$l_company = "Compañía";
$l_contract_contracttype = "Tipo de contrato";
$l_contract_exp = "Expiración";
$l_date_alarm_after = "Antes de Fecha de vencimiento";
$l_date_alarm_before = "Posterior a  Fecha de vencimiento";
$l_after = "Antes de Fecha de vencimiento";
$l_before = "Posterior a  Fecha de vencimiento";
$l_incident_list = "Lista de  incidentes";
$l_incident_new = "Adicione un nuevo incidente";

$l_contract_select_deal = "Seleccionar el Negocio.";
$l_deal = "Negocio";
$l_label = "Referencia";
$l_label_libelle = "Palabra clave de la Referencia";
$l_kind = "Tipo";
$l_marketing_manager = "Gerente de Mercadeo";
$l_technical_manager = "Gerente Técnico";
$l_client_manager = "Gerente Comercial";
$l_clause = "Clausulas";
$l_date_init = "Fecha de Inicio";
$l_dateexp = "Fecha Final";
$l_last_update = "Última actualización";
$l_at = "a las";
$l_number = "Número";

// Actions
$l_insert = "Ingresar el contrato";
$l_update = "Actualizar el contrato";
$l_delete = "Borrar el contrato";
$l_select_company = "Seleccione la compañía";

$l_select_contract = "Seleccione el contrato";

// Messages
$l_no_display = "Llene los campos de búsqueda y presione < Buscar > para obtener los contratos";
$l_found = "contratos encontrados.";
$l_no_found = "No hay contratos que coincidan con la búsqueda !";
$l_delete_ok = "El contrato ha sido borrado exitosamente.";
$l_delete_error = "La eliminación del contrato ha fallado !";
$l_insert_ok = "El contrato ha sido ingresado exitosamente.";
$l_insert_error = "El ingreso del contrato ha fallado !";
$l_update_ok = "El contrato ha sido actualizado exitosamente.";
$l_update_error = "La actualización of el contrato ha fallado !";

$l_link_incident = "El contrato tiene estos incidentes";
$l_link_incident_no = "El contrato no tiene incidentes";
$l_cant_delete = "El contrato no puede ser borrado !";
$l_can_delete = "El contrato puede ser borrado.";

$l_type_manage = "Manejo de tipo de contrato de soporte";
$l_type_exist = "Tipos existentes";
$l_type_new = "Nuevo tipo";
$l_type_checkdelete = "Revisar o Borrar Tipo"; 
$l_type_delete = "Borrar Tipo"; 
$l_type_update = "Actualizar Tipo";
$l_type_insert = "Crear Tipo";
$l_type_insert_ok = "El Tipo ha sido ingresado exitosamente.";
$l_type_insert_error = "El ingreso del Tipo ha fallado !";
$l_type_update_ok = "El Tipo ha sido actualizado exitosamente";
$l_type_update_error = "La actualización del Tipo ha fallado !";
$l_type_delete_error = "La eliminación de Tipo ha fallado !";
$l_type_delete_ok = "El Tipo ha sido borrado exitosamente.";
$l_type_cant_delete = "El Tipo NO puede ser borrado !";
$l_type_can_delete = "EL tipo puede ser borrado.";
$l_type_link_contract = "El tipo esta involucrado en estos contratos";

$l_err_label_empty = "Tiene que llenar el nombre !";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_j_select_contract = "Debe generar un contrato !";
$l_j_type_delete = "Debe seleccionar el tipo a borrar !";
$l_j_type_update = "Debe seleccionar un Tipo e ingresar la modificación a enviar !"; 
$l_j_type_create = "Debe ingresar el nombre del nuevo tipo a crear !";
$l_delete_confirm = "Realmente desea borrar el Contrato ?";

// For the display preferences modification screen 
$l_contract_display = "Opciones de despliegue de Contratos de Soporte";
