<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Español                                                  //
//     - File     : import.inc                                               //
// 2006-02-24 Jaime E. Gomez H.   jgomez@skinatech.com                       //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

// Title
$l_import = "Importar";

// Labels and texts
$l_file = "Archivo";
$l_format = "Formato";
$l_csv_sep = "Separador CSV";
$l_enclosed = "Campos contenidos por";
$l_mapping = "mapeo de campos";
$l_field_num = "# campo";
$l_field = "campo";
$l_default = "Valor por omisión";
$l_result = "Resultado";
$l_info = "Información";
$l_sample_file = "Archivo de muestra para revisar";
$l_conflict = "Conflicto";
$l_nb_insert = "inserciones";
$l_nb_update = "actualizaciones";
$l_mailing_ok_msg = "'X', '1', 'Y' para habilitar correos";

// Actions
$l_insert = "Ingresarar la importación";
$l_update = "Actualizar la importación";
$l_delete = "Borrar la importación";
$l_check_file = "Revisar este archivo";
$l_test_file = "Probar este archivo";
$l_comp_nothing = "Mantener la compañía actual";
$l_comp_insert = "Ingresar this compañía";
$l_comp_update = "Actualizar compañía existente";
$l_con_nothing = "Mantener contacto existente";
$l_con_insert = "Ingresar este contacto";
$l_con_update = "Actualizar contacto existente";

// Messages
$l_name_import_nomatch = "El nombre de la importación no es válido";
$l_import_exists = "Lo siento pero la importación ya existe";
$l_check_sameimport = "Estas importaciones lucen similares a la nueva !";
$l_warn_delete = "Realmente desea borrar esta importación ?";
$l_import_end = "Importación terminada";
$l_lines_processed = "lineas procesadas";
$l_conflict_detected = "Conflicto detectado";
$l_invalid_row = "Fila Invalida !";
$l_invalid_rows = "Filas Inválidas";
$l_conflict_rows = "Filas en Conflicto";

$l_no_display = "Llene los campos de búsqueda y presione < Buscar > para obtener las importaciones definidas";
$l_found = "importaciones encontradas.";
$l_no_found = "No hay importaciones que coincidan con la búsqueda !";

$l_fill_name = "El nombre de la importación debe ser llenado !";
$l_similar_company = "Compañía similar";
$l_similar_contact = "Contacto similar";
$l_company_defaultname = "Compañía sin Nombre";
$l_contact_defaultname = "Contacto sin Apellido";

$l_csvd_sc = ";";
$l_csvd_tab = "tab";
