<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Theme : Standard                                                    //
//     - File  : theme.inc                                                   //
// 2002-07-18 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Colors used //
$col_orange = "EE9B00";
$col_purpleblue = "59519E";
$col_blue = "009FC2";

$col_label = $col_purpleblue;    // Labels (grey fonce)
$col_ok = $col_orange;       // Messages color (bleu violet)
$col_error="FF0000";    // Errors messages color (rouge)

// accounting stuff colors 
$col_client = "00FF00"; // facture client (vert)
$col_frs = "FF0000";    // facture fournisseur (rouge)
$col_balance_neg = "FF0000";  // when the balance is <= 0  (red)
$col_balance_pos = "00FF00";  // when the balance is >  0  (green)


////////////
// Images //
////////////
$ico_principal      = "aliacom.jpg";  // BIG LOG
$ico_contact        = "contact.gif";            // Contact Icon
$ico_obm            = "obm.jpg";                    // OBM icon
$ico_validate	    = "oui2.gif";
$ico_cancel	    = "non2.gif";

// Menus Icons
$ico_contact        = "ico_contact.gif";         // Contact Icon
$ico_contact_new    = "ico_contact_new.gif";     // New Contact Icon
$ico_deal           = "ico_deal.gif";            // Deal Icon
$ico_deal_new       = "ico_deal_new.gif";        // New Deal Icon
$ico_company        = "ico_company.gif";         // Company Icon
$ico_change_company = "ico_change_company.gif";  // Contract Icon
$ico_list           = "ico_list.gif";            // List Icon
$ico_agenda         = "ico_agenda.gif";          // Agenda Icon
$ico_contract       = "ico_phone.gif";
$ico_incident       = "ico_incident.gif";
$ico_account        = "ico_account.gif";
$ico_invoice        = "ico_invoice.gif";
$ico_payment        = "ico_payment.gif";

$ico_time           = "ico_time.gif";
$ico_project        = "ico_project.gif";
$ico_user           = "ico_user.gif";
$ico_setting        = "ico_setting.gif";

$ico_admin          = "ico_admin.gif";
$ico_code           = "ico_code.gif";
$ico_pref           = "ico_pref.gif";
$ico_data           = "ico_data.gif";
$ico_lang           = "ico_lang.gif";

// OBM DISPLAY Icons
$ico_export         = "ico_export.gif";
$ico_export_all     = "ico_export_all.gif";
$ico_begin          = "ico_begin.gif";
$ico_end            = "ico_end.gif";

$ico_web            = "ico_web.gif";        // WWW Icon
$ico_mail           = "ico_mail.gif";       // Mail Icon
$ico_arrow_up       = "arrow_up.gif";       // The up arrow
$ico_arrow_down     = "arrow_down.gif";     // The down arrow
$ico_crow           = "crow-red.gif";
$ico_ball           = "ball-green.gif";
$ico_back           = "arrow_back.gif" ;
$ico_forbidden      = "forbidden.gif";
$ico_warning        = "warning.gif";

//Agenda Icons
$ico_confirm_mail   = "ico_confirmmail.gif";
$ico_new_event      = "ico_calendar_new.gif";
$ico_event          = "ico_calendar_evt.gif";
$ico_left_day       = "left_day.gif";
$ico_right_day      = "right_day.gif";
$ico_spacer         = "spacer.gif";
$ico_calendar_user0 = "ico_calendar0.gif";
$ico_calendar_user1 = "ico_calendar1.gif";
$ico_calendar_user2 = "ico_calendar2.gif";
$ico_calendar_user3 = "ico_calendar3.gif";
$ico_calendar_user4 = "ico_calendar4.gif";
$ico_calendar_user5 = "ico_calendar5.gif";
$ico_calendar_nouser= "ico_calendarno.gif";
$ico_mini_larrow    = "arrows_l_still.gif";
$ico_mini_larrow2   = "arrows_l_anim.gif";
$ico_mini_rarrow    = "arrows_r_still.gif";
$ico_mini_rarrow2   = "arrows_r_anim.gif";
$ico_mini_cal       = "calendar.png";
// Export icons
$ico_html = "ico_netscape.png";
$ico_excel = "ico_excel.png";
$ico_rtf = "ico_label.png";
