= IMAP Archive Service
Antoine Duprat <aduprat@linagora.com>; Matthieu Baechler <mbaechler@linagora.com>; Thomas Hilaire <thilaire@linagora.com>;
:numbered:
:sectlink:
:sectids:
:toc: left
:toclevels: 1
:icons: font

== Prerequisite

*IMAP Archive* service needs a specific partition in order to store the archived mails.

Such partition has to be created manually, as we want that the *OBM* admin is able to choose where its archives are located.


== Adding the archive partition

In order to achieve this task, you have to edit the https://cyrusimap.org/[*Cyrus*] configuration file +/etc/imapd.conf+ and add the *IMAP Archive* partition:
[source]
----
partition-domain_name_archive: /var/spool/cyrus/domain_name_archive
---- 

where:

  * _domain_name_ is the name of the domain associated to this *IMAP Archive* partition
  * _/var/spool/cyrus/domain_name_archive_ may be any not existing folder (read the note below for more information)


[NOTE]
====
The partition folder is automatically created by *Cyrus* when needed. +
Don't create it manually, as you may encounter rights issues. +
The _cyrus_ user must have write rights on the parent directory. 
====

Then, you will have to restart *Cyrus* in order to run with the new configuration.

Each domain configured for *IMAP Archive* service should have a corresponding https://cyrusimap.org/[*Cyrus*] partition.

.Sample configuration +/etc/imapd.conf+
****
partition-domain_name: /var/spool/cyrus/domain_name +
partition-domain_name_archive: /var/spool/cyrus/domain_name_archive +
partition-default: /var/spool/cyrus/mail +
defaultpartition: default +
# Debian Cyrus imapd.conf +
# $Id$ +
# See imapd.conf(5) for more information and more options +
... +
****
