<script language="php">

///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : admin.inc                                                //
// 2001-12-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T15:01:06+02:00 using OBMtranslation (0.4.1)

$l_check = "检查中"; //"Checking"
$l_database_server = "SQL服务器";  //"Database Engine"
$l_database = "数据库";  //"Database"
$l_host = "主机";  //"Host"
$l_session_stats = "会话统计";  //"Session Statistics"
$l_date = "日期";  //"Date"
$l_lifetime = "用户会话时长(秒)";  //"User session lifetime (seconds)"
$l_user_session = "ActiveUserObm中的条目";  //" Entries in ActiveUserObm"
$l_active_user = "当前活跃用户";  //"Active users"
$l_login_date = "登录日期";  //"Login date"
$l_last_access = "上次访问";  //"Last Access"
$l_nb_connec = "点击量";  //"Hits number"
$l_last_page = "上一页";  //"Last page"
$l_user_ip = "IP";  //"IP"
$l_clear_passive_session = "被动用户会话";  //"Passive users sessions"
$l_passive_session = "被动式会话";  //"Passive Sessions"
$l_activeUser_toDisplay = "第一个显示的条目开始于";  //"first entries displayed from"

// Titles
$l_admin = "管理";  //"Admin"
$l_admin_lang = "管理语言";   //"Admin Language"

// Actions
$l_help = "帮助";  //"Help"
$l_action = "动作";  //"Action"
$l_clear_sess = "清除会话";  //"Clear sessions"
