<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : group.inc                                                //
// 2003-09-01 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-09T15:20:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:07:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T11:11:17+02:00 using OBMtranslation (0.4.1)

$l_smb = "Windows"; //"Windows"
$l_system = "系统"; //"System"
$l_mailing = "邮箱地址"; //"Mailing address"
$l_nb_user = "#用户"; //"# Users"
$l_group_user = "包含的用户"; //"Containing user"
$l_group_display = "显示分组列表选项"; //"Display options for Groups lists"
$l_user_display = "显示用户列表选项"; //"Display options for Users lists"
$l_lastname = "姓"; //"Last name"
$l_firstname = "名"; //"First name"
$l_function = "功能"; //"Function"
$l_contacts = "外部成员"; //"External members"
$l_insert = "添加分组"; //"Insert the group"
$l_update = "更新分组"; //"Update the group"
$l_delete = "删除分组"; //"Delete the group"
$l_add = "添加"; //"Add"
$l_fill_name = "您必须填写分组名";  //"You have to fill in the group name"
$l_group_exists = "该分组已存在！"; //"This group already exists !"
$l_j_check_email = "该邮箱地址无效！"; //"The email address is not valid !"
$l_warn_delete = "个在该分组中注册的用户";  //"users registered in this group"
$l_email_exist = "该邮箱地址已经被使用！";  //"This email address is already used !";
$l_system_no_priv = "系统分组不能为私有！";  //"A system group cannot be private !"
$l_only_owner_priv = "只有分组的所有者可以设置分组隐私！"; //"Only the group owner can set a group privacy !"
$l_err_private_email = "私有分组不能有邮箱地址！";  //"Private group cannot have an email address!"
$l_warn_group_diff_privacy = "一些分组还没有被添加。您正试图将私有分组添加到公开分组中！";  //"Some groups have not been added. You are trying to add private groups in a public group !"
$l_groupname_error = "分组名无效！它只能包含字母，数字，空格和'。'，' - '或'_'"; //"Group name is invalid ! It can only contain letters, numbers, whitespace and '.', '-' or '_'"
$l_no_display = "填写搜索字段，并点击<查找>搜索分组";  //"Fill in the search fields and press < Find > to retrieve the groups"
$l_no_user = "没有已注册的用户。"; //"There are no users registered."
$l_no_contact = "没有已注册的外部成员。"; //"There are no external members registered."
$l_no_group_group = "没有已注册的分组。"; //"There are no groups registered."
$l_found = "个已找到的分组。"; //"groups found."
$l_user_member = "已注册的用户。"; //"users registered."
$l_contact_memeber = "已注册的外部成员。"; //"external members registered."
$l_group_member = "已注册的分组。"; //"groups registered."
$l_no_found = "未找到与查询匹配的分组！";  //"No groups matching the query has been  found !"
$l_add_user = "添加用户"; //"Add Users"
$l_add_contact = "添加外部成员"; //"Add external members"
$l_add_group = "添加分组（在可能的分组范围内）"; //"Add Groups (within possible groups)"
$l_del_user_sel = "删除这些用户"; //"Remove these users"
$l_del_contact_sel = "删除这些外部成员"; //"Remove these external members"
$l_del_group_sel = "删除这些分组"; //"Remove these groups"
$l_user_added = "用户已添加"; //"Users added"
$l_contact_added = "外部成员已添加"; //"Extenral members added"
$l_user_removed = "用户已删除"; //"Users removed"
$l_contact_removed = "外部成员已删除"; //"External members removed"
$l_group_added = "分组已添加"; //"Groups added" 
$l_group_removed = "分组已删除 "; //"removed Groups "
$l_no_user_added = "没有用户可添加"; //"No user to add"
$l_no_contact_added = "没有外部成员可添加"; //"No external member to add"
$l_no_user_deleted = "没有用户可删除"; //"No user to remove"
$l_no_contact_deleted = "没有外部成员可删除"; //"No external members to remove"
$l_no_group_added = "没有分组可添加"; //"No group to add"
$l_no_group_deleted = "没有分组可删除"; //"No group to remove"
$l_check_samegroup = "这些分组与已填入的分组相似，确定创建该分组？";  //"These groups seem similar to the filled group. Confirm group creation?"
$l_cant_delete_system = "系统分组无法被删除！"; //"System groups cannot be deleted !"
$l_can_delete = "该分组可以被删除。"; //"The group can be deleted."
$l_cant_delete = "该分组无法被删除！"; //"The group cannot be deleted !"
$l_err_cant_delete_default_user_group = "该分组是一些用户的默认分组，无法被删除！";  //"The group is the default group of some users. It cannot be deleted !"/
$l_cant_delete_domain_group = "域分组自动被OBM处理，无法被删除！";  //"Domain groups are automatically handled by OBM and cannot be deleted !"
$l_cant_update_domain_group = "域分组自动被OBM处理，无法被更新！"; //"Domain groups are automatically handled by OBM and cannot be updated !"
$l_add_groups = "添加分组"; //"Add groups"
$l_err_system_samba = "系统分组的windows更新权限没有被授权。"; //"Windows rights update of system group is not authorised."

$l_public_book_not_writable = "公用通讯录必须是可写才能执行此操作";
