<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - File : Language : zh
//      - File : obminclude/zh/imap_archive.inc
///////////////////////////////////////////////////////////////////////////////
// $Id: $ //
///////////////////////////////////////////////////////////////////////////////

$l_daily = "每日";
$l_weekly = "周刊";
$l_monthly = "每月一次";
$l_yearly = "每年";
$l_monday = "星期一";
$l_tuesday = "星期一";
$l_wednesday = "星期三";
$l_thursday = "星期四";
$l_friday = "星期五";
$l_saturday = "星期六";
$l_sunday = "星期天";
$l_last = "最后";
$l_service_activating = "服务激活";
$l_activating = "激活";
$l_scheduling = "调度";
$l_repeat_kind = "重复样";
$l_weekly_repeat_kind = "本周的每周日";
$l_monthly_repeat_kind = "本月的月日";
$l_yearly_repeat_kind = "今年的年日";
$l_hour = "小时";
$l_minute = "分钟";
$l_next_run = "下一次运行";
$l_excluded_users = "排除用户";
$l_name = "名称";
$l_delete = "删除";
$l_remove_archive = "从存档中删除";
$l_mailing_feedback = "发送电子邮件至";
$l_email_address = "电子邮件地址";
$l_past_operations = "过去的操作";
$l_start_time = "开始时间";
$l_end_time = "结束时间";
$l_status = "状态";
$l_last_fail = "最后失败";
$l_manual_launch = "手动启动";

$l_email_address_not_found = "无法找到您的电子邮件地址，该域名";
$l_imap_archive_server_not_found = "无法找到一个IMAP服务器存档此域";
$l_imap_archive_server_unreachable = "IMAP归档服务器无法访问";
$l_could_not_login_imap_archive_server = "无法登录到IMAP服务器归档";
$l_archiving_running = "当前归档日志";
$l_unsupported_iframe = "您的浏览器并不支援iframes。";
$l_archiving_launched = "存档有过气政客成功推出。";