<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : import.inc                                               //
// 2004-01-17 AliaSource - Pierre Baudracco                                  //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-11T13:45:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:49:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:49:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:54:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:57:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T13:59:44+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:02:53+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:03:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:03:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:04:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:06:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:08:35+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:11:19+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:19:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:22:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:23:05+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:23:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:24:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:25:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:26:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:26:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:04+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:27:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:29:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:30:09+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:31:16+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:32:28+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:33:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:34:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:37:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:38:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:51+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:40:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:42:49+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:43:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:43:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:45:30+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:45:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:47:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:53:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:00:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:01:06+02:00 using OBMtranslation (0.4.1)

$l_import = "导入";  //"Import"
$l_format = "格式";  //"Format"
$l_csv_sep = "CSV分隔符";  //"CSV Separator"
$l_enclosed = "附加字段";  //"Fields enclosed by"
$l_mapping = "字段映射";  //"Fields mapping"
$l_field_num = "#字段";  //"# field"
$l_field = "字段";  //"field"
$l_default = "默认值";  //"Default value"
$l_result = "结果"; //"Result"
$l_info = "信息";  //"Information"
$l_sample_file = "示例文件检查";  //"Sample file to check"
$l_conflict = "冲突";  //"Conflict"
$l_nb_insert = "插入";  //"inserts"
$l_nb_update = "更新";  //"updates"
$l_mailing_ok_msg = "'X', '1', 'Y'启用邮件功能";  //"'X', '1', 'Y' to enable mailing"
$l_insert = "添加导入数据";   //"Insert import"
$l_update = "更新导入数据";  //"Update  import"
$l_delete = "删除该导入数据";  //"Delete the import"
$l_check_file = "检查文件";  //"Check file"
$l_test_file = "测试文件";  //"Test file"
$l_comp_nothing = "保留实际公司";  //"Keep the actual company"
$l_comp_insert = "添加公司";  //"Insert company"
$l_comp_update = "更新现有公司"; //"Update existing company"
$l_con_nothing = "保留现有的联系人";  //"Keep the existing contact"
$l_con_insert = "添加联系人";  //"Insert this contact"
$l_con_update = "更新现有联系人";  // "Update the existing contact"
$l_name_import_nomatch = "导入的名字无效";  //"Import name is not valid"
$l_import_exists = "很抱歉，该导入已经存在";  //"Sorry but this import already exists"
$l_check_sameimport = "这些导入与该新记录很相似！";  //"These imports seem similar to this new entry !"
$l_warn_delete = "真的要删除该导入吗？";  //"Really delete this Import ?"
$l_import_end = "导入已中止"; //"Import terminated"
$l_lines_processed = "行已处理";  //"lines processed"
$l_conflict_detected = "已检测到冲突";  //"Conflict detected"
$l_invalid_row = "无效行！";  //"Invalid row !"
$l_invalid_rows = "无效行";  //"Invalid rows"
$l_conflict_rows = "冲突行"; //"Conflict rows"
$l_no_display = "填写搜索字段，并点击<查找>来搜索已定义的导入"; //"Fill in the search fields and press < Find > to retrieve the imports defined"
$l_found = "个导入已找到。";  //"imports found."
$l_no_found = "未找到与查询匹配的导入！"; //"No imports matching the query have been found!"
$l_fill_name = "必须填写导入名称！"; //"The Import Name must be filled in !"
$l_similar_company = "相似公司";  //"Similar company"
$l_used_company = "往常公司";  //"Used Company"
$l_similar_contact = "相似联系人";  //"Similar contact"
$l_company_defaultname = "无名称公司";  //"Company with no Name"
$l_contact_defaultname = "无姓联系人";  //"Contact with no Last name"
$l_same_company = "该被导入的公司似乎与这一个完全一样"; //"The imported company seems to be exactly the same as this one"
$l_auto_resolv = "自动化公司冲突管理。";  //"Automatic company conflict management."
$l_always_ask = "总是询问。";  //"Always ask."
$l_always_do_nothing = "如果一个公司完全一致，就不需要做什么。";  //"Do nothing if a company is identical."
$l_always_update_same = "如果该公司完全一致，总是更新。";  //"Always update if the company is identical."
$l_always_update_similar = "总是更新，如果该公司完全一致或者只有一个公司相似。";  //"Alway update if the company is identical or there is only one company which seems similar."
$l_always_insert = "总是创建公司，如果没有严格一致的公司。";  //"Always create a company if there is no strictly identical company."
$l_csvd_sc = ";";  //";"
$l_csvd_tab = "tab";  //"tab"

