<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Chinese                                                 //
//     - File     : password.inc                                             //
// 2004-03-25 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-10T13:59:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:02:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:20:01+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:49:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:50:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T14:58:21+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:01:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:04:37+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:12:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:14:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:23:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:34:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:43:06+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T15:44:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-10T16:32:41+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:53:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T14:54:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:00:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-09-11T15:01:06+02:00 using OBMtranslation (0.4.1)

$l_old_password = "原密码";  //"Current password"
$l_new_password = "新密码";  //"New password"
$l_new_password_bis = "确认密码";  //"Confirm new password"
$l_wrong_password = "原密码无效！";  //"The current password is not valid!"
$l_new_password_differ = "确认密码与新密码不匹配";   //"New password differ!"
$l_password_invalid = "新密码无效- 它必须包含4到12个字符（字母，数字 或者 -\$\&~#{([|_`^@);]+=}%!:/.,?<>\"）！";  //"The new password is invalid - it must be between 4 and 12 characters (alphanumeric or -\$\&~#{([|_`^@);]+=}%!:/.,?<>\")!"
$l_fill_password = "验证之前，您必须输入密码。";   //"You must enter password before validating."

