<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : settings.inc                                             //
// 1999-03-18 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_cur_settings = "您的当前设置";  //"Your current settings"
$l_auto_display = "自动列表显示";  //"Automatic listing display"
$l_submit = "确认";  //"Validate"
$l_cur_lang = "您的当前语言";  //"Your current language"
$l_cur_theme = "您的当前主题";  //"Your current theme"
$l_new_settings = "要改变您的设置，请在这里选择新参数";  //"To change your setup, select here the new parameters"
$l_set_lang = "选择您的语言";  //"Select your language"
$l_set_theme = "选择您的主题";  //"Choose your theme"
$l_set_menu = "菜单显示";  //"Menu display"
$l_set_rows = "# 每页显示的行数";  //"# Rows displayed per page"
$l_set_todo = "待办事项排列顺序";  //"Sort order for todo tasks"
$l_set_date_upd = "输入日期格式";  //"Input date format"
$l_set_date = "日期格式";  //"Date format"
$l_set_commentorder = "评论显示";  //"Comment display"
$l_set_display_days = "周视图中日历显示天数";  //"Calendar displayed days in week view"
$l_set_cal_interval = "日历时间间隔";  //"Calendar interval"
$l_set_cal_first_hour = "日历开始时间";  //"Calendar start hour"
$l_set_cal_last_hour = "日历结束时间";  //"Calendar end hour"
$l_set_cal_alert = "日历提醒(几分钟前)";  //"Calendar Alerts (minutes before)"
$l_set_csv_sep = "CSV导出分隔符";  //"CSV Export separator"
$l_set_debug = "调试级别";  //"Debugging level"
$l_send_mail = "接受会议邀请邮件";  //"Accept meeting invitation emails"
$l_send_mail_participation = "接受会议参与邮件";  //"Accept meeting participation emails"

$l_update_ok = "设置更新成功";  //"Settings updated successfully"

$l_da_iso = "yyyy-mm-dd";  //"yyyy-mm-dd"
$l_da_en = "mm/dd/yyyy";  //"mm/dd/yyyy"
$l_da_fr = "dd/mm/yyyy";  //"dd/mm/yyyy"
$l_da_txt = "dd month yyyy";  //"dd month yyyy"

$l_da_dmy = "dmy";  //dmy"
$l_da_mdy = "mdy";  //"mdy"

$l_deadline = "期限";  //"Deadline"

$l_me_txt = "文本";  //"text"
$l_me_ico = "图标";  //"icon"
$l_me_both = "文本+图标";  //"text+icon"

$l_co_chro = "按时间升序";  //"Chronological"
$l_co_rev = "按时间降序";  //"Reverse"

$l_csvd_sc = ";";  //";"
$l_csvd_tab = "tab键";  //"tab"
$l_with_weekend = "包括周末";  //"Including week-end"
$l_without_weekend = "不包括周末";  //"Without including week-end"
$l_set_public_fb = "公开您的忙/闲信息";  //"Publicize your free/busy information"
