<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                  //
//     - File     : time.inc                                                 //
// 1999-01-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_date_task = "任务日期";  //"Task date"
$l_task_del = "移除？";  // "Remove ?"
$l_delete = "移除任务";  //"Remove Tasks"
$l_length = "持续时间";  //"Duration"
$l_total = "总计";  //"Total"
$l_total_period = "本时期总计";  //"Total for this period"
$l_total_spent = "所用时间";  //"Time spent"
$l_total_before = "前期总计";  //"Total before period"
$l_total_after = "后期总计";  //"Total after period"
$l_missing = "剩余";  //"Missing"

$l_task_del = "移除";  //"Remove."
$l_from = "从";  // "from"
$l_to = "到"; //"to"
$l_see = "查看";  //"See"
$l_valid = "确认";  //"Validation"
$l_unvalid = "取消";  //"Cancel"
$l_add = "添加";  //"Add"
$l_update = "更新";  //"Update"
$l_fill = "填写"; //"Fill in"
$l_intern = "内部";  //"Intern" //internal
$l_task = "任务";  //"Task"
$l_duration = "持续时间";  //"Duration"
$l_searchtime_display = "显示任务列表选项";  //"Display options for tasks list"
$total_menu= "总结";  //"Summary"
$total_tasks = "任务总计";  //"Total tasks"
$total_companies="每家公司总计";  //"Total per company"
$total_projects="每个项目/交易总计";  //"Total per project/deal"
$l_pdf_settings="PDF设置";  //"PDF Settings"
$l_daysofweekshort = array (	'Sun',
				'Mon',
				'Tue',
				'Wed',
				'Thu',
				'Fri',
				'Sat');
$l_projects_manager = "项目负责人可以验证以下任务：";  //"Projects managers can validate tasks here:"
$l_found_task = "下面是本周完成并提交的任务：";  //"Here are completed and submited tasks for the current week:"
$l_found = "已找到任务。";  //"found tasks."
$l_no_found = "该用户无任务";  //"No task for this user"
$l_fill_addtask = "请填写本周任务。";  //"Fill in the tasks for this week."
$l_task_list = "目前的周任务列表"; // "List of current week tasks"
$l_admin_valid = "管理验证屏幕";  //"Admin validation screen"
$l_admin_empty = "这个月没有可用信息";  //"No information is available for this month"
$l_proj_stats = "参与目前项目";  //"Taking part in present projects"
$l_no_proj_stats = "此/这些人目前不参与项目"; //"This/These person(s) is/are currently not taking part in projects"
$l_tt_stats = "所花的时间分布在不同的任务类型";  //"Distribution of the time spent on different task types"
$l_no_tt_stats = "此/这些人没有使用时间管理"; //"This/Theser person(s) is/are not using the time management"
$l_j_select_day = "您必须选择一个日期。";  //"You must select a day."
$l_j_select_tasktype = "您必须选择一个任务类型。";  //"You must select a task type."
$l_j_select_project = "您必须选择一个收费业务的项目。";  //"You must select a projet with a billed task type."
$l_j_select_projecttask = "您必须选择一个项目任务。";  // "You must select a project task."
$l_delete_confirm = "确认删除任务？";  //"Confirm task(s) deletion ?"
$l_pdf_no_project_selected = "选择至少一个项目。";  //"Select at least a project."
$l_pdf_bad_date = "无效日期或日期格式。";  //"Invalid date or date format."
$l_pdf_com_date_format = "Y-m-d"; // "Y-m-d"/
$l_pdf_title = "活动报告";  //"Activity report"
$l_pdf_date = "文档生成于：";  //"Document generated on :"
$l_pdf_date_format = "Y-m-d H:i";  //"Y-m-d H:i"
$l_pdf_user = "同事： ";  //"Contributor : "
$l_pdf_visa_user = "同事验证";  //"Contributor Visa"
$l_pdf_visa_client = "客户验证";  //"Client Visa"
$l_pdf_visa_company = "任务负责人验证";  //"Mission Manager Visa"
$l_pdf_comments = "评论：";  // "Comments :"
$l_pdf_projects = "项目：";  //"Projects :"
$l_label = "标签";  //"Label"
$l_user = "用户";  //"User"

