<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Italiano                                                 //
//     - File     : time.inc                                                 //
// 2002-08-01 Augusto Fagioli                                                //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_taskdate="Data Operazione";
$l_tasktype = "Tipo Operazione";
$l_project = "Progetto:";
$l_delete = "Elimina  Operazioni";
$l_length = "Durata";
$l_total_length = "Durata totale";
$l_task_del = "Elimina.";
$l_user = "Utente";
$l_see = "Vedi";
$l_valid = "Conferma";
$l_add = "Aggiungi";
$l_modify = "Modifica";

$l_lastname = "Cognome";
$l_firstname = "Nome";
$l_kind = "Tipo";

$l_week_sel = "Settimana di ricerca";
$l_from_company = "&nbsp;&nbsp;Azienda";
$l_contact_select_company = "Seleziona la società del contatto.";
$l_week_prev = "Settimana precedente";
$l_week_next = "Prossima settimana";
$l_date = "Data:";
$l_task = "Operazione:";
$l_duration = "Durata:";

// Titres
$l_time = "Gestione del Tempo";

// Actions
$l_insert = "Registra il contatto";
$l_update = "Modifica il contatto";
$l_checkdelete = "Verifica o elimina il contatto";
$l_select_company = "Scegli l'azienda";
$l_pdf_settings = "PDF impostazioni";

// Messages
$l_projects_manager = "Projects managers conferma tasks qui:";
$l_check_samecontact = "Questi contatti sembrano simili al nuovo !";
$l_link_deal = "Il Contatto ha questo affari...";
$l_link_deal_no = "Il contatto non h affari ";
$l_link_list = "Il contatto è registrato in queste liste:";
$l_link_list_no = "il contatto non è presente nelle liste:";
$l_cant_delete = "Il contatto non può essere eliminato";
$l_can_delete = "Contatto eliminabile.";
$l_no_display = "Riempi i campi e click su < TROVA > per eseguire la ricerca.";
$l_found_task = "Operazioni della settimana:";
$l_found = "trovate operazioni.";
$l_no_found = "Nessuna operazione per l'utente";
$l_addtask_start = "Inserisci l'informazione per la settimana corrente. La durata è una frazione di giorno (tra  1/";
$l_addtask_end = " e 1).";
$l_modtask = "Modifica task:";
$l_total_day = "Vista giornaliera. Se il giorno è completo,<BR> conferma qui selezionando i giorni and validate form.";
$l_total_deal = "Lista per operazione:";
$l_delete_ok = "Contatto eliminato.";
$l_delete_error = "Eliminazione contatto fallita!";
$l_insert_ok = "Contatto creato.";
$l_insert_error = "Inserimento Contatto fallito !";
$l_update_ok = "Contatto modificato.";
$l_update_error = "Modifica contatto fallita!";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_fill_lastname = "Inserisci prima il nome.";
$l_fill_phone = "Inserisci prima il telefono.";
$l_delete_confirm = "Confermi eliminazione tasks?";
$l_j_check_phone = "Il numero di telefono non è corretto.";
$l_j_check_hphone = "Il numero di telefono personale non è corretto.";
$l_j_check_mphone = "Il numero di cellulare  non è corretto.";
$l_j_check_fax = "Il numero di fax  non è corretto.";
$l_j_check_email = "L'indirizzo email non è corretto.Verifica il dominio ";

// For the display preferences modification screen
$l_contact_display = "Opzioni di visualizzazione dell'elenco contatti.";

// PDF related strings
$l_pdf_no_project_selected = "Seleziona un minimo di un progetto.";
$l_pdf_bad_date = "Data o il formato della data non è valido.";
$l_pdf_com_date_format = "d/m/Y";
$l_pdf_title = "Relazione di attività";
$l_pdf_date = "Documento generato il :";
$l_pdf_date_format = "d/m/Y H:i";
$l_pdf_user = "Collaboratore : ";
$l_pdf_visa_user = "Collaboratore Visa";
$l_pdf_visa_client = "Client Visa";
$l_pdf_visa_company = "Missione manager";
$l_pdf_comments = "Commenti :";
$l_pdf_projects = "Progetti";
