=head1 NOM

OBM::Ldap::typeSystemUsers - Définition des fonctions permettant de gérer le type
'SYSTEMUSERS'.

=head1 DEPENDANCES

 use OBM::Parameters::common;
 use OBM::Parameters::ldapConf;
 require OBM::passwd;
 use Unicode::MapUTF8 qw(to_utf8 from_utf8 utf8_supported_charset);

=head1 DESCRIPTION

    use OBM::Ldap::typeSystemUsers;
    
Ce paquet implémente les fonctions de manipulations du type de données
'SYSTEMUSERS'.

Ce paquet défini les fonctions :

=over 4

=item B<initStruct( $ldapStruct, $parentDn )> : permet d'initialiser la
structure correspondante.
Retour : 1 si tout est ok, 0 sinon ;

=item B<getDbValues( $parentDn, $domainId )> : permet de créer les structures
en fonction des informations de la base de données OBM.
Retour : référence à un tableau contenant les différentes structures ;

=item B<createLdapEntry( $entry, $ldapEntry )> : permet de créer une entité LDAP
à partie d'une structure.
Retour : 1 si tout est ok, 0 sinon ;

=item B<updateLdapEntry( $entry, $ldapEntry )> : permet de mettre à jour une
entité LDAP par rapport à une structure.
Retour : 1 si tout est ok, 0 sinon.

=back

=cut
