=head1 NOM

OBM::Ldap::utils - Définition de fonctions utilles dans la gestion de plusieurs
types.

=head1 DEPENDANCES

 use Unicode::MapUTF8 qw(to_utf8 from_utf8 utf8_supported_charset);

=head1 DESCRIPTION

    use OBM::Ldap::utils;
    
Ce paquet implémente les fonctions de manipulations communes à la gestion de
plusieurs type.

Ce paquet défini les fonctions :

=over 4

=item B<modifyAttr( $newValue, $ldapEntry, $attr )> : permet de modifier
l'attribut 'B<attr>' de l'entité LDAP 'B<ldapEntry>' pour y placer si nécessaire
la valeur 'B<newValue>'.
Retour : 1 si il y a eu mise à jour, 0 sinon ;

=item B<modifyAttrList( $newValue, $ldapEntry, $attr )> : permet de modifier
l'attribut B<multi-évalué> 'B<attr>', de l'entité LDAP 'B<ldapEntry>', pour y
placer si nécessaire la nouvelle liste 'B<newValue>'.
Retour : 1 si il y a eu mise à jour, 0 sinon.

=back

=cut
