<script language="php">
////////////////////////////////////////////////////////////////////////////////
// OBM - Language :                                                           //
//     - File     : admin_ref.inc                                             //
// 2009-09-24                                                                 //
////////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-24T17:31:43+02:00 using OBMtranslation (0.4.1)


// lines below have been created with OBMtranslation (0.4.1) on 2009-09-24T17:31:43+02:00
$l_ctry_insert = ""; 
$l_ctry_cant_delete = ""; 
$l_dsrc_insert_error = ""; 
$l_dsrc_no = ""; 
$l_ctry_link_company_no = ""; 
$l_ctry_insert_error = ""; 
$l_tt_insert = ""; 
$l_iso_3166 = ""; 
$l_dsrc_manage = ""; 
$l_tt_update = ""; 
$l_j_ctry_create = ""; 
$l_j_ctry_update = ""; 
$l_tt_insert_ok = ""; 
$l_ctry_insert_ok = ""; 
$l_ctry_update = ""; 
$l_dsrc_delete = ""; 
$l_ctry_manage = ""; 
$l_tt_delete = ""; 
$l_tt_exist = ""; 
$l_tt_link_project_no = ""; 
$l_tt_update_error = ""; 
$l_j_ctry_delete = ""; 
$l_ctry_exist = ""; 
$l_dsrc_insert_ok = ""; 
$l_dsrc_link_contact = ""; 
$l_dsrc_can_delete = ""; 
$l_ctry_delete = ""; 
$l_ctry_new = ""; 
$l_tt_manage = ""; 
$l_ctry_link_contact = ""; 
$l_tt_update_ok = ""; 
$l_tt_link_project = ""; 
$l_dsrc_checkdelete = ""; 
$l_tt_link_time = ""; 
$l_tt_checkdelete = ""; 
$l_tt_delete_ok = ""; 
$l_dsrc_update_ok = ""; 
$l_dsrc_update_error = ""; 
$l_dsrc_cant_delete = ""; 
$l_j_dsrc_update = ""; 
$l_j_dsrc_create = ""; 
$l_tt_link_time_no = ""; 
$l_dsrc_link_company = ""; 
$l_dsrc_new = ""; 
$l_ctry_can_delete = ""; 
$l_dsrc_exist = ""; 
$l_dsrc_delete_ok = ""; 
$l_tt_delete_error = ""; 
$l_tt_new = ""; 
$l_tt_no = ""; 
$l_j_dsrc_delete = ""; 
$l_ctry_no = ""; 
$l_ctry_checkdelete = ""; 
$l_ctry_link_company = ""; 
$l_ctry_update_error = ""; 
$l_ctry_delete_error = ""; 
$l_tt_insert_error = ""; 
$l_tt_link_deal = ""; 
$l_tt_cant_delete = ""; 
$l_dsrc_link_company_no = ""; 
$l_ctry_update_ok = ""; 
$l_j_tt_update = ""; 
$l_j_tt_create = ""; 
$l_ctry_link_contact_no = ""; 
$l_ctry_delete_ok = ""; 
$l_tt_link_deal_no = ""; 
$l_dsrc_insert = ""; 
$l_dsrc_delete_error = ""; 
$l_dsrc_link_contact_no = ""; 
$l_dsrc_update = ""; 
$l_tt_can_delete = ""; 
$l_j_tt_delete = ""; 

