<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : German                                                   //
//     - File     : agenda.inc                                               //
// 2003/01/02 by Mehdi Rande                                                 //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
//////////////////////////////////////////////////////////////////////////////

$l_users = "Users";
$l_groups = "Groups";
$l_title = "Title";
$l_state = "State";
$l_none = "None";

$l_high = "High";
$l_low = "Low";
$l_medium = "Medium";

$l_timebegin = "Hour begin (HH:MM)";
$l_timebegin2 = "Hour begin";
$l_timeend = "Hour end (HH:MM)";
$l_timeend2 = "Hour end";
$l_occupied_day = "All day";

$l_format = "(AAAA-MM-JJ)";
$l_repeat = "Repetition";
$l_periodicity = "Periodicity";
$l_repeatkind = "Repetition kind";
$l_repeatdays = "Repetition day (weekly kind)";
$l_repeatdays2 = "Repetition day";

$l_date_repeatend = "Date end repetition";
$l_carac = "Propreties";
$l_force = "Force insertion";

$l_waiting_events = "waiting events";

$l_accepted = "Accepted";
$l_rejected = "Rejected";
$l_waiting  = "Waiting";
$l_short_accepted = "A";
$l_short_rejected = "R";
$l_short_waiting  = "W";

$l_daily = "daily";
$l_weekly = "weekly";
$l_monthlybyday = "monthly(day)";
$l_monthlybydate = "monthly(date)";
$l_yearly = "yearly";

$l_from = "from";
$l_to = "to";

$l_insert_ok = "Insertion successfull";
$l_update_ok = "Update successfull";
$l_update_warning = "Warning : Conflicts detected";
$l_insert_warning = "Warning : Conflicts detected";
$l_update_error = "Conflicts detected, update cancelled";
$l_insert_error = "Conflicts detected, insert cancelled";


// actions 
$l_insert = "Insert event";
$l_update = "Update event";
$l_validate = "Validate";
$l_accept = "Accept";
$l_reject = "Refuse";
$l_select = "Select";

// Messages 
$l_select_contacts = "You must select one contact";
$l_select_repeat_day = "You have to select the repetion day(s).";


$l_fill_title = "Please fill the label <Title>";
$l_fill_dateend = "Please fill the label <Date end>";
$l_fill_datebegin = "Please fill the label <Date begin>";
$l_incorect_datebegin = "<Date end> Format incorrect";
$l_incorect_dateend = "<Date begin> Format incorrect";
$l_incorect_repeat = "<Repetition date end> Format incorrect";
$l_incorect_begin_end = "Date end must be superior to Date begin";
$l_incorect_end_repeat = "Repetition date end must be superior than Date end";

$l_conflicts = "Conflicts detected";
$l_date = "Date";
$l_user = "User";
$l_force_all = "Force all";
$l_replace_all = "Replace all";
$l_cancel_all = "Cancel all";
$l_force_event = "Force";
$l_cancel_event = "Cancel";
$l_replace_event = "Replace";

$l_monday="Monthday";
$l_tuesday="Tuesday";
$l_wednesday="Wednesday";
$l_thursday="Thursday";
$l_friday="Friday";
$l_saturday="Saturday";
$l_sunday="Sunday";
$l_go_to = "Go to";
$l_waitings_events = " Waitings events";

$l_accept = "Accept";
$l_wait = "Waiting";
$l_refuse = "Refuse";
$l_change_state = "Currently state of the event";
			      
$l_repeat_update ="Update all repetition (only after this day)";
$l_calendar_visible = "Select calendars";
$l_calendar_displayed = "Calendars displayed";
$l_valid = "Validate";


?>
