<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : Deutsch (German)
//     - File     : common.inc
//     - Content  : common phrases of all language files
// 2001-07-20 / Fink / created
//////////////////////////////////////////////////////////////////////////////
$l_action = "Aktion" ;
$l_all = "Alle";
$l_back_tolist = "Zurück zur Anzeige" ;
$l_cancel = "Abbruch";
$l_comment = "Bemerkung";
$l_company = "Firma";
$l_email = "E-Mail";
$l_error_permission = "Sorry, keine Rechte auf diese Seite";
$l_error_visibility = "Sorry, private Informationen";
$l_find = "Suche";
$l_function = "Funktion";
$l_j_select_company =  "Sie müssen eine Firma auswählen!";

$l_last_company = "Letzte Firma";
$l_last_contact = "Letzter Kontakt";
$l_last_deal = "Letzer Vertrag";

$l_no_display = "Tragen Sie ihre Suchkriterien ein. Die Suche startet mit < $l_find > ";
$l_option_contacts = "Anzeige-Optionen Kontakte" ;
$l_options_dis = "Einstellung Anzeige-Optionen" ;
$l_order_dis = "Reihenfolge" ;
$l_query_display = "Einstellung" ;
$l_query_error = "Fehler beim Suchen!";
$l_subject = "Feld" ;
$l_town = "Ort";

$l_down_option = "Feld nach unten schieben" ;
$l_down_option_help  = "Klicken Sie auf das Symbol umd das Feld nach unten zu schieben" ;
$l_up_option = "Feld nach oben schieben" ;
$l_up_option_help = "Click on this button to move up the field" ;
$l_dis_obligatory = "Dieses Feld wird immer angezeigt" ;
$l_dis_obligatory_help = "Dieses Feld muß immer angezeigt werden" ;
$l_help_options = "Legende" ;
$l_ch_to_dis_no = "Not to display it fields" ;
$l_ch_to_dis_no_help = "That indicates the appropriate field is displayed<br>Click on this button if you don't want to display the field" ;
$l_ch_to_dis_yes = "To display it fields" ;
$l_ch_to_dis_yes_help = "That indicates the appropriate field is not displayed<br>Click on this button if you want to display the field" ;

