<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : Deutsch (German)
//     - File     : company.inc
// 1999-01-25 Pierre Baudracco
// 1999-12-06 / Fink / created from english version
// 2000-01-10 / Fink / check
// 2001-07    / Fink / check for version 0.4
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Labels and texts
$l_number = "Nummer";
$l_aka = "Also known as";
$l_company_name = "Firma";
$l_kind = "Firmenart";
$l_activity = "Activity";
$l_market = "Marketing manager";
$l_company_kind = "Firmenart";
$l_postcode = "Postleitzahl";
$l_contact_first = "K";
$l_newcontact_first = "NK";
$l_listdoc_first = "D";
$l_newdoc_first = "ND";
$l_address = "Adresse";
$l_postcode_first = "PLZ";
$l_expresspostal = "Eilzustellung";
$l_country = "Land";
$l_fax = "Telefax";
$l_web = "Web";
$l_contact_new = "Neuer Kontakt";
$l_deal_new = "Neuer Vertrag";
$l_kind_manage = "Verwaltung Firmenart";
$l_kind_exist = "Vorhandene Firmenarten";
$l_kind_new = "Neue Firmenart";
$l_internal = "Intern";
$l_act_manage = "Company Activity Management";
$l_act_exist = "Existing Activities";
$l_act_new = "New Activity";

// Titres
$l_company_detail = "Firmen-Daten";
$l_company_new = "Neue Firma";
$l_company_insert = "Firma anlegen";
$l_company_update = "Firma ändern";
$l_company_delete = "Firma löschen";
$l_company_admin = "Firma verwalten";

// Actions
$l_insert = "anlegen Firma";
$l_update = "ändern Firma";
$l_delete = "löschen Firma";
$l_kind_update = "ändern Firmenart";
$l_kind_delete = "löschen Firmenart";
$l_kind_insert = "anlegen Firmenart";
$l_act_update = "Update Activity";
$l_act_checkdelete = "Check or Delete Activity";
$l_act_delete = "Delete Activity";
$l_act_insert = "Insert Activity";

// Messages
$l_company_del_verif_error = " es sind noch Verträge zugeordnet: Firma kann nicht gelöscht werden";
$l_found = "Firmen gefunden.";
$l_no_found = "Keine Firma zum Suchkriterium gefunden!";
$l_delete_ok = "Firma gelöscht.";
$l_delete_error = "Fehler beim Löschen der Firma!";
$l_insert_ok = "Firma angelegt.";
$l_insert_error = "Fehler bei Neuanlage der Firma!";
$l_update_ok = "Firmendaten geändert.";
$l_update_error = "Fehler bei Änderung der Firmendaten!";
$l_kind_insert_ok = "Firmenart angelegt.";
$l_kind_insert_error = "Fehler bei Neuanlage Firmenart!";
$l_kind_delete_ok = "Firmenart gelöscht.";
$l_kind_delete_error = "Fehler beim Löschen der Firmenart!";
$l_kind_update_ok = "Firmenart geändert.";
$l_kind_update_error = "Fehler bei Änderung Firmenart!";
$l_kind_cant_delete = " mehrere(?) Firmenart vorhanden!";
$l_act_delete_ok = "Activity has been deleted successfully.";
$l_act_delete_error = "Activity deletion has failed !";
$l_act_insert_ok = "Activity has been inserted successfully.";
$l_act_insert_error = "Activity insertion has failed !";
$l_act_update_ok = "Activity has been updated successfully.";
$l_act_update_error = "Activity update has failed !";
$l_act_link_company = "These companies are referenced as";
$l_act_link_company_no = "No company from activity";
$l_act_cant_delete = "Activity can't be deleted !";
$l_act_can_delete = "Activity can be deleted.";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_fill_name = "\\n Firmenname muß eingetragen sein.";
$l_fill_number = "\\n Nummer muß eingetragen sein.";
$l_fill_postcode = "\\n Postleitzahl muß eingetragen sein.";
$l_fill_address = "\\n Adresse muß eingetragen sein.";
$l_fill_phone = "\\n Telefonnummer muß eingetragen sein.";
$l_delete_confirm = "Firma löschen?";
$lj_check_zip = "Postleitzahl ungültig";
$lj_check_phone = "Telefonnummer ungültig";
$lj_check_pphone = "Telefonnummer privat ungültig";
$lj_check_mphone = "Telefonnummer mobil ungültig";
$lj_check_fax = "Telefaxnummer ungültig";
$lj_check_email = "E-Mail-Adresse ungültig";
$lj_check_web = "Web-Adresse ungültig";
$mj_kind_delete = "Firmenart zum Löschen auswählen!";
$mj_kind_update = "Firmenart auswählen und neuen Namen eintragen!";
$mj_kind_create = "Neue Firmenart eintragen!";
$mj_kind_delete_confirm = "Firmenart löschen?";

// For the display parameters modification screen
$l_company_options = "Anzeige-Optionen für Firma"; 
