<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Deutsch (German)
//     - File     : contact.inc
// 1999-01-24 Pierre Baudracco
// 1999-12-06 / Fink / created from english version
// 2001-07    / Fink / check
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-24T17:31:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:23:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:28:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:35:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:36:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:40:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:43:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:45:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:45:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:47:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:48:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:53:55+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:03:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:04:46+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:06:07+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:07:26+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:08:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:10:39+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:17:42+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T12:23:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:02:48+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:06:12+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:18:45+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:22:03+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:30:54+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:33:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:35:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T14:37:52+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-09T15:15:52+02:00 using OBMtranslation (0.4.1)

$l_contact_name = "Name des Kontakts";
$l_from_company = "Firma";
$l_lastname = "Nachname";
$l_firstname = "Vorname";
$l_market = "Beauftragte"; 
$l_tel = "Telefon";
$l_telp = "Telefon privat";
$l_telm = "Telefon mobil";
$l_telother = "weiteres Telefon";
$l_minitelp = "(Home)";
$l_minitelm = "(Mobile)";
$l_mobilephone = "Mobile";
$l_homephone = "Home";
$l_address = "Adresse";
$l_contact_select_company = "Firmenauswahl für den Kontakt";
$l_comment2 = "Kommentar 2";
$l_comment3 = "Kommentar 3";
$l_contact = "Kontakt";
$l_contact_detail = "Kontakt-Detail";
$l_contact_new_company = "Firma für neuen Kontakt";
$l_contact_new = "Neuer Kontakt";
$l_contact_insert = "Kontakt anlegen";
$l_contact_update = "Kontakt ändern";
$l_contact_delete = "Kontakt löschen";
$l_insert = "Kontakt speichern"; 
$l_update = "ändern Kontakt";
$l_delete = "Kontakt löschen "; 
$l_select_company = "Firmenauswahl";
$l_add_comment2 = "Addieren ein kommentar 2"; 
$l_upd_comment2 = "Aktualisieren den Kommentar 2";
$l_add_comment3 = "Addieren ein Kommentar 3"; 
$l_upd_comment3 = "Aktualisieren den kommentar 3";
$l_copy = "Kopieren"; 
$l_contact_del_verif_error = " Verträge sind noch zugeordnet: Kontakt kann nicht gelöscht werden";
$l_found = "gefundene Kontakte ";
$l_no_found = "Keine Kontakte entsprechen diesen Kriterien !"; 
$l_fill_lastname = "Sie müssen den Namen füllen, bevor die Validierung."; 
$l_fill_phone = "Sie müssen das Telefon informieren, bevor eingeben."; 
$l_delete_confirm = "Bestätigen Sie die Löschung des Kontakt ?";
$lj_check_phone = "The phone number is not valid.";
$lj_check_pphone = "The personal phone number is not valid.";
$lj_check_mphone = "The mobile phone number is not valid.";
$lj_check_fax = "The fax number is not valid.";
$lj_check_email = "The email adress is not valid.";
$l_contact_options = "Anzeige-Optionen Kontakte";
$l_date = "Datum";
$l_suffix = "Suffix";
$l_link_deal_no = "Der Kontakt ist nicht im Geschäft verwiesen";
$l_timeupdate = "Aktualisierungsdatum";
$l_j_check_mphone = "Die Handy-Nummer ist falsch.";
$l_addressbook = "Adressbuch";
$l_kind_delete = "Entfernen Art";
$l_upd_comment1 = "Kommentar bearbeiten";
$l_link_contract = "Der Kontakt ist durch Verträge verwiesen";
$l_publication_title = "Titel";
$l_kind_exist = "bestehenden Arten";
$l_link_publication_no = "Der Kontakt ist nicht die Veröffentlichungen abonniert";
$l_date_after = "Nach Datum";
$l_vcard = "Vcard";
$l_comment1 = "Kommentar";
$l_code = "Code";
$l_vcf_file = "VCF-Datei zu importieren";
$l_phone_labels = array ('HOME_VOICE' => 'Tel (Heim)', 'WORK_VOICE' => 'Tel (Büro)', 'CELL_VOICE' => 'Handy', 'HOME_FAX' => 'Fax (Heim)','WORK_FAX' => 'Fax (Büro)', 'PAGER' => 'Pager', 'OTHER' => 'Andere tel');
$l_other_infos = "Weitere Informationen";
$l_function = "Merkmal";
$l_j_select_contact = "Sie müssen einen Kontakt wählen !";
$l_no_display = "Informieren Sie die gewünschten Kriterien ein und klicken Sie auf <Suchen>, um eine Liste der Kontakte zu haben.";
$l_link_publication = "Der Kontakt ist die Veröffentlichungen abonniert.";
$l_address_labels = array ('HOME' => 'Heim', 'WORK' => 'Büro', 'OTHER' => 'Andere');
$l_quantity = "Quantität";
$l_newsletter = "Newsletter";
$l_subscription = "Abonnement";
$l_contact_display = "Anzeigeoptionen Kontaktlisten";
$l_birthday_event_title = "Datum der Geburt % s";
$l_minihphone = "(Mich)";
$l_checkdelete = "Check oder Kontakt löschen";
$l_email_labels = array ('INTERNET' => 'Internet', 'OTHER' => 'Andere');
$l_no_date = "Nicht angegeben";
$l_kind_checkdelete = "Aktivieren oder Entfernen Art";
$l_no_export = "Keine private Kontakte zu exportieren !";
$l_sync_contact = "PDA-Synchronisierung";
$l_kind_can_delete = "Die Gattung kann gelöscht werden.";
$l_j_kind_update = "Sie müssen eine Kategorie auswählen und eine Veränderung einspeisen bevor !"; 
$l_j_check_phone = "Die Telefonnummer ist nicht korrekt."; 
$l_subscription_list = "Abonnements"; 
$l_category3 = "Kategorie 3"; 
$l_timecreate = "Erschaffungsdatum"; 
$l_website_labels = array ( 'URL' => 'Website', 'Blog' => "Onlinetagebuch ',' Other '=>' Andere '); 
$l_kind_update = "Abändern die Gattung"; 
$l_category4 = "Kategorie 4"; 
$l_kind_new = "Neue Gattung"; 
$l_anniversary = "Geburtstag"; 
$l_link_contract_no = "Der Kontakt wird nicht in den Verträgen verwiesen"; 
$l_recept = "Empfangsmodus"; 
$l_fill_company = "Sie müssen ein Unternehmen auswählen, bevor begehen."; 
$l_minimphone = "(Handy)"; 
$l_mailing_ok = "Aktiviert für Mailing"; 
$l_category5 = "Kategorie 5"; 
$l_check_samecontact = "Diese Kontakte scheinen ähnlich mit neuen Eintrag !"; 
$l_letter = "Briefkopf"; 
$l_subscription_new = "Neue Abonnement"; 
$l_j_check_hphone = "Die persönliche Telefonnummer ist nicht korrekt."; 
$l_j_kind_create = "Sie müssen alle Informationen von der Gattung geben, um sie zu schaffen !"; 
$l_no_found_subscription = "Kein Abo im Zusammenhang mit diesem Kontakt !"; 
$l_kind_link_contact_no = "Keine derartigen Kontakte"; 
$l_mailing_ok_only = "Aktiviert nur zum Versenden"; 
$l_spouse = "Ehepartner"; 
$l_middlename = "Zweite Vorname"; 
$l_news = "Nachrichten"; 
$l_desync = "Deaktivieren der Synchronisation des Kontakts"; 
$l_anniversary_event_title = "Geburtstag von %s"; 
$l_link_deal = "Der Kontakt ist im Geschäft verwiesen"; 
$l_download_contact_card = "Kontaktdaten herunterladen"; 
$l_label = "Label"; 
$l_j_check_email = "Die E-Mail ist nicht gültig. Überprüfen Sie das Feld."; 
$l_j_check_date = "Füllen Sie den Tag mit einem gültigen Datum"; 
$l_err_length_express_postal = "Das Feld 'Cedex' muss maximal 16 Zeichen lang sein."; 
$l_private_only = "nur Private Kontakte "; 
$l_header = "Kopfbrief"; 
$l_kind_insert = "Erstellen die Gattung"; 
$l_sync = "Aktivieren Sie die Synchronisierung des Kontakts"; 
$l_link_list_no = "Der Kontakt wird nicht in den Listen referenziert"; 
$l_synchronisation = "Abonnement"; 
$l_assistant = "Anwesende"; 
$l_kind_manage = "Gattung-Management"; 
$l_j_kind_delete = "Wählen Sie eine Gattung, um zu überprüfen oder zu löschen!"; 
$l_mailing_ok_first = "E-Mail"; 
$l_kind_link_contact = "Diese Kontakte sind der Gattung"; 
$l_exportation = "Exportieren"; 
$l_email_other = "Andere E-mail"; 
$l_link_list = "Der Kontakt wird in Listen gespeichert"; 
$l_add_comment1 = "Addieren ein Kommentar"; 
$l_email = "@"; 
$l_date_before = "Datum bevor"; 
$l_can_delete = "Kontakt kann gelöscht werden."; 
$l_cant_delete = "Der Kontakt kann nicht gelöscht werden !"; 
$l_j_check_fax = "Faxnummer ist ungültig."; 
$l_birthday = "Geburtsdatum"; 
$l_kind_cant_delete = "Die Gattung kann nicht gelöscht werden !"; 
$l_renewal = "Automatische Verlängerung"; 

