<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : Deutsch (German)
//     - File     : header.inc
// 1999-01-27 Pierre Baudracco
// 1999-12-06 / Fink / created from english version
// 2001-07    / Fink / check for version 0.4
//////////////////////////////////////////////////////////////////////////////

$l_header_settings = "Einstellungen";
$l_header_company = "Firmen";
$l_header_contact = "Kontakte";
$l_header_deal = "Verträge";
$l_header_list = "Maillisten";
$l_header_user = "Benutzer";
$l_header_admin = "Administration";
$l_header_computer = "Computer";

$l_header_title_computer = "Computer" ;
$l_header_title_settings = "Einstellungen";
$l_header_title_company = "Firma";
$l_header_title_contact = "Kontakt";
$l_header_title_deal = "Vertrag";
$l_header_title_list = "Liste";
$l_header_title_user = "Benutzer";
$l_header_title_admin = "Administration";

$l_header_new_f = "Neu";
$l_header_new = "Neu";
$l_header_find = "Suche";

$l_header_new_parent = "Neuer Hauptvertrag";
$l_header_find_parent = "Suche Hauptvertrag";

$l_header_agenda = "Agenda";
$l_header_title_agenda = "AGENDA";
$l_header_day = "Jour";
$l_header_week = "Semaine";
$l_header_month = "Mois";
$l_header_new_event = "Nouveau rdv";
