<script language="php">
////////////////////////////////////////////////////////////////////////////////
// OBM - Language :                                                           //
//     - File     : mailshare.inc                                             //
// 2009-09-24                                                                 //
////////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-24T17:31:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-02T09:50:20+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-02T09:50:40+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-02T10:28:31+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-02T10:49:11+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T15:36:14+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:05:34+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:07:22+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:12:00+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:12:59+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:23:38+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:28:02+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:35:18+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:36:57+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:40:24+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:43:36+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:45:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:45:15+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:47:13+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:48:50+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-08T16:53:55+02:00 using OBMtranslation (0.4.1)

$l_mail_server = "E-Mail-Server";
$l_err_mailshare_name_exist = "Der Name des gemeinsamen Mail ist schön verwendet";
$l_err_mailshare_email = "Die eingegebene E-Mail ist ungültig !";
$l_name_error = "Der Name muss angemessen informiert werden ! Es muss nicht keine Leer-oder Sonderzeichen enthalten.";
$l_toggle_public_read = "Dies führt dazu, dass jeder den Inhalt der gemeinsamen Mail ändern können. Wollen Sie weitergehen ?";
$l_toggle_public_admin = "Dies führt dazu, dass jeder die Rechte der gemeinsamen Mail ändern können. Wollen Sie weitergehen ?";
$l_name_in_use = "Der Name ist bereits mit einem anderen freigegebenen Verzeichnis verwendet !";
$l_err_mailshare_name_empty = "Der Name der gemeinsamen Mail muss ausgefüllt werden.";
$l_err_mailshare_email_exist = "Die E-Mail wird bereits verwendet !";
$l_found = "gemeinsamen Mail gefunden";
$l_err_mailshare_email_empty = "Die E-Mail-Adresse muss eingeben werden !";
$l_no_found = "Keine gemeinsame Mail entsprechen diesen Kriterien."; 
$l_cant_delete = "Gemainsame Mail können nicht gelöscht werden !"; 
$l_no_display = "Informieren Sie die gewünschten Kriterien ein und klicken Sie auf \"Suchen> um gemeinsamen entsprechenden E-Mail zu haben."; 
$l_err_mailshare_quota = "Die Quote der gemeinsamen Mail ist ungültig!"; 
$l_check_samemailshare = "Diese gemeinsame Mail erscheinen ähnlich mit der ergriffenen"; 
$l_toggle_public_access = "";
$l_mailshare_display = "Anzeigeoptionen der Liste der gemeinsamen Mail"; 
$l_err_mailshare_uemail_exist = "Die E-mail adresse wird mehrmals ergriffen !"; 
$l_toggle_public_write = "Dies führt dazu, dass jeder den Inhalt der gemeinsamen Mail bearbeiten werden können. Wollen Sie weitergehen ?"; 
$l_can_delete = "Der gemeinsame Mail kann gelöscht werden."; 

