<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : English                                                   //
//     - File     : organizationalchart.inc                                  //
// 2007-02-26 David PHAN                                                     //
///////////////////////////////////////////////////////////////////////////////
// $Id: organizationalchart.inc,v 1.17 2007/02/14 15:18:54 flo Exp $ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-24T17:31:43+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-13T09:16:29+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-13T09:20:17+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-13T09:25:08+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-13T09:48:10+02:00 using OBMtranslation (0.4.1)
// Modified on 2009-10-13T10:32:12+02:00 using OBMtranslation (0.4.1)

$l_detail = "Detail";
$l_title = "Title";
$l_add_child_tooltip = "Add a child";
$l_zoom = "Zoom";
$l_zoom_big = "Big";
$l_zoom_small = "Small";
$l_outline = "Outline";
$l_insert = "Insert organizational chart";
$l_update = "update organizational chart";
$l_ldif_export = "LDIF Export";
$l_svg_export = "SVG Export";
$l_no_display = "Fill the search fields and press < Find > to retrieve the organizational chart";
$l_found = "organizational charts found";
$l_no_found = "No organizational chart found matching the query !";
$l_can_delete = "The organizational chart can be deleted";
$l_cant_delete = "The organizational chart can't be deleted";
$l_fill_name = "You have to fill the organizational chart name before submitting.";
$l_fill_ogroup_name = "You have to fill the all node name before submitting.";
$l_js_delete_node = "Do you realy want to delete this node ?";
$l_organizationalchart_display = "Display options for organizational charts lists";
$l_js_delete_chart = "Bestätigen Sie das Löschen dieses Organisationsplans ?"; 
$l_pdf_export = "PDF-Export"; 

