<script language="php">
////////////////////////////////////////////////////////////////////////////////
// OBM - Language :                                                           //
//     - File     : resourcegroup.inc                                         //
// 2009-09-24                                                                 //
////////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-24T17:31:43+02:00 using OBMtranslation (0.4.1)


// lines below have been created with OBMtranslation (0.4.1) on 2009-09-24T17:31:43+02:00
$l_qty = ""; 
$l_update = ""; 
$l_resourcegroup_member = ""; 
$l_no_resource_added = ""; 
$l_cant_delete_system = ""; 
$l_resourcegroup_resource = ""; 
$l_resourcegroup_exists = ""; 
$l_no_resource = ""; 
$l_delete = ""; 
$l_email_exist = ""; 
$l_no_resourcegroup_added = ""; 
$l_resourcegroups = ""; 
$l_add_resource = ""; 
$l_del_resourcegroup_sel = ""; 
$l_cant_delete_public = ""; 
$l_nb_resource = ""; 
$l_found = ""; 
$l_fill_name = ""; 
$l_j_check_email = ""; 
$l_no_found = ""; 
$l_resourcegroup = ""; 
$l_warn_delete = ""; 
$l_add_resourcegroup = ""; 
$l_no_resource_deleted = ""; 
$l_no_resourcegroup_deleted = ""; 
$l_insert = ""; 
$l_no_display = ""; 
$l_resource_member = ""; 
$l_resourcegroup_removed = ""; 
$l_resourcegroup_display = ""; 
$l_del_resource_sel = ""; 
$l_resourcegroup_added = ""; 
$l_check_sameresourcegroup = ""; 
$l_resource_display = ""; 
$l_add = ""; 
$l_no_resourcegroup_resourcegroup = ""; 
$l_resource_added = ""; 
$l_resource_removed = ""; 

