<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Deutsch (German)
//     - File     : settings.inc
// 1999-03-18 Pierre Baudracco
// 1999-12-06 / Fink / created from english version
// 2001-07    / Fink / check for version 0.4
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////
// Modified on 2009-09-24T17:31:43+02:00 using OBMtranslation (0.4.1)

$l_settings = "Einstellungen";
$l_cur_settings = "Aktuelle Einstellungen";
$l_auto_display = "immer Liste aller Werte anzeigen";
$l_submit = "Bestätigung";
$l_cur_lang = "aktive Sprachwahl";
$l_cur_theme = "aktive Themenwahl";
$l_new_settings = "Wählen Sie die neuen Einstellungen";
$l_set_lang = "Sprachwahl";
$l_set_theme = "Themenwahl";
$l_set_rows = "Anzahl Anzeigezeilen/Seite";
$l_set_date = "Date format";
$l_set_cal_interval = "Kalenderanzeige";
$l_set_menu = "Menu display";
$l_set_debug = "Debugging level";
$l_send_mail = "E-Mails akzeptieren";
$l_update_ok = "Settings updated successfully";
$l_da_iso = "yyyy-mm-dd";
$l_da_en = "mm/dd/yyyy";
$l_da_fr = "dd/mm/yyyy";
$l_da_txt = "dd month yyyy";
$l_da_dmy = "dmy";
$l_da_mdy = "mdy";
$l_me_txt = "text";
$l_me_ico = "icon";
$l_me_both = "text+icon";
$l_co_chro = "Chronologisch";
$l_co_rev = "Invers";
$l_csvd_sc = ";";
$l_csvd_tab = "tab";

// lines below have been created with OBMtranslation (0.4.1) on 2009-09-24T17:31:43+02:00
$l_set_display_days = ""; 
$l_set_cal_last_hour = ""; 
$l_without_weekend = ""; 
$l_set_cal_first_hour = ""; 
$l_set_date_upd = ""; 
$l_set_commentorder = ""; 
$l_send_mail_participation = ""; 
$l_with_weekend = ""; 
$l_set_csv_sep = ""; 
$l_deadline = ""; 
$l_set_todo = ""; 

