<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : Deutsch (German)
//     - File     : settings.inc
// 1999-03-18 Pierre Baudracco
// 1999-12-06 / Fink / created from english version
// 2001-07    / Fink / check for version 0.4
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_settings = "Einstellungen";
$l_cur_settings = "Aktuelle Einstellungen";
$l_auto_display = "immer Liste aller Werte anzeigen";
$l_submit = "Bestätigung";
$l_cur_lang = "aktive Sprachwahl";
$l_cur_theme = "aktive Themenwahl";
$l_new_settings = "Wählen Sie die neuen Einstellungen";
$l_set_lang = "Sprachwahl";
$l_set_theme = "Themenwahl";
$l_set_rows = "Anzahl Anzeigezeilen/Seite";
$l_set_date = "Date format";
$l_set_debug = "Debugging level";

$l_dg_id = "Id";
$l_dg_param = "Parameters";
$l_dg_sql = "SQL";

$l_da_iso = "yyyy-mm-dd";
$l_da_en = "mm/dd/yyyy";
$l_da_fr = "dd/mm/yyyy";
$l_da_txt = "dd month yyyy";
