<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : account.inc                                              //
// 2001-07-31 Nicolas Roman                                                  //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Labels et textes
$l_label_start = "Début du Label";
$l_bank = "Banque"; 
$l_number = "Numéro";
$l_balance = "Solde";
$l_initial_balance = "Solde Initial";
$l_choose_balance_date = "Date de calcul du Solde";
$l_expected_date = "Date Prévisionnelle";
$l_amount = "Montant";

$l_include_expected = "Inclure les opérations prévisionnelles ?";
$l_in_total ="Total des entrées";
$l_out_total = "Total des sorties";
$l_total ="Solde Estimé";
$l_old_balance = "Solde Actuel";
$l_nb_expected_used = " opérations prévisionnelles utilisées pour le calcul.";
$l_expected = "prévisionnel";
$l_used_payments = "Paiement utilisés pour calculer le solde";
$l_used_expected_payments = "Paiement prévisionnels utilisés pour calculer le solde";
$l_expected_payments = "Paiements prévisionnels";
$l_payments = "Paiements";
$l_totals = "Totaux";

// Actions
$l_insert = "Insérer le Compte";
$l_update = "Mettre à jour le Compte";
$l_delete = "Supprimer le Compte";
$l_delete_confirm = "Etes vous sur de vouloir supprimer ce Compte ?";
$l_compute_balance = "Calculer le solde";

// Messages 
$l_no_display = "Remplissez les critères de recherche et appuyez sur <$l_find> pour lancer la recherche";
$l_found = "Compte(s) trouvé(s).";
$l_no_found="Aucun Compte ne correspond à votre requête";
$l_impossible_deletion = " paiements sont liés à ce compte. La suppression est impossible"; // must be used with the number of payments leading...

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_check_number = "Le numéro du compte n\'est pas valide !";
$l_fill_number = "Vous devez fournir un numéro de compte !";
$l_fill_bank = "Vous devez renseigner le champ banque !";
$l_confirm_no_bank="Ce Compte n\\'est associé à aucune banque. Cliquez sur OK pour confirmer .";

// For the display parameters modification screen
$l_account_options = "Options d'affichage pour les listes de Comptes"; 
$l_payment_options = "Options d'affichage pour les listes de Paiements"; 
$l_options_dis = "Options d'affichage" ;
