<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - File : admin_ref.inc                                                //
//     - Desc : French language for Admin Referential                        //
// 2003-12-05 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

// Data Source
$l_dsrc_manage = "Gestion des sources de données";
$l_dsrc_exist = "Sources de données existantes";
$l_dsrc_new = "Nouvelle source de données";
$l_dsrc_no = "Pas de source de données définies";
$l_dsrc_update = "Modifier la source de données";
$l_dsrc_checkdelete = "Vérifier ou Supprimer la source de données";
$l_dsrc_delete = "Supprimer la source de données";
$l_dsrc_insert = "Créer la source de données";

$l_dsrc_delete_ok = "La suppression de la source de données a été correctement effectuée.";
$l_dsrc_delete_error = "La suppression de la source de données a échoué !";
$l_dsrc_insert_ok = "L'insertion de la source de données a été correctement effectuée.";
$l_dsrc_insert_error = "L'insertion de la source de données a échoué !";
$l_dsrc_update_ok = "La modification de la source de données a été correctement effectuée";
$l_dsrc_update_error = "La modification de la source de données a échoué !";

$l_dsrc_link_company = "Ces sociétés sont de la source de données";
$l_dsrc_link_company_no = "Pas de sociétés de la source de données";
$l_dsrc_link_contact = "Ces contacts sont de la source de données";
$l_dsrc_link_contact_no = "Pas de contacts de la source de données";
$l_dsrc_cant_delete = "La source de données ne peut être supprimé !";
$l_dsrc_can_delete = "La source de données peut être supprimé.";

$l_j_dsrc_delete = "Sélectionnez une source de données pour la vérifier ou supprimer !";
$l_j_dsrc_update = "Vous devez sélectionner une source de données et entrer une modification avant de valider !";
$l_j_dsrc_create = "Vous devez saisir un nom de source de données pour la créer !";

// Country
$l_ctry_manage = "Gestion des pays";
$l_ctry_exist = "Pays existants";
$l_ctry_new = "Nouveau pays";
$l_ctry_no = "Pas de pays définis";
$l_ctry_update = "Modifier le pays";
$l_ctry_checkdelete = "Vérifier ou Supprimer le pays";
$l_ctry_delete = "Supprimer le pays";
$l_ctry_insert = "Créer le pays";

$l_ctry_delete_ok = "La suppression du pays a été correctement effectuée.";
$l_ctry_delete_error = "La suppression du pays a échoué !";
$l_ctry_insert_ok = "L'insertion du pays a été correctement effectuée.";
$l_ctry_insert_error = "L'insertion du pays a échoué !";
$l_ctry_update_ok = "La modification du pays a été correctement effectuée";
$l_ctry_update_error = "La modification du pays a échoué !";

$l_ctry_link_company = "Ces sociétés sont du pays";
$l_ctry_link_company_no = "Pas de sociétés du pays";
$l_ctry_link_contact = "Ces contacts sont du pays";
$l_ctry_link_contact_no = "Pas de contacts du pays";
$l_ctry_cant_delete = "Le pays ne peut être supprimé !";
$l_ctry_can_delete = "Le pays peut être supprimé.";

$l_j_ctry_delete = "Sélectionnez un pays pour le vérifier ou supprimer !";
$l_j_ctry_update = "Vous devez sélectionner un pays et entrer une modification avant de valider !";
$l_j_ctry_create = "Vous devez saisir un nom de pays pour le créer !";

$l_iso_3166 = "Code Iso 3166";

// Task Type
$l_tt_manage = "Gestion des types de tâche";
$l_tt_exist = "Types de tâche existants";
$l_tt_new = "Nouveau";
$l_tt_no = "Pas de type de tâche définis";
$l_tt_update = "Modifier le type de tâche";
$l_tt_checkdelete = "Vérifier ou Supprimer le type de tâche";
$l_tt_delete = "Supprimer le type de tâche";
$l_tt_insert = "Créer le type de tâche";

$l_tt_delete_ok = "La suppression du type de tâche a été correctement effectuée.";
$l_tt_delete_error = "La suppression du type de tâche a échoué !";
$l_tt_insert_ok = "L'insertion du type de tâche a été correctement effectuée.";
$l_tt_insert_error = "L'insertion du type de tâche a échoué !";
$l_tt_update_ok = "La modification du type de tâche a été correctement effectuée";
$l_tt_update_error = "La modification du type de tâche a échoué !";

$l_tt_link_deal = "Ces affaires sont du type de tâche";
$l_tt_link_deal_no = "Pas d'affaire du type de tâche";
$l_tt_link_project = "Ces projets sont du type de tâche";
$l_tt_link_project_no = "Pas de projet du type de tâche";
$l_tt_link_time = "Le type de tâche est référencé dans la gestion du temps";
$l_tt_link_time_no = "Le type de tâche n'est pas référencé dans la gestion du temps";
$l_tt_cant_delete = "Le type de tâche ne peut être supprimé !";
$l_tt_can_delete = "Le type de tâche peut être supprimé.";

$l_j_tt_delete = "Sélectionnez un type de tâche pour le vérifier ou supprimer !";
$l_j_tt_update = "Vous devez sélectionner un type de tâche et entrer une modification avant de valider !";
$l_j_tt_create = "Vous devez saisir un nom de type de tâche pour le créer !";
