<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : admin.inc                                                //
// 2001-12-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// labels
$l_user_pref = "Préférences des utilisateurs";
$l_user_pref_update = "Mise à jour de toutes les préférences utilisateurs avec les valeurs par défaut";
$l_user_pref_update_one = "Mise à jour de la préférence pour tous les utilisateurs (+ valeur par défaut)";

// Titles
$l_execute = "Exécute action";
$l_help = "Aide";

// Messages (+ javascript)
$l_update_ok = "Mise à jour des préférences correctement effectuée.";
$l_update_error = "La mise à jour des préférences a échoué !";
