<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : admin.inc                                                //
// 2001-12-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id //
///////////////////////////////////////////////////////////////////////////////

// labels
$l_check = "Vérifications";
$l_version = "version d'OBM";
$l_database_server = "Serveur SQL";
$l_database = "Base de données";
$l_host = "Hôte";
$l_session_stats = "Statistiques des Sessions";
$l_date = "Date";
$l_user_session = " Entrées dans ActiveUserObm";
$l_active_user = "Utilisateurs actuellement actifs";
$l_login_date = "Date de login";
$l_last_acces = "Dernier accès";
$l_nb_connec = "Nombre de hits";
$l_last_page = "Dernière page consultée";
$l_user_ip = "IP";

// Titles
$l_admin = "Admin";
$l_admin_lang = "Admin Langue";

// Actions
$l_execute = "Exécute action";
$l_help = "Aide";

