<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : calendar.inc                                             //
// 2001-06-28 by AliaSource                                                  //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
//////////////////////////////////////////////////////////////////////////////

$l_calendar = "Calendrier";
$l_attendees = "Participants";
$l_users = "Utilisateurs";
$l_owner = "Organisateur";
$l_resources = "Ressources";
$l_free_resources = "Resources libres : ";
$l_groups = "Groupes";
$l_title = "Titre";
$l_location = "Lieu";
$l_details = "Détailler";
$l_private_description = "Cet événement est personnel. Impossible de voir le détail.";
$l_high = "Haute";
$l_low = "Basse";
$l_medium = "Normale";
$l_go = "Voir";
$l_occupied_day = "Journée entière";
$l_event_duration = "Durée de la réunion";
$l_repeat = "Répétition";
$l_periodicity = "Fréquence";
$l_repeatkind = "Type de répétition";
$l_repeatdays = "Jours de répétition (type hebdomadaire)";
$l_repeatdays2 = "Jours de répétition";
$l_user_right = "Gérer les droits de";
$l_date_repeatend = "Fin de répétition";
$l_carac = "Propriétés";
$l_force = "Forcer l'insertion de l'événement";
$l_group_members = "Membres du groupe";
$l_everybody = "Tout le monde";
$l_everyresources = "Toutes les ressources";
$l_all_day = "Toute la journée";
$l_begin = "Début";
$l_end = "Fin";
$l_link_events = " événements liés à cette catégorie.";
$l_waiting_events = "Rendez-vous en attente";
$l_free = "Libre mais restreint";
$l_possible = "Libre";
$l_occupied = "Non disponible";
$l_meeting_legend = "Légende";
$l_selection = "Sélection";
$l_repeatfrequency = "Fréquence";
$l_accepted = "Accepté";
$l_rejected = "Rejeté";
$l_waiting  = "En attente de confirmation";
$l_short_accepted = "A";
$l_short_rejected = "R";
$l_short_waiting  = "Att";
$l_wait = "En attente";
$l_exception = "Exceptions";
$l_alerts = "Alertes";
$l_alerts_time = "Alertes (minutes avant)";
$l_items = "Accessoires";
$l_events = "Événements";
$l_daily = "quotidienne";
$l_daily_unit = "Tous les %s jours";
$l_weekly = "hebdomadaire";
$l_weekly_unit = "Toutes les %s semaines";
$l_monthlybyday = "mensuelle(jour)";
$l_monthlybyday_unit = "Tous les %s mois";
$l_monthlybydate = "mensuelle(date)";
$l_monthlybydate_unit = "Tous les %s mois";
$l_yearly = "annuelle";
$l_yearly_unit = "Tous les %s ans";
$l_task = "Tache";
$l_category_filter = "Filtrer par catégorie";
$l_from = "du";
$l_to = "au";
$l_periodic = "Périodique";

$l_conflicts = "Conflit(s) rencontré(s)";
$l_date = "Date";
$l_user = "Utilisateur";
$l_back_mono = "Revenir à ma vue";
$l_edit = "Editer";

$l_collapse_all = "Tout réduire";
$l_expand_all = "Tout développer";
$l_today_date = "Date du jour";
// actions 
$l_meeting_perform = "Rechercher les créneaux libres";
$l_insert = "Enregistrer le rdv";
$l_accept = "Accepter";
$l_reject = "Refuser";
$l_select = "Sélectionner";
$l_select_group = "Choisir groupe";
$l_repeat_update = "Mettre à jour toutes les répétitions à venir";
$l_go_to = "Aller à";
$l_refuse = "Refuser";
$l_state = "Partcipation";
$l_change_state = "Votre participation à l'évenement";
$l_force_insert = "Forcer l'insertion";
$l_refuse_insert = "Refuser l'évenement";
$l_cancel_insert = "Ne rien faire";
$l_too_much_user = "Vous ne pouvez sélectionner au maximum que six utilisateurs";
$l_too_much_resource = "Vous ne pouvez sélectionner au maximum que six ressources";
$l_update_warning = "Attention des conflits ont été détectés";
$l_insert_warning = "Attention des conflits ont été détectés";
$l_update_error = "Des conflits ont été détectés, mise à jour annulée";
$l_insert_error = "Des conflits ont été détectés, insertion annulée";
$l_sendamail = "Forcer la notification par mail";
$l_calendar_select_group = "Sélectionner les groupes.";
$l_A = "A";
$l_W = "E";
$l_R = "R";

$l_view = "Vue";
$l_views = "Vues";
$l_view_type = "Type de vue";
$l_select_view = "Choisir une vue";
$l_view_label = "Nom de la vue";
$l_view_save = "Mémoriser la vue";
$l_view_delete = "Supprimer la vue";

$l_ics = "Import" ;
$l_ics_insert = "Importer" ;
$l_ics_file = "Fichier ICS à importer" ;

$l_cal_view = "Type d'affichage";
$l_cal_range = "Période d'affichage";
$l_view_agenda = "Calendrier";
$l_view_planning = "Planning";
$l_range_day = "sur un jour";
$l_range_week = "sur une semaine";
$l_range_month = "sur un mois";
$l_view_agenda_desc = "Vue calendrier, cette vue est éditable";
$l_view_printable_desc = "Vue imprimable du calendrier, cette vue n'est pas éditable";
$l_view_planning_desc = "Vue planning du calendrier, cette vue n'est pas éditable";
$l_view_list_desc = "Liste des événements, cette vue n'est pas éditable";
$l_view_week_desc = "Voir les événements sur une semaine";
$l_view_day_desc = "Voir les événements sur un jour";
$l_view_month_desc = "Voir les événements sur un mois";

// Messages
$l_select_contacts = "Vous devez choisir au moins un contact ou un groupe.";
$l_select_repeat_day = "Vous devez sélectionner le ou les jours de répétition";
$l_confirm_delete_all = "Cette opération va supprimer toutes les occurences de cet événement pour tous les utilisateurs, êtes-vous sûr de vouloir poursuivre ?";
$l_confirm_delete = "Cette opération va supprimer cette occurence de l'événement pour tous les utilisateurs, êtes-vous sûr de vouloir poursuivre ?";
$l_conflict_events = "Le ou les créneaux horaires choisis sont occupés pour ";
$l_fill_title = "Veuillez remplir le champ [ $l_title ]";
$l_fill_dateend = "Veuillez remplir le champ [ $l_dateend ]";
$l_fill_datebegin = "Veuillez remplir le champ [ $l_datebegin ]";
$l_err_no_calendar_selected = "Aucun agenda séléctionné";
$l_err_begin_end = "La date de fin doit être supérieure à la date de début";
$l_err_end_repeat = "La fin de répétition doit être supérieure à la date de fin";
$l_err_end_repeat2 = "La durée maximum d'une répétition est de 1 an";
$l_err_end_repeat3 = "La durée maximum d'une répétition est de 10 ans lorsque la répétition est de type annuelle.";
$l_err_days_repeat = "Vous devez spécifier des jours de répétitions.";
$l_err_days_repeat_not_weekly = "Vous ne pouvez préciser des jours de répétition qu'en mode de répétition hebdomadaire.";
$l_err_weekly_repeat = "Lors d'une répétition hebdomadaire la date de fin de répétition doit au moins être de 7 jours supérieure à celle de fin d'événement.";
$l_err_repeatfrequency = "La fréquence est invalide";
$l_event_cant_delete = "Vous ne pouvez supprimer que vos événements !";

$l_fill_view_label = "Vous devez spécifier le nom de la vue avant de valider";
$l_confirm_delete_view = "Etes-vous sûr de vouloir supprimer cette vue ?";
$l_no_sel_view = "Suppression impossible : aucune vue sélectionnée";
$l_conflict_view_label = "$l_view_label : Un conflit a été détecté";

$l_header_planning = "Planning";
$l_header_meeting = "Nouvelle réunion";
$l_header_admin = "Administration";
$l_header_waiting_events = "Evts en attente";
$l_authorize_list = "Personnes autorisées";
$l_denie_list = "Personnes non-autorisées";
$l_read_permission = "Gestion des permissions de lecture de l'agenda";
$l_write_permission = "Gestion des permissions d'écriture sur l'agenda";
$l_everyone = "Autoriser tout le monde";
$l_noone = "N'autoriser personne";
$l_authorize = "&lt;&lt;&lt;&lt;";
$l_deny = "&gt;&gt;&gt;&gt;";

//MAIL
$l_add_event_mail_head = "Nouvel événement dans Obm : ";
$l_update_event_mail_head = "Modification événement : ";
$l_delete_event_mail_head = "Suppression événement : ";

$l_add_event_mail_subject = "Nouvel événement sur Obm : ";
$l_update_event_mail_subject = "Modification événement sur Obm : ";
$l_delete_event_mail_subject = "Suppression événement sur Obm : ";

$l_update_event_mail_body = "\nAu lieu de :";
$l_delete_event_mail_body = "Il aurait du avoir lieu : ";
$l_confirm_mail = "Confirmer+forcer l'envoi de mail";

$l_add_event_mail_subject = "Nouvel evenement sur OBM : %s";
$l_update_event_mail_subject = "Modification evenement sur OBM : %s";
$l_delete_event_mail_subject = "Suppression evenement sur OBM : %s";
$l_delete_exception_mail_subject = "Modification evenement sur OBM : %s";
$l_add_exception_mail_subject = "Modification evenement sur OBM : %s";
$l_update_state_mail_subject = "Participation a l'evenement sur OBM : %s";
$l_alert_mail_subject = "Evenement imminent : %s";

$l_add_event_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
NOUVEAU RENDEZ-VOUS !
------------------------------------------------------------------

Vous êtes invité à participer à un rendez-vous du %s au %s,
qui a pour sujet %s (lieu : %s).


:: Pour plus de détails sur le rendez-vous : %s
:: Pour accepter ce rendez-vous : %s
:: Pour refuser ce rendez-vous : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_add_resource_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
NOUVELLE RESERVATION DE RESSOURCE !
------------------------------------------------------------------

Une ressource dont vous êtes responsable à été réservée du %s au %s,
pour : %s (lieu : %s).


:: Pour accepter/refuser la réservation : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_update_event_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
RENDEZ-VOUS MODIFIÉ !
------------------------------------------------------------------

Le rendez-vous %s,  initialement prévu du %s au %s, (lieu : %s),
a été modifié et se déroulera du %s au %s (lieu : %s).

:: Pour plus de détails sur les modifications : %s
:: Pour accepter les modifications de ce rendez-vous : %s
:: Pour refuser les modifications de ce rendez-vous : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_update_resource_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
MODIFICATION D'UNE RESERVATION DE RESSOURCE !
------------------------------------------------------------------

La réservation %s d'une ressource dont vous êtes responsable
initialement prévue du %s au %s, (lieu : %s), a été modifiée et se
déroulera du %s au %s (lieu : %s).

:: Pour accepter/refuser les modifications : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_delete_event_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
RENDEZ-VOUS SUPPRIMÉ !
------------------------------------------------------------------

Le rendez-vous %s, initialement prévu du %s au %s (lieu : %s), a été
supprimé.

:: Pour contacter le responsable de l'annulation du rendez-vous : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_delete_resource_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
RESERVATION DE RESSOURCE ANNULEE !
------------------------------------------------------------------

La réservation %s, initialement prévu du %s au %s (lieu : %s), a 
été annulée.

:: Pour contacter le responsable de l'annulation du rendez-vous : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_delete_exception_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
OCCURENCE(S) RESTAURÉES !
------------------------------------------------------------------

La ou les occurrences du rendez-vous %s, initialement annulées 
les %s auront lieu.

:: Pour plus de détails sur les modifications : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_add_exception_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
OCCURENCE(S) RESTAURÉES !
------------------------------------------------------------------

La ou les occurrences du rendez-vous %s, initialement prévues 
les %s n'auront pas lieu.

:: Pour plus de détails sur les modifications : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_update_state_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
PARTICIPATION AU RENDEZ-VOUS
------------------------------------------------------------------

La participation de %s à l'événement %s est %s.

:: Pour plus de détails sur l'événement : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s par une action de %s %s dans OBM 
%s";

$l_alert_mail_body = 
"Message automatique envoyé par OBM
------------------------------------------------------------------
RENDEZ-VOUS IMMINENT
------------------------------------------------------------------

L'événement %s aura lieu à %s soit dans %s minutes (lieu : %s).

:: Pour plus de détails sur l'événement : %s

-------------------------------------------------------------------
Ce message a été envoyé le %s à %s automatiquement par OBM %s";

$l_unknown = "Inconnu";
$l_calendar_visible = "Agendas Visibles";
$l_calendar_displayed = "Agendas affichés";
$l_resource_visible = "Ressources";
$l_resource_displayed = "Ressources choisies";
$l_resource_allocated = "Ressources allouées";
// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_interval_null = "La durée ne peux pas être nulle";
$mj_fill_title_event = "\\n Vous devez saisir un titre pour le rdv.";
$mj_fill_time_begin = "\\n Vous devez saisir une heure de début.";
$mj_fill_time_end = "\\n Vous devez saisir une heure de fin.";
$mj_fill_valid_time_begin = "\\n Vous devez saisir une heure de début valide.";
$mj_fill_valid_time_end = "\\n Vous devez saisir une heure de fin valide.";
$mj_delete_confirm = "Confirmer la suppression du rdv ?";
$mj_invalid_day = "Ce jour n'existe pas pour le mois sélectionné.";
$mj_date_incompatibility = "La date de fin ne peut être antérieure a la date de début.";
$mj_repeat_date_incompatibility = "La date de fin de répétition ne peut être antérieure a la date de début."; 
$mj_event_delete_confirm = "Confirmer la suppression du rdv ?"; 
$mj_event_delete_all_confirm = "Confirmer la suppression du rdv et de toutes ses répétitions ?"; 
