<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : document.inc                                             //
// 2003-08-21 Rande Mehdi                                                    //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

// Labels et textes
$l_author = "Auteur";
$l_createtime = "Date de création";
$l_extension = "Extension";
$l_mime_label = "Label";
$l_mime_manage = "Gestion des Types MIME";
$l_mime_exist = "Types MIME existantes";
$l_mime_new = "Nouveau Type MIME"; 
$l_mimetype = "Type MIME";
$l_mime_delete =  "Supprimer";
$l_path = "Chemin";
$l_title = "Titre";
$l_updatetime = "Dernière modification";
$l_document_display = "Options d'affichage des listes de documents";
$l_size = "Taille";
$l_bytes = "octets";
$l_private = "Privé";
$l_header_new_dir = "Nouveau répertoire";
$l_dir = "Répertoire";
$l_add_dir = "Créer le répertoire";
$l_update_dir = "Mettre à jour";
$l_header_tree = "Arborescence";
$l_auto = "Par défaut";
$l_consult = "Consulter le document";
$l_url = "Adresse";
$l_add = "Ajouter les documents";

// Message
$l_mime_link_document = "Le type MIME est référencé par ces documents";
$l_mime_link_document_no = "Le type MIME n'est référencé dans aucun document";
$l_mime_can_delete = " Le type MIME peut etre supprimé"; 
$l_mime_cant_delete = " Le type MIME ne peut pas etre supprimé";
$l_found = "document(s) trouvé(s)";
$l_mime_checkdelete = "Vérifier ou supprimer le type MIME"; 
$l_mime_update = "Mettre à jour le type MIME"; 
$l_mime_insert = "Insérer un type MIME";
$l_mime_delete_ok = "La suppression du type MIME a été correctement effectuée.";
$l_mime_delete_error = "La suppression du type MIME a échoué !";
$l_mime_insert_ok = "L'insertion du type MIME a été correctement effectuée.";
$l_mime_insert_error = "L'insertion du type MIME a échoué !";
$l_mime_update_ok = "La modification du type MIME a été correctement effectuée";
$l_mime_update_error = "La modification du type MIME a &eacute;chou&eacute;e !";
$l_no_found = "Aucun document ne correspond à ces critères !";
$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir la liste des documents correspondants.";
$l_new_file = "Fichier à déposer";
$l_link = "Lien HTTP";
$l_links = "Lien HTTPS";
$l_kind = "Type de document";
$l_events = "Evènement(s) lié(s)";
$l_invalid_link_file = "Impossible de creer un alias sur un lien";
$l_invalid_url = "Adresse invalide";
$l_noupdate_file = "Ne pas changer le fichier";
$l_update_file = "Changer le fichier";
$l_create_file_error = "Erreur lors de la création du fichier";
$l_delete_file_error = "La suppression du fichier du document a échoué !";
$l_can_delete = "Le document peut être supprimé.";
$l_cant_delete = "Le document ne peut être supprimé !";
$l_err_system_path = "The Root and the Default directories can't be deleted !"; 
$l_err_dir_no_empty = "The directory is not empty !"; 
$l_dir_can_delete = "Le répertoire peut être supprimé.";
$l_dir_cant_delete = "Le répertoire ne peut être supprimé !";
$l_browse = "Parcourir";
$l_have_link = "Attention : ce document est lié à des éléments";
$l_have_no_link = "Ce document n'est lié à aucun élément";
$l_no_document = "Document introuvable";
$l_quota_msg = "Vous utilisez actuellement %s (%s) de l'espace de %s dédié à vos documents privés";
$l_over_quota_error = "Ajouter ce document vous ferait dépasser votre quota ! Supprimez quelques documents privés pour pouvoir ajouter celui-ci.";
$l_filesize_units = array('Octets','Ko','Mo','Go','To','Po');
$l_err_file_access_forbidden = "Vous n'avez pas la permission d'accéder à ce document";

// Actions
$l_checkdelete = "Vérifier ou Supprimer le document";
$l_delete = "Supprimer le document";
$l_force_delete = "Forcer la suppression";
$l_insert = "Enregistrer le document";
$l_update = "Modifier le document";
$l_dir_delete = "Supprimer le répertoire";

// JavaScript Messages
$l_fill_title = "Vous devez renseigner le Titre avant de valider.";
$l_fill_author = "Vous devez renseigner l'Auteur avant de valider.";
$l_fill_path = "Vous devez renseigner le Chemin avant de valider.";
$l_j_mime_create = "Vous devez renseigner tous les champ du type MIME";
$l_j_mime_update = "Vous devez renseigner tous les champ du type MIME";
$l_j_mime_delete = "Vous devez sélectionner un type MIME";
$l_fill_dir_name = "Vous devez donner un nom à vote répertoire";
$l_invalid_dir_path = "Le chemin spécifié est invalide";
$l_invalid_file = "Fichier incorrect";
$l_invalid_existing_file = "Le chemin spécifié ne pointe pas vers un fichier valid";
$l_error_dir = "Le répertoire n'est pas valide. Vérifier le chemin et le nom";
$l_file_maxsize = "Attention : taille maximum fixée à ";
