<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// ALIAMIN - Language : French                                               //
//         - File     : group.inc                                            //
// 2003-08-22 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_group = "Groupe";

// Database fields
$l_name = "Nom";
$l_system = "Systeme";
$l_desc = "Description";
$l_email = "E-mail";
$l_creator = "Créateur";
$l_date_creation = "Création";
$l_updater = "Mise à jour par" ;
$l_date_last_update = "Mise à jour" ;

// Labels et textes
$l_yes = "oui";
$l_no = "non";
$l_nb_user = "# Utilisateurs";
$l_group_user = "Ayant comme utilisateur";
$l_group_display = "Options d'affichage des listes de groupes";
$l_user_display = "Options d'affichage des listes d'utilisateurs";
$l_desc = "Description";

// Contact
$l_lastname = "Nom";
$l_firstname = "Prénom";
$l_function = "Fonction";
$l_phone = "Tél";
$l_hphone = "Tél perso";

// Actions
$l_insert = "Enregistrer le groupe";
$l_update = "Modifier le groupe";
$l_delete = "Supprimer le groupe";
$l_add = "Ajouter ces groupes";

// Messages
$l_insert_ok = "L'insertion du groupe a été correctement effectuée.";
$l_insert_error = "L'insertion du groupe a échoué !";
$l_update_ok = "La modification du groupe a été correctement effectuée.";
$l_update_error = "La modification du groupe a échoué !";
$l_delete_ok = "La suppression du groupe a été correctement effectuée.";
$l_delete_error = "La suppression du groupe a échoué !";
$l_name_list = "Le nom du groupe doit etre rempli" ;
$l_name_list_nomatch = "Le nom du groupe n'est pas valide" ;
$l_name_list_nomatch = "La description du groupe doit etre rempli" ;
$l_list_exists = "Désolé mais ce groupe existe déjà";
$l_j_check_email = "L'adresse e-mail n'est pas valide !";
$l_warn_delete = "utilisateurs enregistrés dans ce groupe";
$l_email_exist = "L'adresse E-mail saisie est déjà utilisée !";

$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir les groupes correspondants.";
$l_no_group = "Aucun groupe ne correspond à ces critères.";
$l_no_user = "Il n'y a pas d'utilisateurs membres.";
$l_no_group_group = "Il n'y a pas de groupes membres.";
$l_found = "groupes trouvés.";
$l_user_member = "utilisateurs membres.";
$l_group_member = "groupes membres.";
$l_no_found = "Aucun groupe ne correspond à ces critères !";
$l_add_user = "Ajouter des utilisateurs";
$l_add_group = "Ajouter des groupes";
$l_del_user_sel = "Enlever ces utilisateurs";
$l_del_group_sel = "Enlever ces groupes";
$l_user_added = "Utilisateur(s) ajouté(s)";
$l_user_removed = "Utilisateur(s) enlevé(s)";
$l_group_added = "Groupe(s) ajouté(s)";
$l_group_removed = "Groupe(s) enlevé(s)";
$l_no_user_added = "Pas d'utilisateurs à ajouter";
$l_no_user_deleted = "Pas d'utilisateurs à supprimer";
$l_no_group_added = "Pas de groupes à ajouter";
$l_no_group_deleted = "Pas de groupes à supprimer";
$l_check_samegroup = "Ces groupes sembles similaires au groupe saisi";
$l_title_add_group = "Ajouter des groupes (parmi la liste des groupes possibles)";
