<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : group.inc                                                //
// 2003-08-22 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_system = "Systeme";
$l_email = "E-mail";
$l_creator = "Créateur";
$l_date_creation = "Création";
$l_updater = "Mise à jour par";
$l_date_last_update = "Mise à jour";

// Labels et textes
$l_nb_user = "# Utilisateurs";
$l_group_user = "Ayant comme utilisateur";
$l_group_display = "Options d'affichage des listes de groupes";
$l_user_display = "Options d'affichage des listes d'utilisateurs";

// Contact
$l_lastname = "Nom";
$l_firstname = "Prénom";
$l_function = "Fonction";

// Actions
$l_insert = "Enregistrer le groupe";
$l_delete = "Supprimer le groupe";
$l_add = "Ajouter ces groupes";

// Messages
$l_insert_ok = "L'insertion du groupe a été correctement effectuée.";
$l_insert_error = "L'insertion du groupe a échoué !";
$l_update_ok = "La modification du groupe a été correctement effectuée.";
$l_update_error = "La modification du groupe a échoué !";
$l_delete_ok = "La suppression du groupe a été correctement effectuée.";
$l_delete_error = "La suppression du groupe a échoué !";
$l_fill_name = "Le nom du groupe doit etre rempli";
$l_group_exists = "Ce groupe existe déjà !";
$l_j_check_email = "L'adresse e-mail n'est pas valide !";
$l_warn_delete = "utilisateurs enregistrés dans ce groupe";
$l_email_exist = "L'adresse E-mail saisie est déjà utilisée !";
$l_system_no_priv = "Un groupe système ne peut être privé !";
$l_only_owner_priv = "Seul le propriétaire d'un groupe peut le définir privé !";

$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir les groupes correspondants.";
$l_no_user = "Il n'y a pas d'utilisateurs membres.";
$l_no_group_group = "Il n'y a pas de groupes membres.";
$l_found = "groupes trouvés.";
$l_user_member = "utilisateurs membres.";
$l_group_member = "groupes membres.";
$l_no_found = "Aucun groupe ne correspond à ces critères !";
$l_add_user = "Ajouter des utilisateurs";
$l_add_group = "Ajouter des groupes (parmi la liste des groupes possibles)";
$l_del_user_sel = "Enlever ces utilisateurs";
$l_del_group_sel = "Enlever ces groupes";
$l_user_added = "Utilisateur(s) ajouté(s)";
$l_user_removed = "Utilisateur(s) enlevé(s)";
$l_group_added = "Groupe(s) ajouté(s)";
$l_group_removed = "Groupe(s) enlevé(s)";
$l_no_user_added = "Pas d'utilisateurs à ajouter";
$l_no_user_deleted = "Pas d'utilisateurs à supprimer";
$l_no_group_added = "Pas de groupes à ajouter";
$l_no_group_deleted = "Pas de groupes à supprimer";
$l_check_samegroup = "Ces groupes sembles similaires au groupe saisi";
$l_cant_delete_system = "Les groupes système ne peuvent être supprimés !";
$l_cant_delete_public = "Les groupes publics ne peuvent être supprimés que par leur créateur !";

$l_add_groups = "Ajouter des groupes";