<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : header.inc                                               //
// 1999-01-26 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////
////// Theme headers lang files ////////////////////////
////////////////////////////////////////////////////////

$l_header_com    = "COMMERCIAL";
$l_header_prod   = "PRODUCTION";
$l_header_compta = "COMPTABILITE";
$l_header_users  = "UTILISATEUR";
$l_header_admins = "ADMINISTRATION";

$l_header_settings = "Configuration";
$l_header_company = "Soci&eacute;t&eacute;s";
$l_header_contact = "Contacts";
$l_header_contract = "Contrats";
$l_header_incident = "Incidents";
$l_header_deal = "Affaires";
$l_header_list = "Listes";
$l_header_user = "Utilisateurs";
$l_header_computer = "Ordinateurs" ;
$l_header_admin = "Administration";
$l_header_admin_lang = "Langue";
$l_header_admin_data = "Données";
$l_header_admin_pref = "Préférences";
$l_header_admin_code = "Code";
$l_header_account = "Comptes";
$l_header_invoice = "Factures";
$l_header_payment = "Paiements";

//TIME
$l_header_time = "Gestion temps" ;
$l_header_admin = "Administration";
$l_header_stats = "Statistiques";
$l_header_base = "Base";
$l_header_agenda = "Agenda";

$l_header_title_settings = "CONFIGURATION";
$l_header_title_company = "SOCIETE";
$l_header_title_contact = "CONTACT";
$l_header_title_contract = "CONTRAT";
$l_header_title_incident = "INCIDENT";
$l_header_title_deal = "AFFAIRE";
$l_header_title_list = "LISTE"; 
$l_header_title_user = "UTILISATEUR";
$l_header_title_computer = "ORDINATEUR" ;
$l_header_title_admin = "ADMINISTRATION";
$l_header_title_account = "COMPTES";
$l_header_title_invoice = "FACTURES";
$l_header_title_payment = "PAIEMENTS";
$l_header_title_agenda = "AGENDA";

$l_header_new_f = "Nouvelle";
$l_header_new = "Nouveau";
$l_header_find = "Chercher";
$l_header_modify = "Modifier";
$l_header_display = "Affichage";
$l_header_delete = "Supprimer";

$l_header_new_parent = "Nouvelle SurAffaire";
$l_header_find_parent = "Chercher SurAffaire";

$l_header_export = "Exporter";
$l_header_reconcile = "Rapprocher";
$l_header_dupplicate = "Dupliquer";
$l_header_compute_balance = "Calculez solde";

$l_header_add_contact = "Ajouter contact";

$l_header_reset = "Préférence par défaut";

$l_header_day = "Jour";
$l_header_week = "Semaine";
$l_header_month = "Mois";
$l_header_new_event = "Nouveau rdv";
