<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - File : Language : en
//      - File : obminclude/en/imap_archive.inc
///////////////////////////////////////////////////////////////////////////////
// $Id: $ //
///////////////////////////////////////////////////////////////////////////////

$l_daily = "Quotidienne";
$l_weekly = "Hebdomadaire";
$l_monthly = "Mensuelle";
$l_yearly = "Annuelle";
$l_monday = "Lundi";
$l_tuesday = "Mardi";
$l_wednesday = "Mercredi";
$l_thursday = "Jeudi";
$l_friday = "Vendredi";
$l_saturday = "Samedi";
$l_sunday = "Dimanche";
$l_last = "Dernier";
$l_service_activating = "Activation du service";
$l_activating = "Activation";
$l_scheduling = "Déclenchement du traitement";
$l_repeat_kind = "Type de répétition";
$l_weekly_repeat_kind = "Hebdomadaire jour de la semaine";
$l_monthly_repeat_kind = "Mensuelle jour du mois";
$l_yearly_repeat_kind = "Annuelle jour de l'année";
$l_hour = "Heure";
$l_minute = "Minute";
$l_next_run = "Prochaine exécution";
$l_folder = "Dossier";
$l_excluded_folder = "Dossier à exclure";
$l_excluded_users = "Utilisateurs à exclure";
$l_name = "Nom";
$l_delete = "Supprimer";
$l_remove_archive = "Purger l'archive";
$l_mailing_feedback = "Envoyer les résultats à";
$l_mailing_email = "Adresse mail";
$l_past_operations = "Historique des traitements";
$l_start_time = "Heure de début";
$l_end_time = "Heure de fin";
$l_status = "Statut";
$l_last_fail = "Dernière erreur";
$l_simulation = "Simulation";
$l_manual_launch = "Exécution manuelle";
$l_status_error = "Erreur";
$l_status_success = "Ok";
$l_not_configured = "Non configuré";

$l_email_address_not_found = "Adresse mail introuvable pour ce domaine";
$l_imap_archive_server_not_found = "Server d'archivage IMAP introuvable pour ce domaine";
$l_imap_archive_server_unreachable = "Server d'archivage IMAP injoignable";
$l_domain_configuration_not_found = "La configuration de l'archivage IMAP n'a pas été trouvé pour ce domaine";
$l_domain_configuration_disable = "La configuration de l'archivage IMAP n'est pas active pour ce domaine";
$l_could_not_login_imap_archive_server = "Impossible de se connecter au Server d'archivage IMAP";
$l_archiving_running = "Logs de l'archivage en cours";
$l_unsupported_iframe = "Votre navigateur ne supporte pas les iframes.";
$l_archiving_launched = "L'archivage a été lancé avec succès.";
$l_excluded_folder_error = "Le dossier à exclure doit être correctement renseigné ! Il ne doit pas contenir de caractères spéciaux";
$l_confirm_manual_launch = "Un nouvel onglet contenant les logs va être ouvert. Etes-vous certain(e) de vouloir lancer un archivage manuel maintenant ?";
