<SCRIPT LANGUAGE="PHP">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : incident.inc                                             //
// 2001-08-20 : Mehdi RANDE                                                  //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

//Fields Label
$l_incident_label = "Label";
$l_incident_priority = "Priorité";
$l_incident_status = "Etat";
$l_incident_date = "Date";
$l_incident_logger = "Récepteur";
$l_incident_owner = "Responsable Technique";
$l_incident_description = "Description";
$l_incident_solution = "Solution apportée";
$l_contract_num = "Numéro de Contrat";
$l_contract_label = "Contrat";
$l_contract_date_init = "Date Debut";
$l_contract_date_expir = "Date Expiration";
$l_to = "Au"; 
$l_from = "Du";
$l_manager = "Responsable";
$l_client_manager = "Responsable Client";
$l_date_before ="Date Avant";
$l_date_after ="Date Après";
$l_archive_new = "Archiver";
$l_archive = "Voir les archives";
$l_archive_consult = "Archivé";
$l_incident_company = "Société";
$l_incident = "Incident";
//Title 
$l_incident_select_contract = "Sélectionner le Contrat de l'Incident.";
$l_redhot = "Très Urgent";
$l_hot = "Urgent";
$l_normal = "Normal";
$l_low = "Basse";
$l_open = "Ouvert";
$l_call = "Appel en abscence";
$l_waitcall = "Attente de retour";
$l_paused = "En Attente";
$l_closed = "Fermé";
$l_incident_lastupdate = "Date de dernière modification";

// Action
$l_select_contract = "Sélectionner le contrat";
$l_insert = "Enregistrer l'incident";
$l_update = "Modifier l'incident";
$l_checkdelete = "Supprimer l'incident";
$l_incident_select_contract = "Selectionner le contrat lié à cet incident";

//Message
$l_found = "incident(s) trouvé(s).";
$l_no_found = "Aucun Incident ne correspond à ces critères !";
$l_insert_ok = "L'insertion de l'incident a été correctement effectuée.";
$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir la liste des incidents correspondants.";

// For the display preferences modification screen 
$l_incident_display = "Options d'affichage des Incidents";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_length_label = "Le champ Label est trop long";
$l_fill_contract = "Vous devez sélectionner un contrat avant de valider.";
$l_j_select_contract = "Vous devez sélectionner un Contrat!";
$l_delete_confirm="Confirmer la suppression de l'Incident ?";
$l_date_after_js ="Date Après";
