<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : lead.inc                                                 //
// 2006-05-19 Aliacom Pierre Baudracco                                       //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_source = "Source";

$l_source_manage = "Gestion des opportunités";
$l_source_exist = "Existantes";
$l_source_new = "Nouvelle";

// Actions
$l_insert = "Enregistrer l'Opportunité";
$l_update = "Modifier l'Opportunité";
$l_delete = "Supprimer l'Opportunité";
$l_select_company = "Sélectionner la société";

$l_source_checkdelete = "Vérifier ou Supprimer la Source";
$l_source_delete = "Supprimer la Source";
$l_source_update = "Modifier la Source";
$l_source_insert = "Créer la Source";

// Messages
$l_can_delete = "L'opportunité peut être supprimée.";
$l_cant_delete = "L'opportunité ne peut être supprimée !";

$l_err_name_empty = "Le nom doit être renseigné !";
$l_err_source_empty = "La source d'opportunité doit être renseigné !";
$l_err_market_empty = "Le responsable doit être renseigné !";
$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir la liste des opportunités correspondantes.";
$l_found = "opportunité(s) trouvée(s).";
$l_no_found = "Aucune opportunité ne correspond à ces critères !";

$l_delete_ok = "La suppression de l'opportunité a été correctement effectuée.";
$l_delete_error = "La suppression de l'opportunité a échoué !";
$l_insert_ok = "L'insertion de l'opportunité a été correctement effectuée.";
$l_insert_error = "L'insertion de l'opportunité a échoué !";
$l_update_ok = "La modification de l'opportunité a été correctement effectuée";
$l_update_error = "La modification de l'opportunité a échoué !";
$l_source_insert_ok = "L'insertion de la source a été correctement effectuée.";
$l_source_insert_error = "L'insertion de la source a échoué !";
$l_source_update_ok = "La modification de la source a été correctement effectuée";
$l_source_update_error = "La modification de la source a échoué !";
$l_source_delete_error = "La suppression de la source a échoué !";
$l_source_delete_ok = "La suppression de la source a été correctement effectuée.";
$l_source_can_delete = "La source peut être supprimée";
$l_source_cant_delete = "La source ne peut être supprimée";
$l_source_link_deal = "La source est référencée par ces opportunités";
$l_source_link_deal_no = "La source n'est pas référencée dans les opportunités";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_fill_name = "Vous devez renseigner le Nom avant de valider.";
$l_fill_datealarm = "Vous devez renseigner la date alarme avant de valider.";
$l_invalid_date = "Format de date invalide (JJ/MM/AAAA ou AAAA-MM-JJ).";
$l_delete_confirm = "Confirmer la suppression de l'opportunité ?";

$l_j_source_create = "Vous devez saisir un nom de source pour le créer !";
$l_j_source_update = "Vous devez sélectionner un source et entrer une modification avant de valider !";
$l_j_source_delete = "Vous devez sélectionner un source pour vérifier ou supprimer !";

// For the display preferences modification screen 
$l_lead_display = "Options d'affichage des listes d'opportunités";
