<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : organizationalchart.inc                                  //
// 2007-02-26 David PHAN                                                     //
///////////////////////////////////////////////////////////////////////////////
// $Id: organizationalchart.inc,v 1.17 2007/02/14 15:18:54 flo Exp $ //
///////////////////////////////////////////////////////////////////////////////

// Labels et textes
$l_detail = "Détail";
$l_title = "Fonction";
$l_add_child_tooltip = "Ajouter un fils";

// Actions
$l_insert = "Enregistrer l'organigramme";
$l_update = "Modifier l'organigramme";

// Messages
$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir la liste des organigrammes correspondants.";
$l_found = "organigrammes trouvés.";
$l_no_found = "Aucun organigramme ne correspond à ces critères !";
$l_can_delete = "L'organigramme peut être supprimé.";
$l_cant_delete = "L'organigramme ne peut être supprimé !";
$l_fill_name = "Vous devez renseigner le nom de l'organigramme avant de valider.";
$l_fill_ogroup_name = "Vous devez renseigner le nom de chaque noeuds avant de valider";
$l_js_delete_node = "Etes-vous sûr de vouloir supprimer ce noeud ?";

// For the display preferences modification screen 
$l_organizationalchart_display = "Options d'affichage des listes d'organigrammes";
?>
