<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : password.inc                                             //
// 2004-03-25 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

$l_old_password = "Mot de passe actuel";
$l_new_password = "Nouveau Mot de passe";
$l_new_password_bis = "Validation nouveau Mot de passe";


// Messages
$l_wrong_password = "Le mot de passe actuel n'est pas valide !";
$l_new_password_differ = "Les nouveaux mots de passe saisis diffèrent !";
$l_password_invalid = "Le mot de passe saisi n'est pas valide (de 4 a 12 caractères) !";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_fill_password = "Vous devez saisir les mots de passe avant de valider.";
