<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : publication.inc                                          //
// 2004-01-29 Mehdi Rande                                                    //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Database fields
$l_publication_title = "Titre Publication";
$l_type = "Type";
$l_renew = "Renouvellement automatique";
$l_recept = "Mode de réception";
$l_reception = "Mode de réception";
$l_publication_type = "Type Publication";
$l_quantity = "Quantité";
$l_header_new_auto = "Renouvellement";

// Labels et textes
$l_type_manage = "Gestion des Types de Publication";
$l_type_exist = "Types existants";
$l_type_new = "Nouveau Type";

$l_renew_manage = "Gestion des Modes de renouvellement";
$l_renew_exist = "Modes de renouvellement existants";
$l_renew_new = "Nouveau Mode renouvellement";

$l_recept_manage = "Gestion des Modes de réception";
$l_recept_exist = "Modes de réception existants";
$l_recept_new = "Nouveau Mode de réception";
$l_auto_sub = "Abonnement automatique";
$l_contact_category1 = "Categorie contact 1";

// Titres
$l_publication_orig = "Publication d'origine";
$l_publication_dest = "Publication destination";
$l_subscription = "Abonnement";

// Actions
$l_insert = "Enregistrer la Publication";
$l_update = "Modifier la Publication";
$l_checkdelete = "Vérifier ou Supprimer la Publication";
$l_delete = "Supprimer la Publication";

$l_insert_sub = "Enregistrer l'Abonnement";
$l_update_sub = "Modifier l'Abonnement";
$l_checkdelete_sub = "Vérifier ou Supprimer l'Abonnement";
$l_delete_sub = "Supprimer l'Abonnement";

$l_type_update = "Modifier le Type";
$l_type_checkdelete = "Vérifier ou Supprimer le Type";
$l_type_delete = "Supprimer le Type";
$l_type_insert = "Créer le Type";

$l_renew_update = "Modifier le Mode de renouvellement";
$l_renew_checkdelete = "Vérifier ou Supprimer le Mode de renouvellement";
$l_renew_delete = "Supprimer le Mode de renouvellement";
$l_renew_insert = "Créer le Mode de renouvellement";

$l_recept_update = "Modifier le Mode de réception";
$l_recept_checkdelete = "Vérifier ou Supprimer le Mode de réception";
$l_recept_delete = "Supprimer le Mode de réception";
$l_recept_insert = "Créer le Mode de réception";

// Messages
$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir la liste des publications correspondantes.";
$l_found = "publications trouvées.";
$l_no_found = "Aucune publication ne correspond à ces critères !";
$l_check_samepublication = "Ces publications semblent similaires à cette nouvelle entrée !";
$l_link_contact = "Des contacts sont abonnés à cette publication";
$l_link_contact_no = "Aucun contact n'est abonné à la publication";
$l_can_delete = "La publication peut être supprimée.";
$l_cant_delete = "La publication ne peut être supprimée.";
$l_type_link_publication = "Ces publications sont du type";
$l_type_link_publication_no = "Pas de publications du type";
$l_type_cant_delete = "Le type ne peut être supprimé !";
$l_type_can_delete = "Le type peut être supprimé.";

$l_renew_link_publication = "Ces publications sont du mode de renouvellement";
$l_renew_link_publication_no = "Pas de publications du mode de renouvellement";
$l_renew_cant_delete = "Le mode de renouvellement ne peut être supprimé !";
$l_renew_can_delete = "Le mode de renouvellement peut être supprimé.";

$l_recept_link_publication = "Ces publications sont du mode de réception";
$l_recept_link_publication_no = "Pas de publications du mode de réception";
$l_recept_cant_delete = "Le mode de réception ne peut être supprimé !";
$l_recept_can_delete = "Le mode de réception peut être supprimé.";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_fill_title = "Vous devez renseigner le Titre avant de valider.";
$l_delete_confirm = "Confirmer la suppression de la Publication ?";
$l_j_check_year = "L'année n'est pas correcte.";
$l_j_fill_lang = "Vous devez renseigner la Langue avant de valider;";
$l_j_check_lang = "La langue indiquée n'est pas correcte.";
$l_j_type_delete = "Sélectionnez un type pour le vérifier ou supprimer !";
$l_j_type_update = "Vous devez sélectionner un type et entrer une modification avant de valider !";
$l_j_type_create = "Vous devez saisir un nom de type pour le créer !";
$l_j_renew_delete = "Sélectionnez un mode de renouvellement pour le vérifier ou supprimer !";
$l_j_renew_update = "Vous devez sélectionner un mode de renouvellement et entrer une modification avant de valider !";
$l_j_renew_create = "Vous devez saisir un nom de mode de renouvellement pour le créer !";
$l_j_recept_delete = "Sélectionnez un mode de réception pour le vérifier ou supprimer !";
$l_j_recept_update = "Vous devez sélectionner un mode de réception et entrer une modification avant de valider !";
$l_j_recept_create = "Vous devez saisir un nom de mode de réception pour le créer !";
$l_j_select_publication = "Vous devez sélectionner une publication !";
$l_j_fill_quantity = "Vous devez spécifier une quantité";
$l_j_check_quantity = "Vous devez donner une quantité valide";

// For the display preferences modification screen 
$l_publication_display = "Options d'affichage des listes de publications";
