<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : user.inc                                                 //
// 2005-03-13 Florent Goalabre                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_desc  = "Description";
$l_qty  = "Capacité/Quantité";
$l_check_resourcecreate = " entrées créées par cet utilisateur.";
$l_check_resourceupdate = " entrées modifiées par cet utilisateur.";
$l_no_resource = "Pas de champs ressources dans cette table";
$l_fill_name = "Vous devez renseigner le nom avant de valider.";

// Item & Property
$l_rtype = "Type de ressource";
$l_rtype_manage = "Gestion des types de ressources";
$l_rtype_property = "Propriété";
$l_rtype_kind = "Type";
$l_rtype_insert = "Créer le type de ressource";
$l_rtype_update = "Modifier le type de ressource";
$l_rtype_checkdelete = "Vérifier ou supprimer le type de ressource";
$l_ritem = "Accessoire";
$l_ritem_add = "Ajouter ces accessoires";
$l_ritem_manage = "Gestion des accessoires";
$l_ritem_insert = "Créer l'accessoire";
$l_ritem_update = "Modifier l'accessoire";
$l_no_item_available = "Aucun accessoire n'est disponible pour cette ressource";
$l_confirm_delete_item = "Etes-vous sûr de supprimer cet accessoire?";

// Titres
$l_resource = "Ressource";
$l_resources = "Ressources";
$l_users = "Utilisateurs";

// Actions
$l_insert = "Enregistrer la ressource";
$l_update = "Modifier la ressource";
$l_checkdelete = "Vérifier ou Supprimer la ressource";
$l_reset = "Préférences par défaut";
$l_delete = "Supprimer la ressource";
$l_add = "Ajouter ces ressources";

// Messages
$l_no_display = "Renseigner les critères souhaités et cliquer sur < Chercher > pour obtenir la liste des ressources correspondantes.";
$l_found = "ressource(s) trouvée(s).";
$l_no_found = "Aucune ressource ne correspond à ces critères !";
$l_cant_delete = "La ressource ne peut être supprimée !";
$l_can_delete = "La ressource peut être supprimée.";
$l_name_error = "Le nom doit être renseigné !";
$l_check_samename = "Ces ressources semblent similaires à cette nouvelle entrée !";
$l_exist_error = "Ce nom est déjà utilisé !";

$l_resource_display = "Options d'affichage des listes de ressources";
$l_add_resources = "Ajouter des ressources";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_j_check_number = "La quantité renseignée n'est pas correct.";
$l_j_create_type_first = "Vous devez créer un type de ressource avant de créer un accessoire !";

$l_toggle_public_access = "Ceci entrainera que tout le monde pourra faire une demande de réservation pour cette ressource. Désirez-vous continuer?";
$l_toggle_public_read = "Ceci entrainera que tout le monde pourra vous voire le calendrier de cette ressource. Désirez-vous continuer?";
$l_toggle_public_write = "Ceci entrainera que tout le monde pourra vous modifier les demandes de réservation et accepter la réservation de cette ressource. Désirez-vous continuer?";
$l_toggle_public_admin = "Ceci entrainera que tout le monde pourra modifier les droits de cette ressource. Désirez-vous continuer?";
