<SCRIPT language="php">
//////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                  //
//     - File     : settings.inc                                            //
// 1999-03-18 Pierre Baudracco                                              //
//////////////////////////////////////////////////////////////////////////////
// $Id$ //
//////////////////////////////////////////////////////////////////////////////

$l_settings = "Configuration";
$l_cur_settings = "Votre configuration actuelle";
$l_auto_display = "Afficher les listes automatiquement";
$l_submit = "Valider";
$l_cur_lang = "Votre langue actuelle";
$l_cur_theme = "Votre theme actuel";
$l_new_settings = "Pour changer votre configuration, Selectionner ici les nouveaux parametres";
$l_set_lang = "Choisissez votre langue";
$l_set_theme = "Choisissez votre theme";
$l_set_rows = "# lignes affichées par page";
$l_set_debug = "Niveau de debug";

$l_dg_id = "Id";
$l_dg_param = "Paramètres";
$l_dg_sql = "SQL";

$l_last_deal = "Derniere affaire";
$l_last_contact = "Dernier contact";
$l_last_company = "Derniere societe";
