<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : statistic.inc                                             //
// 2004-04-19 Rande Mehdi                                                    //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_statistic = "Statistiques";

$l_header_resp_stats = "Statistiques sur les responsables";

$l_header_comp_stats = "Statistiques sur les compagnies";

$l_key = "Légende";

$l_totals = "Total";

$l_null = "Aucun";

$l_compcat = "Categories des compagnies";

$l_select_list = "Séléctionner une liste de compagnies depuis le module List";

$l_generate_stats = "Générer les statistiques";
