<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : statistic.inc                                            //
// 2004-04-19 Rande Mehdi                                                    //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

$l_statistic = "Statistiques";

$l_stats_manager = "Statistiques sur les responsables";
$l_stats_contact_date_evolution = "Statistiques sur l'évolution du nombre de contacts par date";

$l_key = "Légende";
$l_totals = "Total";
$l_null = "Aucun";
$l_contcat = "Categories des contacts";
$l_stats_from_list = "Sur un échantillon (liste) donné";
$l_stats_from_all = "Sur l'ensemble";

$l_contact_date_evolution_graph = "Evolution du nombre de contacts (mensuel)";
