<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : time.inc                                                 //
// 1999-01-24 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$ //
///////////////////////////////////////////////////////////////////////////////

// Headers
$l_header_stats = "Statistiques";
$l_header_view = "Vue mensuelle";
$l_header_globalview = "Vue générale";

// for list
$l_task_fac = "Taches Facturées";
$l_task_int = "Taches Internes";

// Database fields
$l_taskdate="Date tâche";
$l_tasktype = "Type tâche";
$l_tasklabel="Label tâche";
$l_deallabel="Projet/Affaire";
$l_task_del="Supprimer ?";
$l_company = "Société";
$l_delete = "Supprimer les tâches";
$l_length="Durée";
$l_total_length="Durée cumulée";
$l_total_before="Durée cumulée précédente";
$l_total_period="Durée sur la période";
$l_total="Total";
$l_day="Jour";
$l_period="Période";

$l_task_del="Suppr.";
$l_week="Semaine";
$l_month="Mois";
$l_user="Utilisateur";
$l_all_users="Tous ?";
$l_see = "Voir";
$l_validate_task = "Validée";
$l_valid = "Valider";
$l_add = "Ajouter";
$l_update = "Modifier";
$l_fill= "compléter";

$l_week_next = "Semaine suivante";
$l_week_prev = "Semaine précédente";
$l_month_next = "Mois suivant";
$l_month_prev = "Mois précédent";
$l_date = "Date:";
$l_project = "Projet:";
$l_task = "Tache:";
$l_label = "Label:";
$l_duration = "Durée:";

// Titres
$l_time = "Gestion des temps";


// Messages
$l_projects_manager = "Confirmation de la validation des taches par l'administrateur:";
$l_found_task = "Voici les tâches réalisées et saisies pour la semaine en cours:";
$l_found = "Taches trouvées.";
$l_no_found = "Aucune Taches pour cet utilisateur!";
$l_addtask_start = "Saisissez les tâches réalisées pour la semaine en cours. La durée s'entend en fraction de journée (entre 1/";
$l_addtask_end = " et 1).";
$l_update_task = "Vous pouvez modifier votre tache ci dessous:";
$l_total_day = "Récapitulatif des tâches par jour.Si une journée a été intégralement saisie,<BR> vous devez confirmer ci-dessous en sélectionnant les journées à valider et en validant le formulaire.";
$l_total_deal = "Récapitulatif par taches :";
$l_total_month = "Récapitulatif mensuel :";

// Type de tâches à rechercher
$l_tasktype = "Type des tâches";
$l_task_all = "Toutes";
$l_task_uservalid = "Validées par l'admin ou l'utilisateur";
$l_task_adminvalid= "Validées par l'admin uniquement";

// JavaScript Messages (les caracteres comme \ doivent etre backslashes -> \\)
$l_j_select_tasktype = "Vous devez sélectionner un type de tâche.";
$l_j_select_project = "Vous devez sélectionner un project pour une tâche facturée.";
$l_delete_confirm = "Confirmer la suppression de ces taches ?";

