<SCRIPT language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : todo.inc                                                 //
// 2003-09-15 Bastien Continsouzas                                           //
///////////////////////////////////////////////////////////////////////////////
// $Id
///////////////////////////////////////////////////////////////////////////////

$l_user = "Utilisateur";
$l_date = "Date de saisie";
$l_deadline = "Date limite";
$l_priority = "Priorité";
$l_todotitle = "Titre";
$l_content = "Description";

$l_del = "Suppr.";
$l_delete = "Supprimer";
$l_add = "Ajouter";

$l_no_found = "Rien à faire";

$l_delete_confirm = "Confirmer la suppression de ces entrées";
$l_j_fill_title = "Remplissez le titre";

</script>