<script language="php">
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French                                                   //
//     - File     : tools.inc                                                //
// 2002-09-26 Pierre Baudracco                                               //
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

$l_tools = "Outils d'administration";

$l_upd = "Mise à jour de la configuration du système";
$l_upd_user = "Mes mises à jour";
$l_upd_domain = "Mises à jour du domaine";
$l_upd_delegation = "Mises à jour de ma délégation";
$l_upd_running = "Le système est en cours de configuration...";
$l_upd_already_running = "Impossible, le système est déjà en cours de configuration...";
$l_upd_not_needed = "La configuration du système est <b>à jour</b>";
$l_upd_need_domain_update = "Le domaine a été modifié ! Une validation de configuration de domaine est nécessaire";
$l_upd_needed = "La configuration du système a été modifiée";
$l_upd_run = "Prendre en compte la nouvelle configuration du système";
$l_upd_cancel = "Annuler les modifications effectuées";
$l_upd_ok = "La configuration du système a bien été prise en compte";
$l_upd_error = "La configuration du système a échoué !";
$l_upd_cancel_ok = "L'annulation des modifications du système a bien été prise en compte";
$l_upd_cancel_error = "L'annulation des modifications du système a échoué !";

$l_created = "Créés";
$l_updated = "Modifiés";
$l_deleted = "Supprimés";
$l_links = "Liaisons";

$l_halt = "Arrêt du système";
$l_halt_aliamin = "Arréter le système";

$l_remote_access = "Prise de contrôle à distance";
$l_remote_allowed = "La prise de contrôle à distance est <em class=\"messageOk\">autorisée</em>";
$l_remote_not_allowed = "La prise de contrôle à distance est <em class=\"messageError\">interdite</em>";
$l_remote_allow = "Autoriser la prise de contrôle à distance";
$l_remote_not_allow = "Interdire la prise de contrôle à distance";
