<?php
///////////////////////////////////////////////////////////////////////////////
// OBM - Language : French
//     - File     : vacation.inc
// 2007-01-24 Pierre Baudracco
///////////////////////////////////////////////////////////////////////////////
// $Id$
///////////////////////////////////////////////////////////////////////////////

// consultation labels
$l_vacation = "Message d'absence" ;
$l_vacation_enabled = "Le message d'absence est " ;
$l_vacation_message = "Message d'absence";
$l_enable_vacation = "Activer mon message d'absence immédiatement" ;
$l_enable_auto_vacation = "Programmer l'activation automatique de mon message d'absence" ;
$l_vacation_datebegin = "Du";
$l_vacation_dateend = "Au";

// errors 
$l_empty_message = "Le message d'absence ne peut être vide quand l'envoi est activé !" ;
$l_sieve_login_failed = "La connexion au serveur de messagerie a échoué.";
$l_vacation_not_allowed = "Le message d'absence nécessite d'avoir le droit d'utiliser la messagerie !";
