/* Generated By:JavaCC: Do not edit this line. VcardParserConstants.java */
package org.obm.funambol.vcardparser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VcardParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int SEOL = 3;
  /** RegularExpression Id. */
  int SEOL_QP = 4;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int COLON_QP = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int SEMICOLON_QP = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int CATEGORIES = 10;
  /** RegularExpression Id. */
  int VERSION = 11;
  /** RegularExpression Id. */
  int TITLE = 12;
  /** RegularExpression Id. */
  int NICKNAME = 13;
  /** RegularExpression Id. */
  int EMAIL = 14;
  /** RegularExpression Id. */
  int FN = 15;
  /** RegularExpression Id. */
  int ORG = 16;
  /** RegularExpression Id. */
  int BDAY = 17;
  /** RegularExpression Id. */
  int PHOTO = 18;
  /** RegularExpression Id. */
  int ADR = 19;
  /** RegularExpression Id. */
  int UID = 20;
  /** RegularExpression Id. */
  int LABEL = 21;
  /** RegularExpression Id. */
  int ROLE = 22;
  /** RegularExpression Id. */
  int TZ = 23;
  /** RegularExpression Id. */
  int LOGO = 24;
  /** RegularExpression Id. */
  int NOTE = 25;
  /** RegularExpression Id. */
  int URL = 26;
  /** RegularExpression Id. */
  int N = 27;
  /** RegularExpression Id. */
  int REV = 28;
  /** RegularExpression Id. */
  int TEL = 29;
  /** RegularExpression Id. */
  int FOLDER = 30;
  /** RegularExpression Id. */
  int VCBEGIN = 31;
  /** RegularExpression Id. */
  int VCEND = 32;
  /** RegularExpression Id. */
  int EXTENSION = 33;
  /** RegularExpression Id. */
  int CONTENTSTRING = 34;
  /** RegularExpression Id. */
  int CONTENTSTRING_QP = 35;
  /** RegularExpression Id. */
  int NONBREAKINGEQUALS = 36;
  /** RegularExpression Id. */
  int WS = 37;
  /** RegularExpression Id. */
  int QUOTED_PRINTABLE = 38;
  /** RegularExpression Id. */
  int PARAMSTRING = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int CONTENTSTATE = 1;
  /** Lexical state. */
  int CONTENTSTATE_QP = 2;
  /** Lexical state. */
  int PARAMSTATE = 3;
  /** Lexical state. */
  int PARAMSTATE_QP = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\".\"",
    "<EOL>",
    "<SEOL>",
    "<SEOL_QP>",
    "\":\"",
    "\":\"",
    "\";\"",
    "\";\"",
    "\"=\"",
    "\"CATEGORIES\"",
    "\"VERSION\"",
    "\"TITLE\"",
    "\"NICKNAME\"",
    "\"EMAIL\"",
    "\"FN\"",
    "\"ORG\"",
    "\"BDAY\"",
    "\"PHOTO\"",
    "\"ADR\"",
    "\"UID\"",
    "\"LABEL\"",
    "\"ROLE\"",
    "\"TZ\"",
    "\"LOGO\"",
    "\"NOTE\"",
    "\"URL\"",
    "\"N\"",
    "\"REV\"",
    "\"TEL\"",
    "\"X-FUNAMBOL-FOLDER\"",
    "<VCBEGIN>",
    "<VCEND>",
    "<EXTENSION>",
    "<CONTENTSTRING>",
    "<CONTENTSTRING_QP>",
    "\"=\"",
    "<WS>",
    "<QUOTED_PRINTABLE>",
    "<PARAMSTRING>",
    "<IDENTIFIER>",
  };

}
